### PR TITLE
Fix error due to empty wd response

### LINKED ISSUE #3552: Cannot read property 'name' of null
**Environment:**
 - **WebdriverIO version:** 5.4
- **Mode:** remote Moon
- **If WDIO Testrunner, running sync:** sync
 - **Node.js version:** 10.15.0
 - **NPM version:** 6.7.0
 - **Browser name and version:** Chrome 72
 - **Platform name and version:** linux - alpine
 - **Additional wdio packages used:** 
    "@wdio/allure-reporter": "^5.4.16",
    "@wdio/cli": "^5.4.17",
    "@wdio/dot-reporter": "^5.4.15",
    "@wdio/local-runner": "^5.4.17",
    "@wdio/mocha-framework": "^5.4.14",
    "@wdio/spec-reporter": "^5.4.15",
    "@wdio/sync": "^5.4.14",

**Config of WebdriverIO**
https://gist.github.com/ilyubin/97aff46b5fb8150465cfca5948ca2f0f

**Describe the bug**
The error occurs when trying open the URLs with:

```js
	browser.url(path);
```

In allure.report it looks like:

	POST /session/:sessionId/url
	{
		"url": "https:/<our_site>/search?text=носки"
	}

**Error:**

	Cannot read property 'name' of null
	TypeError: Cannot read property 'name' of null
	at Request._callback (/tests/node_modules/webdriver/build/request.js:130:17)
	at Request.self.callback (/tests/node_modules/request/request.js:185:22)
	at Request.emit (events.js:182:13)
	at Request.EventEmitter.emit (domain.js:442:20)
	at Request.<anonymous> (/tests/node_modules/request/request.js:1161:10)
	at Request.emit (events.js:182:13)
	at Request.EventEmitter.emit (domain.js:442:20)
	at IncomingMessage.<anonymous> (/tests/node_modules/request/request.js:1083:12)
	at Object.onceWrapper (events.js:273:13)
	at IncomingMessage.emit (events.js:187:15)

**Log**
-

**Additional context**
-

### PR DESCRIPTION
**Pull request by yepninja**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fix #3552
Empty wd response leads to the TypeError:
```bash
Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
at Request._callback (/tests/node_modules/webdriver/build/request.js:130:17)
at Request.self.callback (/tests/node_modules/request/request.js:185:22)
at Request.emit (events.js:182:13)
at Request.EventEmitter.emit (domain.js:442:20)
at Request.<anonymous> (/tests/node_modules/request/request.js:1161:10)
at Request.emit (events.js:182:13)
at Request.EventEmitter.emit (domain.js:442:20)
at IncomingMessage.<anonymous> (/tests/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:273:13)
at IncomingMessage.emit (events.js:187:15)
```
Fixed issue #3552

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mgrybyk** [comment]
@yepninja won't it brake responses with status code 200 and body like '' or null ?

File: packages/webdriver/src/utils.js [hunk 1]
```diff
@@ -302,7 +302,7 @@ export function environmentDetector ({ hostname, capabilities, requestedCapabili
  */
 export function getErrorFromResponseBody (body) {
     if (!body) {
-        return null
+        return new Error('unknown error')
```
Comment (CrispusDH) [inline packages/webdriver/src/utils.js]: It might be better to give clearer error message, also we know what happens, for example `Response has empty body`

Comment (WillBrock) [reply packages/webdriver/src/utils.js]: I agree.

**Comment by yepninja** [comment]
Error message is updated.
This error doesn't depends on status code of the response.

File: packages/webdriver/src/utils.js [hunk 2]
```diff
@@ -302,7 +302,7 @@ export function environmentDetector ({ hostname, capabilities, requestedCapabili
  */
 export function getErrorFromResponseBody (body) {
     if (!body) {
-        return new Error('unknown error')
+        return new Error('Response has empty body')
```
Comment (CrispusDH) [inline packages/webdriver/src/utils.js]: Sorry for double typing, from your tests I got that body can be either empty or does not exist. So, better change message to 'Response has either empty body or body doesn't exist'. What do you think?

Comment (yepninja) [reply packages/webdriver/src/utils.js]: Instead of "or" we can throw different errors

**Comment by yepninja** [comment]
Please, rerun travis job.

File: packages/webdriver/src/utils.js (hunk 2 above)
Comment (CrispusDH) [reply packages/webdriver/src/utils.js]: I think it would be great! Good proposal!

**Comment by CrispusDH** [comment]
> Please, rerun travis job.
take a look at this comment, it is current fix
https://github.com/webdriverio/webdriverio/pull/3566#issuecomment-464392958

**Comment by yepninja** [comment]
@christian-bromann thank you for the quick response!
