### PR TITLE
Check caps in `@wdio/selenium-standalone-server` before modifying capabilities

### LINKED ISSUE #6445: Unable to use multiremote feature Error: Invalid or unsupported WebDriver capabilities found ("protocol", "hostname", "port", "path"). Ensure to only use valid W3C WebDriver capabilities
**Environment (please complete the following information):**
 - **WebdriverIO version:** 7.0.3
 - **Mode:** [Standalone mode or WDIO Testrunner] WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** [e.g. sync/async] sync
 - **Node.js version:** 14.15.4
 - **NPM version:** 6.14.10
 - **Browser name and version:** chrome 88.0.4324.150
 - **Platform name and version:** mac big sur
 - **Additional wdio packages used (if applicable):**  all package below are latest
   @wdio/cli
   wdio-chromedriver-service
  @wdio/appium-service
  wdio/mocha-framework
  wdio/local-runner
  wdio/selenium-standalone-service
  wdio/sync
 
**Config of WebdriverIO**
    
```
          capabilities: caps.CrossCaps,
      baseUrl: 'example.com',
      services: [
        ['selenium-standalone', {
          installArgs: {
            version : "3.141.59",
            baseURL : "https://selenium-release.storage.googleapis.com",
            drivers : {
                chrome : {
                    version : "87.0.4280.20",
                    arch    : process.arch,
                    baseURL : "https://chromedriver.storage.googleapis.com"
                }
            }
          },
            args: {
              seleniumArgs: ['-host','localhost','-port', '4444'],
              drivers
            },
        }],  
        // ['browserstack'],
        ['appium',{
          command : 'appium',
          args: {
              debugLogSpacing: true,
              sessionOverride: true,
              port: 4728,
              // allowInsecure:'chromedriver_autodownload'
          },
        }]
      ],
```

```
    caps.ChromeDesktopCaps = 
{
    protocol: 'http',
    hostname: 'localhost',
    port: 4444,
    path: '/wd/hub',
    capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
          args: [
          'user-data-dir=/home/amrka/.config/google-chrome/Default',
          '--disable-web-security',
            'start-maximized',
          ],
        }
    }
  }

caps.AndroidXCaps =
{
    port: 4728,
    path: '/',
    capabilities: {
      platformName: 'Android',
      'appium:deviceName': 'pixel2',
      'appium:avd': 'pixel2',
      'appium:app': 'src/test/resources/test.apk',
      'appium:platformVersion': '10',
      'appium:avdLaunchTimeout': 120000,
      'appium:avdReadyTimeout': 120000,
      'appium:uiautomator2ServerInstallTimeout' :120000,
      'appium:appWaitForLaunch': true,
      'appium:ensureWebviewsHavePages': true,
      'appium:disableWindowAnimation': true,
      'appium:autoGrantPermissions': true,
      'appium:clearSystemFiles': true,
      'appium:nativeWebScreenshot': true,
      'chromedriverExecutable': 'src/test/resources/chromedriver'
    }
}
```

**Describe the bug**

**To Reproduce**
- Upgrade wdio to latest version (v7)
- set multiremote feature as shown in the config above (it was working on previous version)
- execute the test 

**Expected behavior**
should be able to launch the two services instance normally

**Log**

```
    Execution of 1 spec files started at 2021-02-15T17:29:07.711Z

2021-02-15T17:29:07.713Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
2021-02-15T17:29:07.713Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
2021-02-15T17:29:07.714Z INFO @wdio/cli:launcher: Run onPrepare hook
2021-02-15T17:29:07.716Z DEBUG @wdio/appium-service: Will spawn Appium process: appium --base-path / --debug-log-spacing --session-override --port 4728
2021-02-15T17:29:08.255Z DEBUG @wdio/appium-service: Appium started with ID: 2206
2021-02-15T17:29:09.142Z DEBUG @wdio/cli:utils: Finished to run "onPrepare" hook in 1428ms
2021-02-15T17:29:09.145Z INFO @wdio/cli:launcher: Run onWorkerStart hook
2021-02-15T17:29:09.145Z DEBUG @wdio/cli:utils: Finished to run "onWorkerStart" hook in 0ms
2021-02-15T17:29:09.146Z INFO @wdio/local-runner: Start worker 0-0 with arg: src/test/config/xplatform.conf.js
[0-0] 2021-02-15T17:29:09.407Z INFO @wdio/local-runner: Run worker command: run
[0-0] 2021-02-15T17:29:10.081Z DEBUG @wdio/config:utils: Found '@babel/register' package, auto-compiling files with Babel
[0-0] 2021-02-15T17:29:10.082Z DEBUG @wdio/local-runner:utils: init multiremote session
[0-0] 2021-02-15T17:29:10.092Z DEBUG @wdio/utils:initialiseServices: initialise service "selenium-standalone" as NPM package
[0-0] 2021-02-15T17:29:10.093Z DEBUG @wdio/utils:initialiseServices: initialise service "appium" as NPM package
[0-0] RUNNING in MultiRemote - /src/test/specs/spec-android/CrossPlatform_Suite.js
[0-0] 2021-02-15T17:29:10.200Z DEBUG @wdio/local-runner:utils: init multiremote session
[0-0] 2021-02-15T17:29:10.202Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-02-15T17:29:10.202Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2021-02-15T17:29:10.202Z ERROR @wdio/runner: Error: Invalid or unsupported WebDriver capabilities found ("protocol", "hostname", "port", "path"). Ensure to only use valid W3C WebDriver capabilities (see https://w3c.github.io/webdriver/#capabilities).
    at Object.startWebDriverSession (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/webdriver/build/utils.js:38:19)
    at Function.newSession (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/webdriver/build/index.js:56:59)
    at Object.exports.remote (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/webdriverio/build/index.js:56:43)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/webdriverio/build/index.js:82:26
    at async Promise.all (index 0)
    at Object.exports.multiremote (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/webdriverio/build/index.js:81:5)
    at Object.initialiseInstance (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/@wdio/runner/build/utils.js:69:21)
    at Runner._startSession (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/@wdio/runner/build/index.js:198:56)
    at Runner._initSession (/Users/amrka/Desktop/work/tracker/Appium-wdio/node_modules/@wdio/runner/build/index.js:160:25)
2021-02-15T17:29:10.320Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in MultiRemote - /src/test/specs/spec-android/CrossPlatform_Suite.js
2021-02-15T17:29:10.321Z INFO @wdio/cli:launcher: Run onComplete hook
2021-02-15T17:29:10.321Z INFO @wdio/selenium-standalone-service: shutting down all browsers
2021-02-15T17:29:10.321Z DEBUG @wdio/appium-service: Appium (pid: 2206) killed
2021-02-15T17:29:10.321Z DEBUG @wdio/cli:utils: Finished to run "onComplete" hook in 0ms
```

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

We modify the capabilities when a user applies a service like `@wdio/selenium-standalone-service` to ensure we can connect to the server that is being launched. Unfortunately we also do this for capabilities that were not suppose to run on the standalone server.

This patch adds a check to ensure caps are only changed that would be also run on Selenium Standalone.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

fixes #6445

### CODE REVIEW

File: packages/wdio-selenium-standalone-service/src/utils.ts [hunk 1]
```diff
@@ -19,3 +31,17 @@ export function getFilePath (filePath: string, defaultFilename: string): string
...
+ * find whether a browser session could be supported by the selenium-standalone service
+ * @param   {Capabilities.Capabilities} capabilities capabilities used for the session
+ * @returns {Boolean}                                true, if capabilities suggest a supported platform
+ */
+export function hasCapsWithSupportedBrowser (capabilities: Capabilities.Capabilities) {
+    if (!capabilities.browserName) {
+        return false
+    }
+    return SUPPORTED_CAPABILITIES.includes(
+        capabilities.browserName?.toLocaleLowerCase()
```
Comment (erwinheitzman) [inline packages/wdio-selenium-standalone-service/src/utils.ts:45]:
```suggestion
        capabilities.browserName?.toLowerCase()
```

**Review by erwinheitzman — CHANGES_REQUESTED** [review]
One small remark

File: packages/wdio-selenium-standalone-service/src/utils.ts (hunk 1 above)
Comment (erwinheitzman) [reply packages/wdio-selenium-standalone-service/src/utils.ts:45]: The resason for this is that toLocaleLowerCase is not meant to be used like this.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/toLocaleLowerCase

**Comment by christian-bromann** [comment]
Addressed the remark, I will move forward, let me know if anything else is missing.
