### PR TITLE
fix(webdriverio): fix script execution

### LINKED ISSUE #13443: [🐛 Bug]: WDIO v9 breaks backwards compatibility of `executeAsync` when used with BiDi
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [
    {
      // capabilities for local browser web tests
      browserName: "chrome",
      // "wdio:enforceWebDriverClassic": true, - toggled on to check usage differences
    },
  ]
```

### What happened?

Toggling `wdio:enforceWebDriverClassic` or using v8 passing a statement string to `browser.executeAsync` executes as expected, example: 

```ts
const res = await browser.executeAsync(`
    const callback = arguments[arguments.length - 1];
    return Promise.resolve(arguments[0] * 2).then(callback);
`, 6);

console.log({ res }); // 12
```

When using WDIO v9 which defaults to use the BiDi protocol, I get an error: 

```
[0-0] 2024-08-23T17:36:47.136Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[391 bytes]>","awaitPromise":true,"arguments":[{"type":"number","value":6}],"target":{"context":"C510048CD98884A967DA0A57E837406F"}}
[0-0] {
[0-0]   res: {
[0-0]     error: {
[0-0]       message: "SyntaxError: Unexpected token 'const'",
[0-0]       columnNumber: 26,
[0-0]       exception: [Object],
[0-0]       lineNumber: 9,
[0-0]       stackTrace: [Object]
[0-0]     }
[0-0]   }
[0-0] }
```
To get around this I've had to replace my string with a function: 

```ts
const res = await browser.executeAsync(function myFunc(...args: any[]) {
  return Promise.resolve(args[0] * 2).then(args[args.length - 1]);
}, 6);

console.log({ res }); // 12
```

This appears to have been introduced in: https://github.com/webdriverio/webdriverio/pull/13389

### What is your expected behavior?

`browser.executeAsync` Function to execute as expected regardless if passed as a string or function declaration.

### How to reproduce the bug.

With WDIO v9 use: 

```ts
const res = await browser.executeAsync(`
    const callback = arguments[arguments.length - 1];
    return Promise.resolve(arguments[0] * 2).then(callback);
`, 6);

console.log({ res }); // 12
```

### Relevant log output

```typescript
[0-0] 2024-08-23T17:36:47.136Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[391 bytes]>","awaitPromise":true,"arguments":[{"type":"number","value":6}],"target":{"context":"C510048CD98884A967DA0A57E837406F"}}
[0-0] {
[0-0]   res: {
[0-0]     error: {
[0-0]       message: "SyntaxError: Unexpected token 'const'",
[0-0]       columnNumber: 26,
[0-0]       exception: [Object],
[0-0]       lineNumber: 9,
[0-0]       stackTrace: [Object]
[0-0]     }
[0-0]   }
[0-0] }
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### LINKED ISSUE #13444: [🐛 Bug]: browser.execute breaks when declaring functions
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.0.7

### Node.js Version

v20.13.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
}
```

### What happened?

When using `browser.execute` with a script that declares a function, the script gets transformed in such a way that no longer runs inside a browser. This works fine in v8.

For example:

```typescript
browser.execute(() => {
    function fn() {}
});
```

The above gets transformed, and the script that's injected onto the page becomes:

```javascript
((...args) => {
      function callFunction(f, args) {
        const deserializedThis = args.shift();
        const deserializedArgs = args;
        return f.apply(deserializedThis, deserializedArgs);
      }
      return callFunction((
        ()=>{function fn(){}__name(fn,"fn")}
      ), args);
    })
```

`__name` doesn't exist, so it throws an error.

### What is your expected behavior?

It should work.

### How to reproduce the bug.

I've made a minimal reproducible example at https://github.com/Dinnerbone/wdio-bug-repro/

The actual test that breaks is https://github.com/Dinnerbone/wdio-bug-repro/blob/main/test/specs/test.e2e.ts

This was generated with `npx create-wdio@latest` just moments ago, the only change is that test.

### Relevant log output

```
[0-0] 2024-08-23T18:20:53.484Z INFO webdriver: BIDI COMMAND script.callFunction {"functionDeclaration":"<Function[53 bytes]>","awaitPromise":false,"arguments":[],"target":{"context":"29984D43E1634C4142BF795BC9F87764"}}
[0-0] AssertionError in "Javascript execution.works"
AssertionError [ERR_ASSERTION]: {
  error: {
    columnNumber: 28,
    exception: {
      type: 'error'
    },
    lineNumber: 6,
    message: 'ReferenceError: __name is not defined',
    stackTrace: {
      callFrames: [
        {
          columnNumber: 28,
          functionName: '',
          lineNumber: 6,
          url: ''
        },
        {
          columnNumber: 17,
          functionName: 'callFunction',
          lineNumber: 3,
          url: ''
        },
        {
          columnNumber: 13,
          functionName: '',
 ... == 'Success!'
    at Context.<anonymous> (C:\Users\Dinnerbone\workspace\personal\wdio-bug\test\specs\test.e2e.ts:13:16)
    at Context.executeAsync (C:\Users\Dinnerbone\workspace\personal\wdio-bug\node_modules\@wdio\utils\build\index.js:1488:20)
    at Context.testFrameworkFnWrapper (C:\Users\Dinnerbone\workspace\personal\wdio-bug\node_modules\@wdio\utils\build\index.js:1559:14)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #13444
fixes #13443

In addition, this patch will:

- create nicer stack traces and print the line that caused the error, e.g.
  given following script:
    ```ts
    await browser.execute(async () => {
        const a: number = 1
        console.log('Hello Bidi')
        if (a) {
            if (a) {
                throw new Error('Hello Bidi')
            }
        }
    })
    ```
   ```
    Error: Error: Hello Bidi
        at Context.<anonymous> (/path/to/webdriverio/e2e/wdio/headless/bidi.e2e.ts:207:28)
        207 │ if(a){if(a){throw new Error("Hello Bidi")}}}
            ╵ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

        at parseScriptResult (/path/to/webdriverio/build/index.js:750:19)
        at Browser.execute (/path/to/webdriverio/build/index.js:2982:12)
        at Browser.wrapCommandFn (/path/to/wdio-utils/build/index.js:1368:23)
        at Context.<anonymous> (/path/to/webdriverio/e2e/wdio/headless/bidi.e2e.ts:207:28)
        at Context.executeAsync (/path/to/wdio-utils/build/index.js:1488:20)
        at Context.testFrameworkFnWrapper (/path/to/wdio-utils/build/index.js:1559:14)
    ```
- it will deprecate `executeAsync` as there is not need for it anymore

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### CODE REVIEW

File: packages/webdriverio/src/polyfill.ts [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+         *
+         * @see https://github.com/evanw/esbuild/issues/2605
+         */
+        const polyfill = () => {
+            const closure = new Function(
+                'var __defProp = Object.defineProperty;' +
+                'var __name = (target, value) => __defProp(target, \'name\', { value, configurable: true });' +
+                'globalThis.__name = __name;'
+            )
+            return closure()
```
Comment (danielhjacobs) [inline packages/webdriverio/src/polyfill.ts:46]: Are you sure this is all that's needed. See https://github.com/evanw/esbuild/issues/607#issuecomment-747843078:

> The `__name` function is just one of many code transforms that esbuild can make that assume functions aren't arbitrarily recompiled by converting them to a string and feeding them to `eval`. Other examples include converting `a ** b` to `__pow(a, b)` and `{...a, ...b}` to `__assign({}, a), b)`.

Comment (christian-bromann) [reply packages/webdriverio/src/polyfill.ts:46]: Are you aware of more polyfills that are needed here?

Comment (danielhjacobs) [reply packages/webdriverio/src/polyfill.ts:46]: Ruffle doesn't need any others for its tests currently but that doesn't means others won't or that future tests won't require others. I think any fron this file might be needed:

https://github.com/evanw/esbuild/blob/main/internal/runtime/runtime.go

As stated in https://github.com/evanw/esbuild/issues/607#issuecomment-747843078
> Preserving the value of `toString()` on a function expression is not a design goal of esbuild. If that use case is important to you, it would be best to either arrange for the code to be passed as a string instead, or to use another tool that supports preserving the value of `toString()` on a function.

Comment (christian-bromann) [reply packages/webdriverio/src/polyfill.ts:46]: Understood. The amount of usecases for WDIO vs someone compiling a TS project with Esbuild is very different, e.g. no one would export variables from the test. My idea was to add more polyfills when needed as this seems the simplest approach while keeping the codebase as simple as possible.

**Comment by lararojasmr** [comment]
@christian-bromann those changes fix https://github.com/webdriverio/webdriverio/issues/13444 wihtout BiDi? I'm getting this issue now.

**Comment by christian-bromann** [comment]
@lararojasmr non bidi sessions have not been impacted by this issue.
