### PR TITLE
(webdriverio): polish intercepted errors

### LINKED ISSUE #8507: [🐛 Bug]: no lines or helpful info displayed for "element not interactable"
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.19

### Node.js Version

18.3.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
browserName: "chrome",
browserVersion: "latest",
platformName: "MacOS Catalina"
}
```

### What happened?

I'm getting this error.  It has no helpful info whatsoever, no line numbers, nothing about what object is not interactable.  below is the entirety of the output:

### What is your expected behavior?

_No response_

### How to reproduce the bug.

run npx wdio

### Relevant log output

```typescript
[chrome 103.0.5060.114 mac os x #0-0] element not interactable
  (Session info: chrome=103.0.5060.114)
[chrome 103.0.5060.114 mac os x #0-0] element not interactable: element not interactable
[chrome 103.0.5060.114 mac os x #0-0]   (Session info: chrome=103.0.5060.114)
[chrome 103.0.5060.114 mac os x #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:	 0 passed, 1 failed, 1 total (100% completed) in 00:01:31
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Resolves #8507 

## Types of changes

- [x] Polish (an improvement for an existing feature)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [x] Back-ported PR at #12534

### CODE REVIEW

**Review by christian-bromann — APPROVED** [review]
Awesome 👍

File: packages/webdriverio/src/middlewares.ts [hunk 1]
```diff
@@ -38,13 +35,19 @@ export const elementErrorHandler = (fn: Function) => (commandName: string, comma
 
                 return result
             } catch (err: any) {
+                if (err.name === 'element not interactable') {
```
Comment (christian-bromann) [inline packages/webdriverio/src/middlewares.ts:38]: I believe in Safari the error name is different which is why the CI test is failing, mind giving it a try with Safari?

**Review by christian-bromann — COMMENTED** [review]
One comment on the CI failure.

File: packages/webdriverio/src/middlewares.ts (hunk 1 above)
Comment (erwinheitzman) [reply packages/webdriverio/src/middlewares.ts:38]: I took the stacktrace from another error which had the session info. Since I added the tests without having the fix from the other PR in this I made a guess and seems like this doesn't have the session info when running Safari so I it is easily solved 👍
Will fix it and when green merge it
