### PR TITLE
Fixes #6068

### LINKED ISSUE #6068: Cannot change outputDir for a new Appium session while testing
Hello,
I am a maintainer of [React Native Tools](https://github.com/microsoft/vscode-react-native) VS Code extension, which is used for debugging React Native applications in VS Code. We use WebdriverIO package for testing of the extension.

**Environment:**
 - **WebdriverIO version:** 6.6.7
 - **Mode:** Standalone mode
 - **Node.js version:** 10.19.0
 - **NPM version:** 6.13.4
 - **Platform names and versions:** Windows 10, macOS 10.15.7, Linux Ubuntu 18.04
 - **Appium**: 1.18.2

**Describe the bug**
We use `Appium` as a server. In our tests we create a WebdriverIO session per each test. We'd like to have logs from each session in separate `wdio.log` files. We specify `outputDir` parameter for each session, but the only first configuration is taken into account. So logs from the second session are written in the `.log` file of the first session and so on.

**To Reproduce**
Try to create 2 WebdriverIO sessions sequentially with different `outputDir` parameters.

1. Start Appium using the command `appium` in the terminal
2. Add capabilities to the configurations below and run the script

```js
const wdio = require("webdriverio");

const opts1 = {
    path: '/wd/hub',
    port: 4723,
    capabilities: { /*any capabilities*/ },
    logLevel: "trace",
    outputDir: `${__dirname}/1`
};

const opts2 = {
  path: '/wd/hub',
  port: 4723,
  capabilities: { /*any capabilities*/ },
  logLevel: "trace",
  outputDir: `${__dirname}/2`
};
  
  async function main () {
    let client = await wdio.remote(opts1);

    console.log("ses1-sleep");
    await sleep(4000);

    await client.deleteSession();

    console.log("ses1 - end");
    await sleep(15000);

    console.log("ses2");
    client = await wdio.remote(opts2);
  
    console.log("ses2-sleep");
    await sleep(6000);

    console.log("ses2 - pre end");
    await client.deleteSession();
  }
  
  main();

async function sleep(time) {
  await new Promise(resolve => {
      const timer = setTimeout(() => {
          clearTimeout(timer);
          resolve();
      }, time);
  });
}
```

After that logs from the both sessions were written to the log file for the first session
image

**Expected behavior**
`wdio.log` logs for each session are written in different files (in the folders `1` and `2`).

**Additional context**
We investigated this issue and found out that [`process.env.WDIO_LOG_PATH`](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/src/index.js#L50) is responsible for logging directory. While debugging we found out this variable is changed on each session creation. We also found that a log file is created [here](https://github.com/webdriverio/webdriverio/blob/master/packages/wdio-logger/src/node.ts#L63-L65). We revealed such behavior that according to the current condition if the `process.env.WDIO_LOG_PATH` is changed and the 'logFile' exists, a new file won't be created. So WebdriverIO continues to write logs to the first created file.
Screen Shot 2020-11-05 at 10 36 21

### PR DESCRIPTION
**Pull request by RedMickey**
## Proposed changes

Fixes https://github.com/webdriverio/webdriverio/issues/6068

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@RedMickey would you mind signing the CLA?

File: packages/webdriver/src/command.ts [hunk 1]
```diff
@@ -99,6 +99,10 @@ export default function (
             }
 
             this.emit('result', { method, endpoint, body, result })
+
+            if (commandUsage.includes('deleteSession')) {
```
Comment (christian-bromann) [inline packages/webdriver/src/command.ts:103]: Let's be more strict here.

```suggestion
            if (command === 'deleteSession') {
```

**Review by christian-bromann — CHANGES_REQUESTED** [review]

File: packages/webdriver/src/command.ts [hunk 2]
```diff
@@ -99,6 +101,10 @@ export default function (
             }
 
             this.emit('result', { method, endpoint, body, result })
+
+            if (commandUsage === DELETE_SESSION_COMMAND) {
```
Comment (christian-bromann) [inline packages/webdriver/src/command.ts:105]: Why not just?
```suggestion
            if (command === 'deleteSession') {
```

File: packages/webdriver/src/command.ts [hunk 3]
```diff
@@ -8,6 +8,8 @@ import { BaseClient } from './types'
 
 const log = logger('webdriver')
 
+const DELETE_SESSION_COMMAND = 'deleteSession()'
+
```
Comment (christian-bromann) [inline packages/webdriver/src/command.ts:12]:
```suggestion
```

File: packages/wdio-logger/tests/node.test.ts [hunk 4]
```diff
@@ -228,6 +229,24 @@ describe('wdio-logger node', () => {
...
+
+                const log = nodeLogger('test-logFile5')
+                log.info('foo')
+
+                nodeLogger.clearLogger()
+
+                process.env.WDIO_LOG_PATH = 'wdio.test.log2'
+
+                log.info('bar')
+
```
Comment (christian-bromann) [inline packages/wdio-logger/tests/node.test.ts:244]:
```suggestion
```

File: packages/wdio-logger/tests/node.test.ts [hunk 5]
```diff
@@ -228,6 +229,24 @@ describe('wdio-logger node', () => {
...
+            it('should be possible to change output directory', () => {
+                process.env.WDIO_LOG_PATH = 'wdio.test.log'
+
+                const log = nodeLogger('test-logFile5')
+                log.info('foo')
+
+                nodeLogger.clearLogger()
+
+                process.env.WDIO_LOG_PATH = 'wdio.test.log2'
+
```
Comment (christian-bromann) [inline packages/wdio-logger/tests/node.test.ts:242]:
```suggestion
```

File: packages/wdio-logger/tests/node.test.ts [hunk 6]
```diff
@@ -228,6 +229,24 @@ describe('wdio-logger node', () => {
             expect(write.mock.results[1].value).toContain('test-logFile4: Error: bar')
         })
 
+        describe('clearLogger', () => {
+            it('should be possible to change output directory', () => {
+                process.env.WDIO_LOG_PATH = 'wdio.test.log'
+
+                const log = nodeLogger('test-logFile5')
+                log.info('foo')
+
```
Comment (christian-bromann) [inline packages/wdio-logger/tests/node.test.ts:238]:
```suggestion
```

File: packages/wdio-logger/tests/node.test.ts [hunk 7]
```diff
@@ -228,6 +229,24 @@ describe('wdio-logger node', () => {
             expect(write.mock.results[1].value).toContain('test-logFile4: Error: bar')
         })
 
+        describe('clearLogger', () => {
+            it('should be possible to change output directory', () => {
+                process.env.WDIO_LOG_PATH = 'wdio.test.log'
+
```
Comment (christian-bromann) [inline packages/wdio-logger/tests/node.test.ts:235]:
```suggestion
```

**Review by christian-bromann — COMMENTED** [review]
some formatting

**Review by christian-bromann — APPROVED** [review]
👍  thanks for the fix and congrats to your first WebdriverIO contribution 🚀

File: packages/webdriver/src/command.ts (hunk 2 above)
Comment (RedMickey) [reply packages/webdriver/src/command.ts]: I'm sorry for the delay, I think we should use `deleteSession()` instead of `deleteSession` here, because we get the `deleteSession()` command string.

Screen Shot 2020-11-09 at 09 29 56
