### PR TITLE
fix(create-wdio): add missing ts dependencies

### LINKED ISSUE #14833: [🐛 Bug]: `create-wdio` is missing dependencies with types when TypeScript is selected
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.20.0

### Node.js Version

v22.12.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
-
```

### What happened?

When TypeScript is selected in `create-wdio` starter, dependencies with types are missing.

The `tsconfig.json` usually references the following globals:
```json
"types": [
    "node",
    "jasmine",
    "@wdio/globals/types",
    "expect-webdriverio",
],
```
but corresponding dependencies are missing in `package.json`, so I have to add them manually: `pnpm i -D @types/node @wdio/globals expect-webdriverio`

### What is your expected behavior?

I would expect missing dependencies with types to be explicitly listed in `package.json`

### How to reproduce the bug.

1. `pnpm create wdio@latest`
2. Choose "E2E testing", agree to use TypeScript
3. Open `tsconfig.json` in VSCode and it will complain

Image
4. `typescript` package is also missing. Add it (`pnpm i -D typescript`) and execute `pnpm tsc --noEmit`, you will get "TS2688"-errors

### Relevant log output

```typescript
❯ pnpm tsc --noEmit
error TS2688: Cannot find type definition file for '@wdio/globals/types'.
  The file is in the program because:
    Entry point of type library '@wdio/globals/types' specified in compilerOptions

  tsconfig.json:12:13
    12             "@wdio/globals/types",
                   ~~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.

error TS2688: Cannot find type definition file for 'expect-webdriverio'.
  The file is in the program because:
    Entry point of type library 'expect-webdriverio' specified in compilerOptions

  tsconfig.json:13:13
    13             "expect-webdriverio",
                   ~~~~~~~~~~~~~~~~~~~~
    File is entry point of type library specified here.


Found 2 errors.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by mccmrunal**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
This PR fixes an issue where 
create-wdio
 was missing essential TypeScript dependencies (@types/node, @wdio/globals, expect-webdriverio) when generating a new project with TypeScript enabled. This ensures that the generated project has all necessary types for compilation and execution without requiring manual dependency installation.

Fixes #14833
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments
The fix involves updating 
npmInstall
 in 
packages/create-wdio/src/utils.ts
 to explicitly add the missing dependencies to packagesToInstall when isUsingTypeScript is true. Verified with new test cases covering both Jasmine and Mocha frameworks.
[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/create-wdio/src/utils.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import url from 'node:url'
 import path from 'node:path'
 import util, { promisify } from 'node:util'
 import fs from 'node:fs/promises'
-import { execSync,  } from 'node:child_process'
+import { execSync, } from 'node:child_process'
```
Comment (christian-bromann) [inline packages/create-wdio/src/utils.ts]:
```suggestion
import { execSync } from 'node:child_process'
```
