### PR TITLE
'name' find strategy should be used if isMobile is used even when w3c is used

### LINKED ISSUE #3738: Mobile name selector doesn't work  in WebdriverIO 5
**Environment:**
 - **WebdriverIO version:** [5.7.2]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [sync]
 - **Node.js version:** [8.11.4]
 - **NPM version:** [5.6.0]
 - **Platform name and version:** [e.g. MacOS 10.13.6 ]
 - **Additional wdio packages used (if applicable):** [webdriverio]

**Config of WebdriverIO**
```
runner: 'local',
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 200000,
        require: [
            'tsconfig-paths/register']
     },

    sync: true,
    logLevel: 'warn',
    deprecationWarnings: true,
    bail: 0,
    waitforTimeout: 20000,
    connectionRetryTimeout: 90000,
    connectionRetryCount: 3,
    reporters: ['spec', ['allure', {
        outputDir: 'allure-results',
        disableWebdriverStepsReporting: true,
        disableWebdriverScreenshotsReporting: false,
    }]],


    port: 4723,
    maxInstances: 1,

    capabilities:{
        deviceName: 'iPhone 6',
        platformName: 'iOS',
        automationName: 'XCUITest',
        platformVersion: '11.4',
        app: path.resolve('../ios/build/Build/Products/Debug-iphonesimulator/zoom.app'),

        noReset: false,
        fullReset: false,
        newCommandTimeout: 240,
    },

    before: function() {
        require('ts-node').register({ files: true });
        const chai = require('chai');
        global.expect = chai;
        chai.should();


        browser.addCommand('request', function (config) {
            return Axios.request(config).then((response)=>{return response.data});
        })
    },
```
**Describe the bug**
I've noticed that since version 5 (actually 5.7.2 that I have installed) mobile name selector strategy does not work.  I've checked the code, and looks like this condition  https://github.com/webdriverio/webdriverio/blob/afb0fa78e00feeddb824753c4550a704d8f9156b/packages/webdriverio/src/utils.js#L85 could cause the problem. 
While running test with such selector I'm getting `Locator Strategy 'css selector' is not supported for this session`

Comparing to v4.14.1 https://github.com/webdriverio/webdriverio/blob/6866934436a32d99aa5123d1f6e983e3d696f2aa/lib/helpers/findElementStrategy.js#L102 there is no !isW3C check which causes problem. 
Is it necessary to put it there? I've removed it locally and now my name selector works.

**To Reproduce**
1. Write mobile test with name selector eg. '[name="test-locator"]' 

**Expected behavior**
Name selector should work on mobile as well.

### PR DESCRIPTION
**Pull request by CrispusDH**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fix #3738 . Inside `findStrategy` method we have a logic that uses `css selector` in case when `w3c` is `true`. When running tests on mobile (`isMobile` is `true`) it should use `name` anyway.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriverio/src/utils.js [hunk 1]
```diff
@@ -81,8 +81,11 @@ export const findStrategy = function (value, isW3C, isMobile) {
         value = value.replace(/<|>|\/|\s/g, '')
 
     // use name strategy if value queries elements with name attributes for JSONWP
+    // or if isMobile is used even when w3c is used
     // e.g. "[name='myName']" or '[name="myName"]'
-    } else if (!isW3C && value.search(/^\[name=("|')([a-zA-z0-9\-_. ]+)("|')]$/) >= 0) {
+    } else if (isMobile
+        ? value.search(/^\[name=("|')([a-zA-z0-9\-_. ]+)("|')]$/) >= 0
+        : !isW3C && value.search(/^\[name=("|')([a-zA-z0-9\-_. ]+)("|')]$/) >= 0) {
```
Comment (christian-bromann) [inline packages/webdriverio/src/utils.js]: Can we move `value.search(/^\[name=("|')([a-zA-z0-9\-_. ]+)("|')]$/) >= 0` into a const somewhere upwards?

Comment (CrispusDH) [reply packages/webdriverio/src/utils.js]: Yep, I'm thinking about refactor this function in another PR.
