### PR TITLE
Properly report Sauce job for Mocha retries

### LINKED ISSUE #5989: SauceLabs dashboard displays test as failed when it has passed on retry
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.6.2
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.13.0
 - **NPM version:** 6.12.0
 - **Browser name and version:** N/A
 - **Platform name and version:** N/A
 - **Additional wdio packages used (if applicable):** @wdio/cli, @wdio/dot-reporter, @wdio/junit-reporter, @wdio/local-runner, @wdio/mocha-framework, @wdio/reporter, @wdio/sauce-service, @wdio/selenium-standalone-service, @wdio/spec-reporter, @wdio/sync

**Config of WebdriverIO**
```
'use strict';
 
const chai = require('chai');
 
global.assert = chai.assert;
global.chai = chai;
chai.Should();
 
exports.config = {
  user: process.env.SAUCE_USERNAME,
  key: process.env.SAUCE_ACCESS_KEY,
  region: 'us-west-1',
 
  maxInstances: 1,
  capabilities: [
      {
        browserName: 'chrome',
        platformName: 'Windows 10',
        browserVersion: '83.0',
        'sauce:options': {
          parentTunnel: '<insert tunnel name>',
          public: 'team',
          screenResolution: '1280x960',
          tunnelIdentifier: 'Primary',
          extendedDebugging: true,
        }
      }
  ],
  execArgv: [],
  sync: true,
  logLevel: 'trace',
  coloredLogs: true,
  deprecationWarnings: true,
  bail: 0,
  screenshotPath: 'screenshots',
  baseUrl: '',
  outputDir: './wdio-log',
  waitforTimeout: 60000,
  connectionRetryTimeout: 120000,
  connectionRetryCount: 3,
  services: [
    [
      'sauce',
      {
        sauceConnect: true,
        sauceConnectOpts: {
          parentTunnel: '<insert tunnel name here>',
          tunnelIdentifier: 'Primary',
        },
      },
    ],
  ],
  framework: 'mocha',
  reporters: [
    [
      'junit',
      {
        outputDir: './reports/',
        outputFileFormat: function (opts) {
          return `results-${opts.cid}.${opts.capabilities.browserName}-v${opts.capabilities.browserVersion}.xml`;
        },
      },
    ],
  ],
 
  mochaOpts: {
    retries: 2,
    timeout: 0,
   ui: 'bdd',
  }
};
```

**Describe the bug**
wdio config has been set so that a test will retry upon a failure.  When a test passes on a retry, SauceLabs dashboard still indicates the test as failed even though it has passed.

**To Reproduce**
1. Set up wdio configuration to allow for retries.
2. Set up a test to fail and then pass on a retry.
3. Login to SauceLabs and observe the test status.

```
'use strict';
 
describe(`custom-test`, function () {
  let tries = 0;

  it(`passes`, function () {
    console.log('Starting test.');
 
    if (tries < 1) {
      ++tries;
      console.log('Failing intentionally.');
      chai.expect(true).to.be.false;
    }
 
    console.log('Passing.');
    chai.expect(true).to.be.true;
  });
});
```

**Expected behavior**
SauceLabs dashboard to correctly display test status for tests that pass on retry.

**Log**
1. [console.log](https://gist.github.com/jiyoon-sb/e82450937a346ab6abc93eb5fd8f8452#file-console-log)
2. [wdio-0-0.log](https://gist.github.com/jiyoon-sb/b9623b683c2ce3c2fe7f425ceed1f134#file-wdio-0-0-log)
3. [wdio.log](https://gist.github.com/jiyoon-sb/e54ed0195cd8079adb9fa697dd2118c4#file-wdio-log)

**Additional context**
A SauceLabs support ticket was created and they have responded indicating they have spoke with the main contributor for the WDIO project and confirms they think it is a WDIO issue.

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

If Mocha retries a test and that test eventually passes the job is still reported as failure on Sauce Labs. This patch fixes this.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

fixes #5989

### CODE REVIEW

File: packages/wdio-sauce-service/src/service.js [hunk 1]
```diff
@@ -90,6 +90,23 @@ export default class SauceService {
     }
 
     afterTest (test, context, results) {
+        /**
+         * remove failure if test was retried and passted
```
Comment (martinfrancois) [inline packages/wdio-sauce-service/src/service.js:94]:
```suggestion
         * remove failure if test was retried and passed
```

File: packages/wdio-sauce-service/src/service.js [hunk 2]
```diff
@@ -90,6 +90,23 @@ export default class SauceService {
...
+        if (test._retriedTest && results.passed) {
+            --this.failures
+            return
+        }
+
+        /**
+         * don't bump failure number if test was retried and still failed
+         * > Mocha only
+         */
+        if (test._retriedTest && !results.passed && test._currentRetry < test._retries) {
```
Comment (mgrybyk) [inline packages/wdio-sauce-service/src/service.js:106]: If we don't bump failures do we still need to remove it?

Comment (christian-bromann) [reply packages/wdio-sauce-service/src/service.js:106]: nope, we only remove it if the test passed at the end

**Comment by christian-bromann** [comment]
@mgrybyk @martinfrancois any other comments or is this ready to go?

File: packages/wdio-sauce-service/src/service.js [hunk 3]
```diff
@@ -90,6 +90,23 @@ export default class SauceService {
     }
 
     afterTest (test, context, results) {
+        /**
+         * remove failure if test was retried and passed
+         * > Mocha only
+         */
+        if (test._retriedTest && results.passed) {
+            --this.failures
```
Comment (mgrybyk) [inline packages/wdio-sauce-service/src/service.js:98]: I mean do we need to have this one if https://github.com/webdriverio/webdriverio/pull/5997/files#r506921171

**Review by mgrybyk — APPROVED** [review]
LGTM
Have one question though

File: packages/wdio-sauce-service/src/service.js (hunk 3 above)
Comment (christian-bromann) [reply packages/wdio-sauce-service/src/service.js:98]: Yes, the order is as follows:

- test fails: `this.failures++` (failure count: 1)
- test retries and fails: we return without adding to failure count
- test retries and fails: we return without adding to failure count
- test finally passes: we remove failure count

which resolves in having a total failure count of 0
