### PR TITLE
fix: direction and scrollableElement error

### LINKED ISSUE #14019: [🐛 Bug]: Swipe method will not recognize scrollableElement if user pass it as variable and also type error
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.5

### Node.js Version

22.12

### Mode

Standalone Mode

### Which capabilities are you using?

_No response_

### What happened?

Screenshot 2025-01-01 at 11 12 36
When using swipe method I passed scrollableElement as variable the code not work and returned an error
`Error: Malformed type for "elementId" parameter of command getElementRect
Expected: string
Actual: object`
Also as in the image the scrollEle also has type error even when it's the same as the doc example
`Type 'ChainablePromiseElement' is not assignable to type 'Element'.
  Types of property 'parent' are incompatible.
    Type 'Promise<Browser | Element | MultiRemoteBrowser>' is not assignable to type 'Browser | Element'.ts(2322)`
 

### What is your expected behavior?

_No response_

### How to reproduce the bug.

declare the scrollableElement as variable and pass that variable into swipe method

### Relevant log output

```typescript
Error: Malformed type for "elementId" parameter of command getElementRect
Expected: string
Actual: object

For more info see https://w3c.github.io/webdriver/#dfn-get-element-rect
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by wswebcreation**
This PR fixes #14019

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Review by wswebcreation — COMMENTED** [review]
I'm trying to debug the "scrollableElement" malformed id error, but can't reproduce it. Still checking it

**Comment by wswebcreation** [comment]
> I'm trying to debug the "scrollableElement" malformed id error, but can't reproduce it. Still checking it

This doens't seem to be an issue, but the code of the user is. So stopping my investigation. PR is ready to review :D

File: packages/webdriverio/src/commands/mobile/swipe.ts [hunk 1]
```diff
@@ -136,7 +136,7 @@ async function calculateFromTo({
     //    - bottom
     //    - left
     //    of the element. These positions will contain the x and y coordinates on where to put the finger
-    const { x, y, width, height } = await browser.getElementRect(scrollableElement?.elementId)
+    const { x, y, width, height } = await browser.getElementRect(await scrollableElement?.elementId)
```
Comment (wswebcreation) [inline packages/webdriverio/src/commands/mobile/swipe.ts:139]: @christian-bromann 

Hmm, might this fix the error @dinh246 was talking about? I first tested it on my machine with the old code and there was no issue. Then after running the adjusted appium-boilerplate code on GHA+Sauce I got the same error with the current `webdriverio`package, see https://github.com/webdriverio/appium-boilerplate/actions/runs/12587209761/job/35082582798#step:9:221

Comment (wswebcreation) [reply packages/webdriverio/src/commands/mobile/swipe.ts:139]: Hmm, it might be, it's now also fails on iOS, see https://github.com/webdriverio/appium-boilerplate/actions/runs/12587209746/job/35082583004#step:7:254

This seems to be working on my machine due to the M3 and not on slower machines. So this fix might solve the issue

**Review by christian-bromann — APPROVED** [review]
This makes sense to me 👍
