### PR TITLE
@devtools: Enable file uploads by changing input elements' value

### LINKED ISSUE #5090: devtools: Cannot upload files though input elements
**Environment:**
 - **WebdriverIO version:** latest v5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Browser name and version:** chrome, firefox
 - **Platform name and version:** Mac OSX

**Config of WebdriverIO**
Any v5 with devtools `automationProtocol`

**Describe the bug**
Cannot upload files through`addValue`/`setValue` command on`type="file"` `input` fields.
It's possible with selenium-standalone, driver services, but not devtools `automationProtocol`.
`elementSendKeys` is successfully executed/ logged with the proper value (the file(s) path) but file upload is not triggered.

**To Reproduce**
Execute`setValue`/`addValue`to file input element.
Example found here: https://github.com/nextlevelbeard/wdio-repro-devtools-input

**Expected behavior**
Should trigger element's onChange event and upload files.

### PR DESCRIPTION
**Pull request by nextlevelbeard**
## Proposed changes

Enables files uploads though input elements of type `file` by changing their value with `addValue`/`setValue` commands. Fixes #5090 , thanks to @takeya0x86

Usage (same as `webdriver` protocol)
```js
input.setValue("/Users/user/files/file.txt") // Single
input.setValue("/Users/user/files/file.txt\n/Users/user/files/file2.txt") //Multiple
// also for addValue
```

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/devtools/src/commands/elementSendKeys.js [hunk 1]
```diff
@@ -1,4 +1,5 @@
 import { getStaleElementError } from '../utils'
+import path from "path"
```
Comment (christian-bromann) [inline packages/devtools/src/commands/elementSendKeys.js:2]: this is failing eslint tests
```suggestion
import path from 'path'
```

File: e2e/element.test.js [hunk 2]
```diff
@@ -105,6 +105,12 @@ describe('elements', () => {
         expect(await browser.getElementProperty(textarea[ELEMENT_KEY], 'value')).toBe('foobar')
     })
 
+    it.only('elementSendKeys for file-type input', async () => {
```
Comment (christian-bromann) [inline e2e/element.test.js:108]:
```suggestion
    it('elementSendKeys for file-type input', async () => {
```

File: e2e/element.test.js [hunk 3]
```diff
@@ -105,6 +105,12 @@ describe('elements', () => {
...
+        const fileInput = await browser.findElement('css selector', '#upload-test')
+        await browser.elementSendKeys(fileInput[ELEMENT_KEY], 'README.MD')
```
Comment (christian-bromann) [inline e2e/element.test.js:110]:
```suggestion
        await browser.elementSendKeys(fileInput[ELEMENT_KEY], 'README.md')
```
