### PR TITLE
wdio-logger: fix setting log level for subloggers and docs

### LINKED ISSUE #3867: When loglevel for specific loggers are set to silent, info and debug logs appear
**Environment:**
 - **WebdriverIO version:** @wdio/cli@5.7.14
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** v10.15.2
 - **NPM version:** 6.4.1
 - **Browser name and version:** Chrome Version 73.0.3683.86 
 - **Platform name and version:** OSX 10.14.4 
 - **Additional wdio packages used (if applicable):** 
```
├─┬ @wdio/cli@5.7.14
│ ├─┬ @wdio/config@5.7.13
│ │ ├── @wdio/logger@5.7.8 deduped
│ ├─┬ @wdio/logger@5.7.8
│ ├─┬ @wdio/utils@5.7.8
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/config@5.7.13 deduped
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/repl@5.7.13 deduped
│ │   ├── @wdio/config@5.7.13 deduped
│ │   ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/dot-reporter@5.7.8
│ ├── @wdio/reporter@5.7.8 deduped
├─┬ @wdio/local-runner@5.7.14
│ ├── @wdio/logger@5.7.8 deduped
│ ├─┬ @wdio/repl@5.7.13
│ │ └── @wdio/config@5.7.13 deduped
│ ├─┬ @wdio/runner@5.7.14
│ │ ├── @wdio/config@5.7.13 deduped
│ │ ├── @wdio/logger@5.7.8 deduped
│ │ ├── @wdio/utils@5.7.8 deduped
├─┬ @wdio/mocha-framework@5.7.14
│ ├── @wdio/config@5.7.13 deduped
│ ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/reporter@5.7.8
├─┬ @wdio/sauce-service@5.7.8
│ ├── @wdio/logger@5.7.8 deduped
├─┬ @wdio/selenium-standalone-service@5.7.8
├─┬ @wdio/spec-reporter@5.7.13
│ ├── @wdio/reporter@5.7.8 deduped
├─┬ @wdio/sync@5.7.13
│ ├── @wdio/config@5.7.13 deduped
│ ├── @wdio/logger@5.7.8 deduped
├── eslint-plugin-wdio@5.7.8
```

**Config of WebdriverIO**
```
logLevel: 'silent',
logLevels: {
        webdriver: 'silent',
        webdriverio: 'silent',
        'wdio-local-runner': 'silent',
        'wdio-cli': 'silent',
        'wdio-sauce-service': 'silent',
        'wdio-utils': 'silent'
    }
``` 

**Describe the bug**
loglevels are set to silent but info and debug logs still appear on the console.
This is the case with `loglevel` set to silent or not set at all.

**To Reproduce**
With the above loglevels set run a test.

**Expected behavior**
No info or debug logs should appear on the console when loglevel is specific loggers are set to silent.

**Log**
```
> wdio example/wdio.conf.js
2019-04-18T18:54:01.530Z DEBUG @wdio/utils:initialiseServices: initialise wdio service "sauce"
2019-04-18T18:54:01.606Z INFO @wdio/cli:Launcher: Run onPrepare hook
2019-04-18T18:54:01.609Z INFO @wdio/local-runner: Start worker 0-0 with arg: example/wdio.conf.js

Test Suites:	 2 passed, 2 total (100% completed)
Time:		 🕒  27.42s
```

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

fix setting log level for subloggers and update docs

partially fixes #3867 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

this PR doesn't affect interface.js

### CODE REVIEW

File: packages/wdio-logger/src/node.js [hunk 1]
```diff
@@ -128,12 +128,16 @@ export default function getLogger (name) {
...
 getLogger.setLogLevelsConfig = (logLevels = {}) => {
     logLevelsConfig = {}
+
     Object.keys(logLevels).forEach(loggerName => {
         const logLevelName = getLogLevelName(loggerName)
-
         logLevelsConfig[logLevelName] = logLevels[loggerName]
+    })
+
+    Object.keys(loggers).forEach(loggerName => {
```
Comment (CrispusDH) [inline packages/wdio-logger/src/node.js]: it might be clearer to name it `logger` instead of `loggerName`

Comment (mgrybyk) [reply packages/wdio-logger/src/node.js]: will do within next PR
