### PR TITLE
fix(bidi-dialog): only accept dialogs in active browsing context

### LINKED ISSUE #14295: [🐛 Bug]: Errors interacting with native browser dialogs (Bidi protocol)
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.12.0

### Node.js Version

20.17.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: "chrome",
    "goog:chromeOptions": {
            args: [
            "--no-sandbox",
            "--start-maximized",
            "--window-size=1920,1080",
            "--disable-dev-shm-usage",
            //"--headless=new",
            "--lang=en-GB"
        ]
    },
    // "wdio:enforceWebDriverClassic": true,
}
```

### What happened?

I am testing an application that uses native browser dialogs to confirm some user actions (like deletes, ...). With Bidi protocol, I face 2 issues that do not happen with WebdriverClassic.

1. Sometimes, the dialog does not open or opens and closes automatically and almost immediately. This causes the error: "no such alert: WebDriverError: no such alert"
2. When the first error does not happen, and there is an interaction with the dialog, then there is the  following error on the next action after the dialog interaction: "no such frame - Context 9467FF542C3FAB062A8D6E7FF8570DD9 not found". When this error happens, the test breaks and the browser remains open until I manually close it.

### What is your expected behavior?

To have a similar behavior as we have running the tests with WebdriverClassic.

### How to reproduce the bug.

For the first error, here is a reproducible example:
[browser_native_dialogs.zip](https://github.com/user-attachments/files/19289893/browser_native_dialogs.zip)

And the logs of the error happening: 
[log_1.txt](https://github.com/user-attachments/files/19290056/log_1.txt)

For the second example, I cannot provide a reproducible example (maybe after you first the first one, you will face this one), just the logs:

[log_2.txt](https://github.com/user-attachments/files/19290432/log_2.txt)

### Relevant log output

```typescript
Provided above.
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by Rondleysg**
## Proposed changes

This PR adds a context check in the `accept() `handler so that we only call `dialog.accept() `when the dialog actually belongs to the current browsing context. It uses the `ContextManager.getCurrentContext()` helper and bails out early if `this.#context !== context`, preventing “no such frame” errors when multiple contexts fire native‐dialog events.

## Related issue
Closes #14295

## Types of changes

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

File: packages/webdriverio/src/session/dialog.ts [hunk 1]
```diff
@@ -111,6 +112,11 @@ export class Dialog {
      * @returns {Promise<void>}
      */
     async accept(userText?: string) {
+        const contextManager = getContextManager(this.#browser)
+        const context = await contextManager.getCurrentContext()
+
+        if (this.#context !== context) {return}
```
Comment (christian-bromann) [inline packages/webdriverio/src/session/dialog.ts:118]:
```suggestion
        if (this.#context !== context) {
            return
        }
```

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Can we add a unit test for this?

**Comment by erwinheitzman** [comment]
Quick question, shouldn't we add this check to all public methods, like close() etc as well?

**Comment by erwinheitzman** [comment]
Great change, thanks for picking this up 👍

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by Rondleysg** [comment]
> Quick question, shouldn't we add this check to all public methods, like close() etc as well?

Yes, sorry, I should have added dismiss() too.
I'll do it in a new PR
