### PR TITLE
wdio-allure-reporter: add tags cucumber support for scenario

### LINKED ISSUE #4815: @issue, @severity  and @tmsLink in cucumber tags are not taken into account by @wdio/allure-reporter
*Environment (please complete the following information):**
 - **WebdriverIO version:** 5.16.9
 - **Mode:** WDIO
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.6.0
 - **NPM version:** 6.9.0
 - **Browser name and version:** Any
 - **Platform name and version:**  Windows 10
 - **Additional wdio packages used (if applicable):** "@wdio/cli": "^5.16.9",
    "@wdio/cucumber-framework": "^5.16.9",
    "@wdio/dot-reporter": "^5.16.5",
    "@wdio/local-runner": "^5.16.9",
    "@wdio/mocha-framework": "^5.16.5",
    "@wdio/selenium-standalone-service": "^5.16.5",
    "@wdio/spec-reporter": "^5.16.5",
    "@wdio/sync": "^5.16.9",
    "@wdio/allure-reporter": "^5.16.0",
    "@wdio/sync": "^5.16.9",

**Describe the bug**
For allure report, to set severity and to pass issues to report, I added @severity=blocker, @issue=<ISSUE-NUMBER> and @tmsLink=<TEST-CASE-ID> on top of Scenario on Feature in my .feature file. But these tags do not seem to be taken into account by allure-report plugin.  
The labels 'severity' and 'isssue' are not present in testsuite.xml generated

Severity in allure + cucumber : https://docs.qameta.io/allure/#_severity_4
Issue/TmsLink in allure + cucumber : https://docs.qameta.io/allure/#_links_4

**To Reproduce**
Feature file:
```
Feature: Try to set severity and to pass issue
  @severity=critical
  @issue=IN-4515
  @tmsLink=INQA-45
  Scenario: Try to set severity and to pass issue
    Given Example
```

Given step:
```
Given('Example',
  () => {
    browser.url('https://shop.polymer-project.org/detail/mens_outerwear/Anvil+L+S+Crew+Neck+-+Grey');
    const app = browser.$('shop-app');
    const home = app.shadow$('shop-detail');
    const button = home.shadow$('button');
    button.waitForDisplayed(10000);
    button.click();
  });
```

**Expected behavior**
Should return true as element clearly clickable and webdriver can click on it

**wdio.config file:**
```
 framework: 'cucumber',

  reporters: ['spec',
    ['allure', {
      outputDir: 'report/allure-results',
      disableWebdriverStepsReporting: false,
      disableWebdriverScreenshotsReporting: false,
      useCucumberStepReporter: true,
    }]],
  cucumberOpts: {
    // <boolean> show full backtrace for errors
    backtrace: false,
    // <string[]> module used for processing required features
    requireModule: ['@babel/register'],
    // <boolean< Treat ambiguous definitions as errors
    failAmbiguousDefinitions: true,
    // <boolean> invoke formatters without executing steps
    // dryRun: false,
    // <boolean> abort the run on first failure
    failFast: false,
    // <boolean> Enable this config to treat undefined definitions as
    // warnings
    ignoreUndefinedDefinitions: false,
    // <string[]> ("extension:module") require files with the given
    // EXTENSION after requiring MODULE (repeatable)
    name: [],
    // <boolean> hide step definition snippets for pending steps
    snippets: true,
    // <boolean> hide source uris
    source: true,
    // <string[]> (name) specify the profile to use
    profile: [],
    // <string[]> (file/dir) require files before executing features
    require: [
      './src/steps/given.js',
      './src/steps/then.js',
      './src/steps/when.js',
      './src/steps/after.js',
      // Or search a (sub)folder for JS files with a wildcard
      // works since version 1.1 of the wdio-cucumber-framework
      // './src/**/*.js',
    ],
    // <string> specify a custom snippet syntax
    snippetSyntax: undefined,
    // <boolean> fail if there are any undefined or pending steps
    strict: true,
    // <string> (expression) only execute the features or scenarios with
    // tags matching the expression, see
    // https://docs.cucumber.io/tag-expressions/
    tagExpression: 'not @Pending',
    // <boolean> add cucumber tags to feature or scenario name
    tagsInTitle: true,
    // <number> timeout for step definitions
    timeout: 99999999,
  },
```

**Log**
Content of testsuite xml file
```
<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1574764826127' stop='1574764826817'>
    <name>Try to set severity and to pass issue</name>
    <title>Try to set severity and to pass issue</title>
    <test-cases>
        <test-case start='1574764826176' status='passed' stop='1574764826817'>
            <name>@severity=critical, @issue=IN-4515: Try to set severity and to pass issue</name>
            <title>@severity=critical, @issue=IN-4515: Try to set severity and to pass issue</title>
            <labels>
                <label name='language' value='javascript'/>
                <label name='framework' value='wdio'/>
                <label name='thread' value='0-0'/>
            </labels>
            <parameters>
                <parameter kind='argument' name='browser' value='MicrosoftEdge'/>
            </parameters>
            <steps>
                <step start='1574764826179' status='passed' stop='1574764826815'>
                    <name>Given Example</name>
                    <title>Given Example</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments/>
        </test-case>
    </test-cases>
</ns2:test-suite>
```

**Missing :**
```
<label name='severity' value='critical'/>
<label name='issue' value='IN-4515'/>
<label name='testId' value='INQA-45'/>
```

### PR DESCRIPTION
**Pull request by lacell75**
## Proposed changes

Fixed #4815 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added necessary documentation (if appropriate)
- [X] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by lacell75** [comment]
Yes I can. I will add tests today or tomorrow.

**Comment by lacell75** [comment]
tests added

File: packages/wdio-allure-reporter/src/index.js [hunk 1]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
         currentTest.addLabel('thread', cid)
     }
 
+    getLabels(test){
+        var tags = test.tags
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: I think would be better to use `let` or `const` instead of `var`

File: packages/wdio-allure-reporter/src/index.js [hunk 2]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
...
+        var labels = []
+        if (tags != null && tags != undefined){
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: `tags != null && tags != undefined` could be replaced with `!!tags`

File: packages/wdio-allure-reporter/src/index.js [hunk 3]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
...
+            tags.forEach(function (tag) {
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: I would prefer arrow function here `tags.forEach((tag) => {...`. As I see in this file amount of arrow functions more than function

File: packages/wdio-allure-reporter/src/index.js [hunk 4]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
...
+                var label = tag.name.replace(/[@]/, '').split('=')
+                if(label.length == 2){
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: It's more solid to use `===` instead of `==`

Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: Do you think that `length` could be more or less than `2`?

File: packages/wdio-allure-reporter/src/index.js [hunk 5]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
...
+                    labels.push({ name: label[0], value: label[1] })
+                }
+            })
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: Could you explain why did you remove line with `console.log`?

File: packages/wdio-allure-reporter/src/index.js [hunk 6]
```diff
@@ -91,7 +91,11 @@ class AllureReporter extends WDIOReporter {
     }
 
     onTestStart(test) {
+        const currentTest = this.allure.getCurrentTest()
         if (this.options.useCucumberStepReporter) {
+            this.getLabels(test).forEach(function (label) {
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: here we could use destructuring assignment:
```
this.getLabels(test).forEach(({name, value}) => {
  currentTest.addLabel(name, value)
 })
```

File: packages/wdio-allure-reporter/src/index.js [hunk 7]
```diff
@@ -120,6 +124,20 @@ class AllureReporter extends WDIOReporter {
         currentTest.addLabel('thread', cid)
     }
 
+    getLabels(test){
```
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: here we could use destructuring assignment as well `getLabels({tags}){`

File: packages/wdio-allure-reporter/src/index.js (hunk 4 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Yes, length can be less than 2 for all other tags (other than "Allure" tags)

File: packages/wdio-allure-reporter/src/index.js (hunk 5 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Many irrelevant logs would have been displayed if tags other than "Allure" tags are present in feature file

**Comment by lacell75** [comment]
In the latest commit, I took into account @CrispusDH's remark and moved the code to the "suite" level instead of "test" level.  I realized that for cucumber , suite = scenario and test = step. (The labels were added at each step instead of each test)

File: packages/wdio-allure-reporter/src/index.js (hunk 4 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Done

File: packages/wdio-allure-reporter/src/index.js (hunk 3 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Done

File: packages/wdio-allure-reporter/src/index.js (hunk 2 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Done

File: packages/wdio-allure-reporter/src/index.js (hunk 1 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: Done

File: packages/wdio-allure-reporter/src/index.js (hunk 7 above)
Comment (CrispusDH) [inline packages/wdio-allure-reporter/src/index.js]: 1) You could  use destructuring assignment as well:
```
getLabels({tags}){
  const tags = test.tags   <<<<----- can remove
```
2) If you prefer to put object rename it from `test` to `suite`

File: packages/wdio-reporter/src/stats/test.js [hunk 8]
```diff
@@ -11,6 +11,7 @@ export default class TestStats extends RunnableStats {
         this.cid = test.cid
         this.title = test.title
         this.fullTitle = test.fullTitle
+        this.tags = test.tags
```
Comment (CrispusDH) [inline packages/wdio-reporter/src/stats/test.js]: should be here suite.tags?

Comment (lacell75) [reply packages/wdio-reporter/src/stats/test.js]: suite.tags already exists. I will remove it in test. No longer needed now.

File: packages/wdio-allure-reporter/src/index.js (hunk 7 above)
Comment (lacell75) [reply packages/wdio-allure-reporter/src/index.js]: This is a mistake. i'm fixing that.
