### PR TITLE
Remove app path from sanitize.caps() so it fixes #1104

### LINKED ISSUE #1104: Logger does not sanitize app path
When providing the [`app` desired capability](https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-ApplicationPath), the logger fails because it tries to open a log file containing the app path:
```
Error: ENOENT: no such file or directory, open '/.../log/google.android./my/super/long/path/to/app.apk.2016-02-15T10:30:06.742.log'
```
I think we have to options here: do not include the app name in file name or escape the path properly.

### PR DESCRIPTION
**Pull request by agauthiez**
Quickfix for #1104 as the app name is polluting the log file name. Unless you run parallel tests on different applications (Is that common?), it will not lead to file name conflicts.

### CODE REVIEW

**Comment by christian-bromann** [comment]
@georgecrawford what do you think? It's kinda related to #991

**Comment by agauthiez** [comment]
If we want to keep the app name, we can either only keep the file name with `caps.app.replace(/^.*[\\\/]/, '')` or replace all slashes with something. I would prefer the first solution, the second one can lead to crazy long log file names.

**Comment by georgecrawford** [comment]
I think we should keep the app name, but we should certainly escape it. I'd do `caps.app.replace(/^.*\/([^\/]+)\/?$/, '$1')` to get the last segment of the path (or the whole value if it doesn't look like a path). Does that work?

**Comment by agauthiez** [comment]
Yes, it works. I did the change.

File: lib/helpers/sanitize.js [hunk 1]
```diff
@@ -28,9 +29,9 @@ let caps = function (caps) {
      * mobile caps
      */
     if (caps.deviceName) {
-        result = [sanitizeString(caps.deviceName), sanitizeString(caps.platformName), sanitizeString(caps.platformVersion), sanitizeString(caps.app)]
+        result = [sanitizeString(caps.deviceName), sanitizeString(caps.platformName), sanitizeString(caps.platformVersion)]
```
Comment (georgecrawford) [inline lib/helpers/sanitize.js]: Can you now reinstate `caps.app` here?

**Comment by agauthiez** [comment]
My bad. Done.

**Comment by christian-bromann** [comment]
LGTM! Thanks @agauthiez
