### PR TITLE
Assign w3c identifier to element scope after element re-found

### LINKED ISSUE #5865: Double-clicking doesn't work on delayed elements
**Environment:**
 - **WebdriverIO version:** 6.5.0
 - **Mode:** Both standalone and wdio test runner.
 - **If WDIO Testrunner, running sync/async:** I have only tried this in async mode.
 - **Node.js version:** 12.18.3
 - **NPM version:** 6.14.6
 - **Browser name and version:** Chrome 85
 - **Platform name and version:** macOS 10.15.6

**Config of WebdriverIO**
See steps to reproduce further down.

**Describe the bug**
If I get an element reference to an element that doesn't exist yet, then do `await element.waitForExist()`, and then `await element.doubleClick()`, the test fails with an error like this:

```
invalid argument
from invalid argument: 'element' is missing
  (Session info: chrome=85.0.4183.102)
```

**To Reproduce**
A reproducible test case can be found here: https://codesandbox.io/s/wdio-double-click-issue-qm3sg?file=/test/specs/delayed-elements.js

I couldn't figure out a way to have it run in there, but you can go File -> Export to ZIP and then:
1. Unzip the file somewhere
2. Navigate to the folder
3. `npm install`
4. `npm test`

And you will see one test passing (click) and one test failing (double click).

Copy of the test code to make it clearer right here:

```js
await browser.url("http://the-internet.herokuapp.com/dynamic_loading/2");
const startButton = await browser.$("#start button");
const finishTitle = await browser.$("#finish h4");
await startButton.click();
await finishTitle.waitForExist();
expect(await finishTitle.getText()).toBe("Hello World!");
await finishTitle.doubleClick(); // This causes the error
```

**Expected behavior**
Since both `await element.click()` and `await element.getText()` work, I would expect `await element.doubleClick()` to work just fine too.

**Additional context**
It seems like the element object still has an error object attached to it, even after the element starts existing (after running `await element.waitForExist()`). I wonder if this error state needs to be reset once the element becomes available?

Thanks! 🙏

### PR DESCRIPTION
**Pull request by L0tso**
## Proposed changes
Fix #5865 
[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriverio/src/middlewares.js [hunk 1]
```diff
@@ -13,6 +14,9 @@ export const elementErrorHandler = (fn) => (commandName, commandFn) => {
         return fn(commandName, async function elementErrorHandlerCallbackFn () {
             const element = await implicitWait(this, commandName)
             this.elementId = element.elementId
+            if(this.isW3C) {
+                this[ELEMENT_KEY] = element.elementId
+            }
```
Comment (christian-bromann) [inline packages/webdriverio/src/middlewares.js:19]: There is no need to avoid setting the key for non-W3C browser given that they aren't many people running those type of tests anymore.

```suggestion
            this[ELEMENT_KEY] = element.elementId
```

**Review by christian-bromann — CHANGES_REQUESTED** [review]
One comment

File: packages/webdriverio/src/middlewares.js (hunk 1 above)
Comment (L0tso) [reply packages/webdriverio/src/middlewares.js]: fixed

**Review by christian-bromann — APPROVED** [review]
Thank you 👍

File: packages/webdriverio/src/middlewares.js (hunk 1 above)
Comment (L0tso) [reply packages/webdriverio/src/middlewares.js]: @christian-bromann Oops, looks like this fix breaks a unit test. Should I revert it?

**Comment by christian-bromann** [comment]
@L0tso it seems like a test is failing and it might be related to the change.

**Comment by L0tso** [comment]
@christian-bromann Yeap
That's because no-w3c elements have ELEMENT_KEY, i can revert https://github.com/webdriverio/webdriverio/pull/5872/commits/a66d3207b3f2e94041a5067087c78b977a8c4287, it will fix it

**Comment by christian-bromann** [comment]
@L0tso I suggest to remove these assertions from [the test](https://github.com/webdriverio/webdriverio/blob/master/packages/webdriverio/tests/commands/element/$.test.js#L44-L46):
```diff
-        expect(elem[ELEMENT_KEY]).toBe(undefined)
         expect(elem.ELEMENT).toBe('some-elem-123')
-        expect(subElem[ELEMENT_KEY]).toBe(undefined)
```

**Review by christian-bromann — APPROVED** [review]
Awesome, thanks 👍
