### PR TITLE
Fix overflow text is displayed

### LINKED ISSUE #4200: Safari 12.1: isDisplayed() and "text-overflow: ellipsis;" in div
- **WebdriverIO version:** 5.11.5
 - **Mode:** WDIO Testrunner (sync)
 - **Node.js version:** 10.16.0 LTS
 - **NPM version:** 6.9.0
 - **Browser name and version:** Safari 12.1.1
 - **Platform name and version:** MacOS Mojave 10.14.5

win

Simple test:
```
describe('test', () => {
  it('test', () => {
    browser.url('https://support.microsoft.com/en-us')
    $('//div[@class="product-name"]//div[text()="Windows"]').waitForDisplayed()
  })
})
```

> 
> [Safari  macOS #0-0] Running: Safari on macOS
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] test
> [Safari  macOS #0-0]    ✖ test
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] 1 failing (13.4s)
> [Safari  macOS #0-0]
> [Safari  macOS #0-0] 1) test test
> [Safari  macOS #0-0] element ("//div[@class="product-name"]//div[text()="Windows"]") still not displayed after 10000ms

WDIO does not work correctly with visibility where div with "text-overflow" attribute in Safari

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Ignore _TEXT_NODEs_ when checking if element subtree is hidden by overflow.
I assume that it is enough to check _TEXT_NODE_ parent in such cases.

Please correct me if I'm wrong.

fixes #4200

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have tested my changes in desktop _Chrome_ (`w3c: true`) and _Safari_
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

Added brackets to `if` blocks because it is really painful to debug without them.

### CODE REVIEW

File: packages/webdriverio/src/scripts/isElementDisplayed.js [hunk 1]
```diff
@@ -134,24 +146,33 @@ export default function isElementDisplayed(element) {
...
             return false
+        }
 
         // This element's subtree is hidden by overflow if all child subtrees are as well.
         return Array.from(element.childNodes).every((childNode) => {
             // Returns true if the child node is overflowed or otherwise hidden.
             // Base case: not an element, has zero size, scrolled out, or doesn't overflow container.
-            if (!nodeIsElement(childNode))
+            // Visibility of text nodes is controlled by parent
+            if (childNode.nodeType === Node.TEXT_NODE) {
```
Comment (mgrybyk) [inline packages/webdriverio/src/scripts/isElementDisplayed.js]: the only change is here, others are just additions of brackets.
