### PR TITLE
fix: Emit browser custom command `beforeCommand` to fix broken reports

### LINKED ISSUE #14580: [🐛 Bug]: Custom command triggers only Reporter.onAfterCommand without the onBeforeCommand breaking reports
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.15.0

### Node.js Version

18

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
N/A
```

### What happened?

Since we introduced the driver custom command, our reports are broken, and the startStep/EndStep no longer displays correctly. Our steps ended prematurely, and we encountered unusual errors during and after our tests. 

After debugging, I found that it is due to the new driver custom command we introduced, which triggers only the onAfterCommand on the reporter and closes a step not related to that command.

The root cause is [this code line in monad.ts ](https://github.com/dprevost-LMI/webdriverio/blob/b6c4be917a8d7f4e8822a525dd38fc3df842f05a/packages/wdio-utils/src/monad.ts#L210) emitting `result` without prior `command`. Moreover, it should also send a result on error.

See potential fix: https://github.com/webdriverio/webdriverio/pull/14581

### What is your expected behavior?

All emit to `result` should have one prior on `command` and also should be wrap in a try-catch so that on error we garantee a `result` emit

### How to reproduce the bug.

- Have a driver custom command
- User startStep from allure
- call your custom command
- The custom command will end your step before you can call end step

### Relevant log output

```typescript
[0-0] Error in "reporter CustomAllureReporter"
Error: There isn't any active test!
    at GoToAllureReporter._endSuite (/redacted/config/webDriverIO/reporters/allure-reporter/allureReporter.ts:568:13)
    at GoToAllureReporter.onSuiteEnd (/redacted/config/webDriverIO/reporters/allure-reporter/allureReporter.ts:504:10)
    at GoToAllureReporter.<anonymous> (/redacted/node_modules/@wdio/reporter/build/index.cjs:615:12)
    at GoToAllureReporter.emit (node:events:517:28)
    at GoToAllureReporter.emit (node:domain:489:12)
    at file:///redacted/node_modules/@wdio/runner/build/index.js:508:18
    at Array.forEach (<anonymous>)
    at BaseReporter.emit (file:///redacted/node_modules/@wdio/runner/build/index.js:506:21)
    at MochaAdapter.emit (/redacted/node_modules/@wdio/mocha-framework/build/index.js:281:20)
    at Runner.emit (node:events:529:35)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by dprevost-LMI**
## Proposed changes

As described in [this issue](https://github.com/webdriverio/webdriverio/issues/14580), when using browser custom command, it can break reports since we only emit a `result` event, which translates to triggering only a `onAfterCommand`, which stops a step not belonging to that command.

Now, we emit the command so that `onBeforeCommand` gets called correctly, and we also ensure, with the catch, that `onAfterCommand` is always called. We have also reviewed the emitted data to align with the already existing command  emitting when doing a HTTP request/response

Other:
- Fix reporter `attachJSON` to ensure it outputs the proper JSON file type when needed and any compatible JSON in a beautified format
- On afterCommand, stop generating a response file if the result or error is undefined

fixes #14580

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-reporter/src/types.ts [hunk 1]
```diff
@@ -3,31 +3,38 @@ export interface Tag {
...
-export interface AfterCommandArgs extends CommandArgs {
-    result: unknown
-
-    /**
-     * custom commands also send along the command name
-     */
-    name?: string
+export interface CustomCommand extends CommonArgs {
+    name: string
+    args: unknown[]
```
Comment (dprevost-LMI) [inline packages/wdio-reporter/src/types.ts]: @christian-bromann I reused `name` and `args` since the emit of `result` in `monad.ts` was already using them, but if we use them as `command` and `body`, we could simplify the types.

What do you think?

File: packages/wdio-allure-reporter/src/reporter.ts [hunk 2]
```diff
@@ -31,6 +31,7 @@ import type {
 import {
     TYPE as DescriptionType
 } from './types.js'
+import type { BeforeCommand, CustomCommand } from 'node_modules/@wdio/reporter/build/types.js'
```
Comment (christian-bromann) [inline packages/wdio-allure-reporter/src/reporter.ts]: We should export these types if we use them elsewhere
```suggestion
import type { BeforeCommand, CustomCommand } from '@wdio/reporter'
```

File: packages/wdio-browserstack-service/src/Percy/Percy-Handler.ts [hunk 3]
```diff
@@ -82,12 +82,13 @@ class _PercyHandler {
     }
 
     isDOMChangingCommand(args: BeforeCommandArgs): boolean {
+        if ('method'in args && 'endpoint' in args) {
         /*
           Percy screenshots which are to be taken on events such as send keys, element click & screenshot are deferred until
           another DOM changing command is seen such that any DOM processing post the previous command is completed
         */
```
Comment (christian-bromann) [inline packages/wdio-browserstack-service/src/Percy/Percy-Handler.ts]: Let's intend this as well

File: packages/wdio-reporter/src/types.ts (hunk 1 above)
Comment (christian-bromann) [reply packages/wdio-reporter/src/types.ts]: makes sense to me

File: packages/wdio-utils/src/monad.ts [hunk 4]
```diff
@@ -183,6 +183,7 @@ export default function WebDriver (options: object, modifier?: Function, propert
     unit.lift = function (name: string, func: Function, proto: Record<string, any>, origCommand?: Function) {
         (proto || prototype)[name] = function next (...args: unknown[]) {
             log.info('COMMAND', commandCallStructure(name, args))
+            this.emit('command', { name, args })
```
Comment (christian-bromann) [inline packages/wdio-utils/src/monad.ts]: Can we add unit tests for this?

Comment (christian-bromann) [reply packages/wdio-utils/src/monad.ts]: ideally somewhere here `packages/webdriverio/tests/addCommand.test.ts`

File: packages/wdio-allure-reporter/src/reporter.ts (hunk 2 above)
Comment (dprevost-LMI) [reply packages/wdio-allure-reporter/src/reporter.ts]: Damn vscode

File: packages/wdio-utils/src/monad.ts (hunk 4 above)
Comment (dprevost-LMI) [reply packages/wdio-utils/src/monad.ts]: Yes, just want to confirm the implementation first

File: packages/wdio-reporter/src/types.ts (hunk 1 above)
Comment (dprevost-LMI) [reply packages/wdio-reporter/src/types.ts]: Great, I'll prepare a breaking change. At the same time, I doubt a lot of people were relying on the name /arg of custom commands!

File: packages/wdio-allure-reporter/src/reporter.ts (hunk 2 above)
Comment (dprevost-LMI) [reply packages/wdio-allure-reporter/src/reporter.ts]: Done

File: packages/wdio-utils/src/monad.ts [hunk 5]
```diff
@@ -198,6 +199,7 @@ export default function WebDriver (options: object, modifier?: Function, propert
              * always transform result into promise
              */
             Promise.resolve(result).then((res: unknown) => {
```
Comment (dprevost-LMI) [inline packages/wdio-utils/src/monad.ts]: @christian-bromann What is the goal of this promise if it is not returned? My unit test indicates that this is being called after my `expect`, so something seems wrong here; we either do not need this code or should return the promise, perhaps?

If it's legitimate, do you have an example of where and how it's useful?
Thanks!

Comment (dprevost-LMI) [reply packages/wdio-utils/src/monad.ts]: By testing with `packages/webdriverio/tests/addCommand.test.ts`, I think I understand a bit more. 
However, let's wrap up the result and not leave a promise on the side, so I will remove the existing code in favour of running on the `result.then` +`result.catch` so the code runs with the `await`

Note that I still struggle to understand the code below, which I have difficulty making work from the unit tests.
```ts
  const elem = res as { elementId: string, selector?: string }
  let resultLog = res
  if (elem instanceof SCOPE_TYPES.element) {
      resultLog = `WebdriverIO.Element<${elem.elementId || elem.selector}>`
  } else if (res instanceof SCOPE_TYPES.browser) {
      resultLog = 'WebdriverIO.Browser'
  }
```

Comment (dprevost-LMI) [reply packages/wdio-utils/src/monad.ts]: Never mind got it, will look into `packages/webdriverio/tests/middleware.test.ts` and see

File: packages/wdio-reporter/src/types.ts (hunk 1 above)
Comment (dprevost-LMI) [reply packages/wdio-reporter/src/types.ts]: Done

File: packages/wdio-browserstack-service/src/Percy/Percy-Handler.ts (hunk 3 above)
Comment (dprevost-LMI) [reply packages/wdio-browserstack-service/src/Percy/Percy-Handler.ts]: Reverted

File: packages/wdio-utils/src/monad.ts (hunk 4 above)
Comment (dprevost-LMI) [reply packages/wdio-utils/src/monad.ts]: Done

File: packages/wdio-reporter/src/types.ts [hunk 6]
```diff
@@ -22,11 +22,6 @@ export interface BeforeCommandArgs extends CommandArgs {
 
 export interface AfterCommandArgs extends CommandArgs {
     result: unknown
-
-    /**
-     * custom commands also send along the command name
-     */
-    name?: string
```
Comment (dprevost-LMI) [inline packages/wdio-reporter/src/types.ts]: Is it okay to remove it, assuming it was not heavily used, or should we keep it, still emit it, and mark it as deprecated?

File: packages/webdriverio/tests/addCommand.test.ts [hunk 7]
```diff
@@ -356,6 +356,40 @@ describe('addCommand', () => {
             // @ts-ignore uses expect-webdriverio
             expect.assertions(2)
         })
+
+        describe('when browser custom command is a function', () => {
+            test('should return result when running custom command as a function', async () => {
+                const browser = await remote(remoteConfig)
+                console.log('addCommand')
```
Comment (christian-bromann) [inline packages/webdriverio/tests/addCommand.test.ts]:
```suggestion
```

File: packages/webdriverio/tests/addCommand.test.ts [hunk 8]
```diff
@@ -356,6 +356,40 @@ describe('addCommand', () => {
...
+                browser.addCommand(
+                    'press1',
+                    () => {
+                        console.trace('custom command executed')
+                        return 'command result'
+                    }
```
Comment (christian-bromann) [inline packages/webdriverio/tests/addCommand.test.ts]:
```suggestion
                    () => 'command result'
```

File: packages/webdriverio/tests/addCommand.test.ts [hunk 9]
```diff
@@ -356,6 +356,40 @@ describe('addCommand', () => {
...
+                )
+
+                console.log('call command')
```
Comment (christian-bromann) [inline packages/webdriverio/tests/addCommand.test.ts]:
```suggestion
```

File: packages/wdio-reporter/src/types.ts (hunk 6 above)
Comment (christian-bromann) [reply packages/wdio-reporter/src/types.ts]: Let's mark it as deprecated

File: packages/wdio-allure-reporter/src/reporter.ts [hunk 10]
```diff
@@ -499,36 +506,40 @@ export default class AllureReporter extends WDIOReporter {
...
+        const stepName = command ? command : `${method} ${endpoint}`.trim() || 'unknown command'
+        const payload = body || params
 
         this._startStep(stepName as string)
 
-        if (typeof payload === 'object' && !isEmpty(payload as object)) {
+        if (payload && (typeof payload === 'object' || Array.isArray(payload))  && !isEmpty(payload)) {
             this.attachJSON('Request', payload)
         }
+
```
Comment (dprevost-LMI) [inline packages/wdio-allure-reporter/src/reporter.ts]:
```suggestion
```

File: packages/wdio-reporter/src/types.ts (hunk 6 above)
Comment (dprevost-LMI) [reply packages/wdio-reporter/src/types.ts]: Done + kept legacy emit: 3180e1dbb4894d742e82c2deb7d38adc80235747

**Comment by christian-bromann** [comment]
Once I managed to fix the build (see #14592) I can update the branch and merge once tests pass. Sorry for the delay.

**Review by christian-bromann — APPROVED** [review]
Awesome 🎉
