### PR TITLE
fix(webdriver): update the registration logic for  abort listener

### LINKED ISSUE #14257: [🐛 Bug]: Possible EventEmitter memory leak detected
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.11.0

### Node.js Version

v20.18.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
      'browserName': 'electron',
      'wdio:electronServiceOptions': {
        appBinaryPath,
        appArgs: ['foo', 'bar=baz'],
      },
    },
```

### What happened?

When execute test suite which runs `execute` command many times, the following message is displayed multiple times. I don't know if this is a direct cause, but the test results are not stable.

Please check the Relevant log output.
*) `NODE_OPTIONS="--trace-warnings"` is set when run `wdio` command at the command prompt

This issue is related to #14246
https://github.com/webdriverio/webdriverio/blob/9127b92109987dff12d9c8203a96e2c3a76dfcab/packages/webdriver/src/command.ts#L223-L264

### What is your expected behavior?

The log is not displayed.

### How to reproduce the bug.

1. Clone and checkout 
  https://github.com/mato533/webdriverio/tree/inv/14257
    repository: `mato533/webdriverio`
    branch: `inv/14257`

1. build
   ```
   $ pnpm run setup   
   ```

1. Run test
   ```
   $ pnpm test:e2e:testrunner  
   ```

### Relevant log output

```typescript
> wdio run ./wdio.conf.ts

Execution of 1 workers started at 2025-03-10T05:45:52.194Z

[0-0] RUNNING in chrome - file:///test/api.spec.ts
[0-0] (node:49036) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 result listeners added to [EventEmitter]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
[0-0]     at genericNodeError (node:internal/errors:984:15)
[0-0]     at wrappedFn (node:internal/errors:538:14)
[0-0]     at _addListener (node:events:593:17)
[0-0]     at EventEmitter.addListener (node:events:611:10)
[0-0]     at Browser.WebDriver.prototype.<computed> (/work/wdio-electron-service/node_modules/.pnpm/@wdio+utils@9.11.0/node_modules/@wdio/utils/build/index.js:462:29)
[0-0]     at Browser.manageSessionAbortions (file:///work/wdio-electron-service/node_modules/.pnpm/webdriver@9.11.0/node_modules/webdriver/build/node.js:180:8)
[0-0]     at Browser.protocolCommand (file:///work/wdio-electron-service/node_modules/.pnpm/webdriver@9.11.0/node_modules/webdriver/build/node.js:100:72)
[0-0]     at Browser.wrapCommandFn (/work/wdio-electron-service/node_modules/.pnpm/@wdio+utils@9.11.0/node_modules/@wdio/utils/build/index.js:902:32)
[0-0]     at Browser.<anonymous> (/work/wdio-electron-service/node_modules/.pnpm/@wdio+utils@9.11.0/node_modules/@wdio/utils/build/index.js:1017:20)
[0-0]     at Browser.execute (/work/wdio-electron-service/node_modules/.pnpm/webdriverio@9.11.0_puppeteer-core@22.15.0/node_modules/webdriverio/build/node.js:3576:15)
[0-0]     at Browser.wrapCommandFn (/work/wdio-electron-service/node_modules/.pnpm/@wdio+utils@9.11.0/node_modules/@wdio/utils/build/index.js:902:32)
[0-0]     at Browser.<anonymous> (/work/wdio-electron-service/node_modules/.pnpm/@wdio+utils@9.11.0/node_modules/@wdio/utils/build/index.js:1017:20)
[0-0]     at ElectronWorkerService.execute (/work/wdio-electron-service/packages/src/commands/execute.ts:26:37)
[0-0]     at Object.execute (/work/wdio-electron-service/packages/src/service.ts:68:77)
[0-0]     at Function.mock.update (/work/wdio-electron-service/packages/src/mock.ts:290:2)
[0-0]     at <anonymous> (/work/wdio-electron-service/packages/src/service.ts:196:73)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by mato533**
## Proposed changes
This PR suggests the change to register abort listener at only once even if the request called multiple times.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [X] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [X] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

closes #14257

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by mato533** [comment]
The Failure of Unit tests seems to be coming from the changes of #14259.

**Comment by nextlevelbeard** [comment]
@mato533 When using the this `webdriver` package

> npm i https://pkg.pr.new/webdriverio/webdriverio/webdriver@14278  --save-dev --save-exact

I'm getting this error using the `browser.url` command
>```
> Error: Navigation to 'http://localhost:1234/' timed out as no request payload was received
>     at <anonymous> (/Users/user/repos/repo/e2e/node_modules/webdriverio/build/node.js:5638:15)
>     at Browser.wrapCommandFn (/Users/user/repos/repo/e2e/node_modules/@wdio/utils/build/index.js:902:23)
>     at Browser.url (/Users/user/repos/repo/e2e/node_modules/webdriverio/build/node.js:5591:21)
>```

**Comment by mato533** [comment]
@nextlevelbeard 
Thank you for your feedback.

But according to the results of test which toword reverted my changes, the similar error message (timed out  ~) you commented is occured.

So, It seems to be this error is coming from out of this PR.
As a proposed response to Issue (#14257), I would like to keep the content of this PR, what do you think?

### CI result of reverted code
https://github.com/webdriverio/webdriverio/actions/runs/13888757117

#### Test log
```
2025-03-17T00:11:25.396Z INFO webdriver: BIDI RESULT {"id":1,"result":{"navigation":"33ec35ef-b288-4767-8509-4990413d4688","url":"https://www.google.com/"},"type":"success"}
WebdriverIO CJS Test Failed! Error: Navigation to 'https://www.google.com/ncr' timed out as no request payload was received
    at file:///home/runner/work/webdriverio/webdriverio/packages/webdriverio/build/node.js:5676:15
    at async Browser.wrapCommandFn (file:///home/runner/work/webdriverio/webdriverio/packages/wdio-utils/build/index.js:902:23)
    at async Browser.url (file:///home/runner/work/webdriverio/webdriverio/packages/webdriverio/build/node.js:5629:21)
    at async Browser.wrapCommandFn (file:///home/runner/work/webdriverio/webdriverio/packages/wdio-utils/build/index.js:902:23)
    at async /home/runner/work/webdriverio/webdriverio/tests/interop/webdriverio.e2e.js:18:5
```

#### Note
For the record, keep the revert commit that nullifies the change and the commit that revert of revert

File: packages/webdriver/src/command.ts [hunk 1]
```diff
@@ -252,7 +252,10 @@ function manageSessionAbortions (this: BaseClient): {
             sessionAbortListeners.set(this.sessionId, null)
         }
     }
-    this.on('result', abortOnSessionEnd)
+    if (!this.isAbortListenerRegistered) {
+        this.on('result', abortOnSessionEnd)
+        this.isAbortListenerRegistered = true
```
Comment (christian-bromann) [inline packages/webdriver/src/command.ts:257]: Since this is an internal flag, let's not attach it to the `WebdriverIO.Browser` instance and instead maybe derive it from `sessionAbortListeners`?

Comment (mato533) [reply packages/webdriver/src/command.ts]: @christian-bromann 
Thank you for the feedback.

I reconsidered the comment and realised that it is possible to determine whether a handler should be registered or not by whether the registration process to sessionAbortListeners takes place or not.

We have pushed the new logic and completely hide the flag from Browser. Thanks for giving us the opportunity to notice.

But Component test is unstable... I'm checking what is wrong...

**Review by christian-bromann — APPROVED** [review]
LGTM 👍 

Thanks a ton!
