### PR TITLE
(webdriverio): fix isDisplayed for Firefox, updated examples in docs

### LINKED ISSUE #11563: [🐛 Bug]: 'isDisplayed' API works incorrectly in chrome for elements with zero opacity or not in viewport
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.20.4

### Node.js Version

18.17.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        maxInstances: 5,
        browserName: 'chrome',
        acceptInsecureCerts: true,
    }],
```

### What happened?

The Webdriverio 'isDisplayed' API works not as its [documentation](https://webdriver.io/docs/api/element/isDisplayed/)
It returns false which indicates the element is invisible if the element has zero opacity or not in viewport.

elem = await $('#notInViewport');
isDisplayed = await elem.isDisplayed();
console.log(isDisplayed); // expect true but return false

elem = await $('#zeroOpacity');
isDisplayed = await elem.isDisplayed();
console.log(isDisplayed); // expect true but return false

I found a similar closed issue here https://github.com/webdriverio/webdriverio/issues/7708
### What is your expected behavior?

I expect the Webdriverio 'isDisplayed' API works correctly as its [documentation](https://webdriver.io/docs/api/element/isDisplayed/)

### How to reproduce the bug.

You can reproduce the issue by using this repo: https://github.com/webdriverio/example-recipes
You can set up the example mentioned in [documentation](https://webdriver.io/docs/api/element/isDisplayed/)
by reusing files in this folder https://github.com/webdriverio/example-recipes/tree/main/waitForDisplayed

**index.html**
```
<div id="notDisplayed" style="display: none"></div>
<div id="notVisible" style="visibility: hidden"></div>
<div id="notInViewport" style="position:absolute; left: 9999999"></div>
<div id="zeroOpacity" style="opacity: 0"></div>
```

**waitForDisplayedExample.js**
```
describe('waitForDisplayed Example', () => {
    beforeEach(async () => {
        await browser.url('/index.html')
    })

    it('should detect if an element is displayed', async () => {
        let elem = await $('#notDisplayed');
        let isDisplayed = await elem.isDisplayed();
        console.log('notDisplayed', isDisplayed); // outputs: false
    
        elem = await $('#notVisible');
        isDisplayed = await elem.isDisplayed();
        console.log('notVisible', isDisplayed); // outputs: false
    
        elem = await $('#notExisting');
        isDisplayed = await elem.isDisplayed();
        console.log('notExisting', isDisplayed); // outputs: false
    
        elem = await $('#notInViewport');
        isDisplayed = await elem.isDisplayed();
        //expect(isDisplayed).toEqual(true)
        console.log('notInViewport', isDisplayed); // outputs: true
    
        elem = await $('#zeroOpacity');
        isDisplayed = await elem.isDisplayed();
        //expect(isDisplayed).toEqual(true)
        console.log('zeroOpacity', isDisplayed); // outputs: true
    });
})
```
Then run command: `npm run waitForDisplayed`

### Relevant log output

```typescript
elem = await $('#notInViewport');
    isDisplayed = await elem.isDisplayed();
    console.log(isDisplayed); // outputs: false

    elem = await $('#zeroOpacity');
    isDisplayed = await elem.isDisplayed();
    console.log(isDisplayed); // outputs: false
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by erwinheitzman**
## Proposed changes

Fixes #11563

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

File: packages/webdriverio/src/commands/element/isDisplayed.ts [hunk 1]
```diff
@@ -59,6 +70,8 @@ export async function isDisplayed (this: WebdriverIO.Element) {
         return false
     }
 
+    const isListedBrowser = noW3CEndpoint.includes((browser.capabilities as WebdriverIO.Capabilities).browserName?.toLowerCase()!) ||
```
Comment (christian-bromann) [inline packages/webdriverio/src/commands/element/isDisplayed.ts:73]: Let's just use the atom for all cases and remove the complexity it.

**Comment by christian-bromann** [comment]
The tests seem failing because we only mock the `isElementDisplayed` endpoint while the browser actually calls `execute` which the atom script. We need to adjust this here: https://github.com/webdriverio/webdriverio/blob/28f02d71b463ce2333f8130cad22a8676a663845/packages/wdio-webdriver-mock-service/src/index.ts#L115-L123

File: packages/webdriverio/src/commands/element/isDisplayed.ts (hunk 1 above)
Comment (erwinheitzman) [reply packages/webdriverio/src/commands/element/isDisplayed.ts:73]: Doing this, does mean that we no longer support the old Microsoft Edge (non Chromium), that is fine for me but I do want to make sure we are aware.

Comment (christian-bromann) [reply packages/webdriverio/src/commands/element/isDisplayed.ts:73]: What do you mean by "not supporting it"? It would just use the atom to determine the visibility which hopefully results in the same. That said though, I don't think anyone uses this browser for testing either.

**Comment by erwinheitzman** [comment]
I'm currently at a dinner, will fix the remaining tests once I am back 👍

**Review by christian-bromann — APPROVED** [review]
LGTM 👍
