### PR TITLE
Propagate connection details from capabilities

### LINKED ISSUE #6557: WebdriverIO in watch-mode "forgets" hostname and protocol if not explicitly specified
**Environment (please complete the following information):**
 - **WebdriverIO version:** [7.1.0]
 - **Mode:** [WDIO Testrunner]
 - **If WDIO Testrunner, running sync/async:** [async]

**Config of WebdriverIO**
```
export const config: WebdriverIO.Config = {
    runner: "local",
    specs: ["__specs__/*.spec.js"],
    specFileRetries: 0,
    capabilities: [{browserName: "chrome", "goog:chromeOptions": {args: chrome_args}}],
    port: 9515,
    path: "/",

    services: [
        ["chromedriver", {logFileName: `${test_dir}/chromedriver.log`, port: 9515}],
    ],
}
```

Note: The bug happens with the default service as well.

**Describe the bug**
WebdriverIO works fine until I try to use the watch mode. Then the first run is still ok but the consecutive ones fail with:
```
UnsupportedProtocolError: Unsupported protocol "undefined:"
    at normalizeArguments (/Users/pero/src/pero/cling-main/node_modules/got/dist/source/core/index.js:420:23)
    at normalizeArguments (/Users/pero/src/pero/cling-main/node_modules/got/dist/source/as-promise/core.js:34:31)
    at Object.got [as default] (/Users/pero/src/pero/cling-main/node_modules/got/dist/source/create.js:88:39)
    at WebDriverRequest._request (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/request.js:126:41)
    at WebDriverRequest.makeRequest (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/request.js:68:21)
    at Browser.protocolCommand (/Users/pero/src/pero/cling-main/node_modules/webdriver/build/command.js:74:24)
    at Browser.wrapCommandFn (/Users/pero/src/pero/cling-main/node_modules/@wdio/utils/build/shim.js:79:38)
```

It works once I explicitly configure hostname and protocol:
```
config = {
...
    hostname: "localhost",
    protocol: "http",
...
}

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

When services like `@wdio/selenium-standalone-server` are used they modify connection details through setting them within the capabilities. When running in watch mode these details were not propagated correctly.

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

fixes #6557

### CODE REVIEW

File: packages/wdio-runner/src/utils.ts [hunk 1]
```diff
@@ -64,7 +65,15 @@ export async function initialiseInstance (
     if (config.sessionId) {
         log.debug(`attach to session with id ${config.sessionId}`)
         config.capabilities = sanitizeCaps(capabilities)
-        return attach({ ...config } as Required<ConfigWithSessionId>)
+
+        /**
+         * propagate connection details defined by services or user in capabilities
+         */
+        const { protocol, hostname, port, path } = pick(
```
Comment (erwinheitzman) [inline packages/wdio-runner/src/utils.ts:72]: lodash.pick seems to do the same as destructuring, can you please verify?

**Review by erwinheitzman — COMMENTED** [review]
Left a small question regarding the use of lodash.pick

File: packages/wdio-runner/src/utils.ts (hunk 1 above)
Comment (christian-bromann) [reply packages/wdio-runner/src/utils.ts:72]: this is using `lodash.pick`, see top of file:

```ts
import pick from 'lodash.pick'
```

Comment (christian-bromann) [reply packages/wdio-runner/src/utils.ts:72]: ahh I understand now, I know there was a reason, let me double check

Comment (christian-bromann) [reply packages/wdio-runner/src/utils.ts]: you are right, lodash is not needed here, good catch
