### PR TITLE
fix: support windows/mac apps for isDisplayed

### LINKED ISSUE #14258: [🐛 Bug]: waitForDisplayed and isDisplayed methods are not working for windows apps
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.11.0

### Node.js Version

22.12.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
capabilities: {                                                                        
   chromeBrowser: {                                                                     
     capabilities: {                                                                    
       'browserName': 'chrome',                                                         
       'acceptInsecureCerts': true,                                                     
       'goog:chromeOptions': {                                                          
         debuggerAddress: 'localhost:9222',                                             
       },                                                                               
     },                                                                                 
   },                                                                                   
   workstation: {                                                                       
     path: '/',                                                                         
     hostname: '127.0.0.1',                                                             
     port: 4723,                                                                        
     capabilities: {                                                                    
       'platformName': 'Windows',                                                       
       'appium:automationName': 'windows',                                              
       'appium:app': 'C:\\Program Files\\MicroStrategy\\Workstation\\Workstation.exe',  
       'appium:appArguments': '-p 54213 -l 1033',                                       
       'appium:newCommandTimeout': 200000,                                              
     },                                                                                 
   },                                                                                   
 },
```

### What happened?

After webdriverIO upgrade I noticed that waitForDisplayed and isDisplayed methods do not work on automation of a windows app. This used to work in the past.
Similar issue to https://github.com/webdriverio/webdriverio/issues/14084

### What is your expected behavior?

_No response_

### How to reproduce the bug.

Using appium-windows-driver I create automation for a windows app, unfortunately I cannot share the files. 
But I face the error simply after using waitForDisplayed, I found that waitForExist is working well 

### Relevant log output

```typescript
WARN webdriver: WebDriverError: Unsupported execute method 'function webdriverioPolyfill() {
[0-0]   const __defProp2 = Object.defineProperty;
[0-0]   const __name = function(target, value) {
[0-0]     return __defProp2(target, "name", { value, configurable: true });
[0-0]   };
[0-0]   const __globalThis = typeof globalThis === "object" && globalThis || typeof window === "object" && window;
[0-0]   __globalThis.__name = __name;
[0-0] }
[0-0]             webdriverioPolyfill()
[0-0]             return (function checkVisibility(elem, params) {
[0-0]       return elem.checkVisibility(params);
[0-0]     }).apply(null, arguments)', did you mean 'windows: startRecordingScreen'? Make sure the installed WindowsDriver is up-to-date. Execute methods available in the current driver version are: windows: startRecordingScreen,
 windows: stopRecordingScreen, windows: deleteFolder, windows: setClipboard, windows: getClipboard, windows: deleteFile, windows: clickAndDrag, windows: launchApp, windows: closeApp, windows: scroll, windows: click, windows: hover, windows: keys when running "execute/sync" with method "POST" and args "function checkVisibility(elem, params) {
[0-0]       return elem.checkVisibility(params);
[0-0]     }
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by wswebcreation**
## Proposed changes

This PR fixes #14258 and contains

- add 2 new session flags for windows and mac apps
- add UT's
- add Docs

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: __mocks__/fetch.ts [hunk 1]
```diff
@@ -108,6 +108,26 @@ const requestMock: any = vi.fn().mockImplementation((uri, params) => {
         delete sessionResponse.capabilities.browserName
     }
 
+    if (
+        body &&
+        body.capabilities &&
+        body.capabilities.alwaysMatch.mobileMode &&
+        body.capabilities.alwaysMatch.windowsAppMode
```
Comment (erwinheitzman) [inline __mocks__/fetch.ts:115]:
```suggestion
body?.capabilities?.alwaysMatch.mobileMode &&
body?.capabilities?.alwaysMatch.windowsAppMode
```

Comment (erwinheitzman) [reply __mocks__/fetch.ts:115]: Same goes for the code below

File: packages/wdio-utils/src/envDetector.ts [hunk 2]
```diff
@@ -190,6 +200,44 @@ function isAndroid(capabilities?: WebdriverIO.Capabilities) {
...
+        return false
+    }
+
+    const automationName = getAutomationName(capabilities)
+
+    if (!automationName) {
+        return false
+    }
+
+    return Boolean(automationName.match(new RegExp(automationNameValue, 'i')))
```
Comment (erwinheitzman) [inline packages/wdio-utils/src/envDetector.ts:220]:
```suggestion
    return new RegExp(automationNameValue, 'i').test(automationName)
```

**Review by erwinheitzman — CHANGES_REQUESTED** [review]
Left some feedback on code improvements

File: packages/wdio-utils/src/envDetector.ts (hunk 2 above)
Comment (wswebcreation) [reply packages/wdio-utils/src/envDetector.ts:220]: @erwinheitzman 

This would return an array and match a boolean, or did I learn this wrong last time?

File: __mocks__/fetch.ts (hunk 1 above)
Comment (wswebcreation) [reply __mocks__/fetch.ts:115]: I can change it,m but then i need to change it for the complete file 😅 , I used the same style

**Comment by wswebcreation** [comment]
@christian-bromann 

Do you have some time to look at this? And if agree, can we merge it?

**Review by christian-bromann — APPROVED** [review]
🥇
