### PR TITLE
fix(webdriverio): properly switch context using switchToParentFrame()

### LINKED ISSUE #14064: [🐛 Bug]: `switchToParentFrame` switches to the top-level browsing context (root) instead of (only) the parent frame.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.5.2

### Node.js Version

v20.15.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
	browserName: 'chrome',
	'goog:chromeOptions': {
		args: [
			"disable-search-engine-choice-screen",
			"ignore-certificate-errors",
			...(process.env["CI"] ? ['headless', 'disable-gpu'] : [])
		],
	}
}
```

### What happened?

This test fails:

```ts
import { expect, browser } from '@wdio/globals'

beforeEach(async () => {
    await browser.url(`https://htho.github.io/wdio-repro-iframes/`);
});

// without this, the next test will load the url in the last selected frame
afterEach(() => browser.switchFrame(null))

describe('switchToParentFrame', () => {
    it("switches to parent (not top-level)", async () => {
        await expect($("h1")).toHaveText("Frame Demo");
        await expect($("h2")).not.toExist();
        await expect($("h3")).not.toExist();
    
        await browser.switchFrame($("#A"));
        await expect($("h1")).not.toExist();
        await expect($("h2")).toHaveText("IFrame A");
        await expect($("h3")).not.toExist();
        
        await browser.switchFrame($("#A2"));
        await expect($("h1")).not.toExist();
        await expect($("h2")).not.toExist();
        await expect($("h3")).toHaveText("IFrame A2");

        await browser.switchToParentFrame();
        await expect($("h1")).not.toExist(); // <- FAILS: Expect $(`h1`) not to exist - Received: "exist"
        await expect($("h2")).toHaveText("IFrame A");
        await expect($("h3")).not.toExist();
    });
});
```

### What is your expected behavior?

The test should not fail.

### How to reproduce the bug.

see above - I'm glad to add more if needed

### Relevant log output

```typescript
relevant output included as comment - I'm glad to add more if needed
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #14064
fixes #14070
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### CODE REVIEW

File: packages/webdriverio/src/session/context.ts [hunk 1]
```diff
@@ -77,6 +80,22 @@ export class ContextManager extends SessionManager {
     }
 
     #onCommand(event: { command: string, body: unknown }) {
+        /**
+         * update frame context if user switches using 'switchToParentFrame'
+         */
+        if (event.command === 'switchToParentFrame') {
+            return this.#browser.browsingContextGetTree({}).then(({ contexts }) => {
+                if (!this.#currentContext) {
```
Comment (erwinheitzman) [inline packages/webdriverio/src/session/context.ts:88]: I believe this could be moved higher so that the code up to this point is never run when it doesn't have to be

File: packages/webdriverio/src/session/context.ts [hunk 2]
```diff
@@ -177,4 +196,97 @@ export class ContextManager extends SessionManager {
...
+
+    /**
+     * Find the parent context of a given context id
+     * @param contextId the context id you want to find the parent of
+     * @param contexts  the list of contexts to search through returned from `browsingContextGetTree`
+     * @returns         the parent context of the context with the given id
+     */
+    findParentContext (contextId: string, contexts: local.BrowsingContextInfoList): local.BrowsingContextInfo | undefined {
+        for (const context of contexts) {
+            if (context.children?.find((child) => child.context === contextId)) {
```
Comment (erwinheitzman) [inline packages/webdriverio/src/session/context.ts:233]: I believe that using .some is a tiny bit cheaper to execute as we only need a Boolean to be returned instead of the actual item

**Review by erwinheitzman — APPROVED** [review]
I approved it but did add two suggestions that you could pickup if you feel like they add value

File: packages/webdriverio/src/session/context.ts (hunk 2 above)
Comment (christian-bromann) [reply packages/webdriverio/src/session/context.ts:237]: good catch!
