### PR TITLE
Fix attach to session w3c handling

### LINKED ISSUE #3933: isW3C options is not working for attaching session
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.8.2
 - **Mode:** Standalone mode
 - **If WDIO Testrunner, running sync/async:** async
 - **Node.js version:** 10.11.0
 - **NPM version:** 6.4.1
 - **Browser name and version:** Firefox 66.0.4
 - **Platform name and version:** macOS Mojave
 - **Additional wdio packages used (if applicable):** nothing special

**Config of WebdriverIO**
Not using any config file. Just a single test case can reproduce the issue.

**Describe the bug**
- When attaching to an existing session, `isW3C` option is ignored.
- Moreover the default value (true) is ignored, so we cannot use some commands like `getWindowHandles()` in firefox or IE11 in the attached session.

**To Reproduce**
- Activate Geckodriver
- Create a new session for firefox
- Create a new client and attach to the existing session with `option.isW3C=true`
- Call any commands that have different specification between Json Wire Protocol and WebDriver Protocol

[Include code or an example repository that can easily be set up]
https://gist.github.com/nkns165/32a92f22ec5e6501c7a0c01ce0becfd9
This test code works with mocha.

**Expected behavior**
The webdriver works with W3C WebDriver Protocol (use `session/:sessionId/window/handles`) 

**Log**
https://gist.github.com/nkns165/1ec42e0dc64bc759ef1e2468dd25a0ba

**Additional context**
I investigated the reason a little. Maybe the argument here should be changed.

https://github.com/webdriverio/webdriverio/blob/3fe38b5d9946372d4243d07dbd8cadf05389b19a/packages/webdriver/src/index.js#L92
```
const prototype = Object.assign(getPrototype({isW3C: options.isW3C}), userPrototype)
```

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Currently `attachToSession` ignores W3C option and assumes that it is always **false**.

This PR fixes it.
`isW3C` default value is now true and `attachToSession` respects isW3C passed value.

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

fixes #3933

### CODE REVIEW

File: packages/webdriver/src/index.js [hunk 1]
```diff
@@ -88,8 +88,8 @@ export default class WebDriver {
         logger.setLevel('webdriver', options.logLevel)
 
         options.capabilities = options.capabilities || {}
-        options.isW3C = options.isW3C || true
-        const prototype = Object.assign(getPrototype(options.isW3C), userPrototype)
+        options.isW3C = options.isW3C === false ? false : true
+        const prototype = Object.assign(getPrototype({ isW3C: options.isW3C }), userPrototype)
```
Comment (christian-bromann) [inline packages/webdriver/src/index.js]: I think it also makes sense to add the other flags in here too , like `isChrome` , `isSauce` etc, no?

Comment (mgrybyk) [reply packages/webdriver/src/index.js]: yeah, `getPrototype` accepts `{ isW3C, isChrome, isMobile, isSauce }`. 
Agree that it makes sense to pass all of them

Comment (mgrybyk) [reply packages/webdriver/src/index.js]: @christian-bromann  updated

File: packages/webdriver/src/index.js [hunk 2]
```diff
@@ -88,8 +88,8 @@ export default class WebDriver {
         logger.setLevel('webdriver', options.logLevel)
 
         options.capabilities = options.capabilities || {}
-        options.isW3C = options.isW3C || true
-        const prototype = Object.assign(getPrototype(options.isW3C), userPrototype)
+        options.isW3C = options.isW3C === false ? false : true
+        const prototype = Object.assign(getPrototype({ ...options, isW3C: options.isW3C }), userPrototype)
```
Comment (christian-bromann) [inline packages/webdriver/src/index.js]:
```suggestion
        const prototype = Object.assign(getPrototype({ ...options }), userPrototype)
```

Comment (mgrybyk) [reply packages/webdriver/src/index.js]: @christian-bromann done
