### PR TITLE
fix: relative XPath chaining in BiDi mode

### LINKED ISSUE #14675: [🐛 Bug]: XPath chaining not working in V9 in methods but same code working in v7
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.18.4

### Node.js Version

24

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript

```

### What happened?

XPath chaining from the page objects files when specified in a method is not recognisable.
Ex: declare a locator get sampleLocator(){return $(‘//div/input’)}
Try chaining the same in a method using sibling like: cont actual = await this.sampleLocator.$(‘./following-sibling::div’)
waitfordisplayed(actual)
Seems like wdio9 unable to recognise the chained part when executed, but wdio7 has no issues and working absolutely fine.
So the workaround I have used is to add browser.execute

### What is your expected behavior?

_No response_

### How to reproduce the bug.

Create chaining xpath from methods in page object file using wdio9

### Relevant log output

```typescript
Element not displayed
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by mccmrunal**
Fixes #14675

## Proposed changes

This PR fixes an issue where chaining relative XPath selectors (e.g., `element.$('./following-sibling::div')`) fails when running in WebDriver BiDi mode (the default in v9).

**Root Cause:**
The WebDriver BiDi `browsingContext.locateNodes` command, when provided with `startNodes`, searches for elements *within the descendants* of those nodes. It does not interpret relative XPath expressions (starting with `./` or `..`) as relative to the `startNodes` themselves in the same way WebDriver Classic does. This caused selectors like `./following-sibling::div` to fail to find elements that are siblings of the context element.

**The Fix:**
I updated `findDeepElement` and `findDeepElements` in [packages/webdriverio/src/utils/index.ts] to detect this specific scenario:
1. The selector strategy is `xpath`.
2. The selector value starts with `./` or `..` (indicating a relative path).
3. The command is being executed on an element (i.e., `elementId` is present).

When these conditions are met, the code now falls back to using the WebDriver Classic `findElementFromElement` (or `findElementsFromElement`) command, ensuring the relative XPath is evaluated correctly against the context element.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)
I verified this fix by:
1. Creating a local reproduction case with `element.$('./following-sibling::div')` which failed in BiDi mode.
2. Confirming the test passes with this fix applied.
3. Adding unit tests in [packages/webdriverio/tests/utils/index.test.ts]

### CODE REVIEW

File: packages/webdriverio/src/utils/index.ts [hunk 1]
```diff
@@ -317,6 +317,16 @@ export async function findDeepElement(
         (this as WebdriverIO.Element).elementId
     )
     const { using, value } = findStrategy(selector as string, this.isW3C, this.isMobile)
+
+    /**
+     * if we are using a relative xpath selector and we have a parent element
+     * we need to fall back to the regular WebDriver Classic command as BiDi
+     * does not support relative xpath selectors with a start node
+     */
+    if (using === 'xpath' && (value.startsWith('./') || value.startsWith('..')) && (this as WebdriverIO.Element).elementId) {
```
Comment (christian-bromann) [inline packages/webdriverio/src/utils/index.ts:326]: As mentioned in the other PR, can we use [`startNodes`](https://www.w3.org/TR/webdriver-bidi/#command-browsingContext-locateNodes) to enable this?

Comment (mccmrunal) [reply packages/webdriverio/src/utils/index.ts:326]: startNodes searches within descendants only. Sibling axes like ./following-sibling::* look outside, so Classic fallback is still needed. (This is my understanding - happy to be corrected if I'm wrong!)

**Review by christian-bromann — APPROVED** [review]
LGTM 👍
