### PR TITLE
v6 release bug fixes

### LINKED ISSUE #5167: devtools: Cannot find module puppeteer-core/node_modules/debug
**Environment:**
 - **WebdriverIO version:** 6.0.5
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 12.16.1
 - **NPM version:** 6.14.4
 - **Browser name and version:** any
 - **Platform name and version:** any

**Config of WebdriverIO**
Any.

**Describe the bug**
Test runner crashes, see logs.
Possible cause: 
https://github.com/webdriverio/webdriverio/pull/5007/files#diff-ac866ff0354e029d2ba18bc72e991988R19
Locking puppeteer-core to 2.1.1 with npm shrinkwrap does not help.

**To Reproduce**
???
Upgrade to v6.

**Expected behavior**
Test runner should not not crash.

**Log**
```js
(node:10834) UnhandledPromiseRejectionWarning: Error: Cannot find module '/Users/[REDACTED]/Repos/wdio-v6/node_modules/puppeteer-core/node_modules/debug'
Require stack:
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/devtools/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/utils.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/multiremote.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/webdriverio/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/build/commands/repl.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/yargs/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/build/index.js
- /Users/[REDACTED]/Repos/wdio-v6/node_modules/@wdio/cli/bin/wdio.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/[REDACTED]/Repos/wdio-v6/node_modules/devtools/build/index.js:47:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)

```

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

This patch fixes:

- documentation on how to use Babel with Jasmine
- a bug where devtools package throws due to not finding debug package
- services that check failure status in `afterTest` hook

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

closes #5167, #5174, #5167

### CODE REVIEW

File: packages/devtools/src/index.js [hunk 1]
```diff
@@ -16,10 +17,19 @@ const log = logger('devtools:puppeteer')
...
+let puppeteerDebugPkg = path.resolve(
     path.dirname(require.resolve('puppeteer-core')),
     'node_modules',
     'debug')
+
+/**
+ * check if Puppeteer has its own version of debug, if not use the
+ * one that is installed for all packages
+ */
+if (!fs.existsSync(puppeteerDebugPkg)) {
```
Comment (wswebcreation) [inline packages/devtools/src/index.js]: Dont' we have/need a UT for this?

Comment (christian-bromann) [reply packages/devtools/src/index.js]: fair point
