### PR TITLE
fix jasmine afterTest hook

### LINKED ISSUE #11495: [🐛 Bug]: afterTest hook contains wrong test object but correct error in a specific scenario
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.20.2

### Node.js Version

18.6.1

### Mode

Standalone Mode

### Which capabilities are you using?

_No response_

### What happened?

The afterTest hook is called containing the wrong test object but correct error in a specific scenario

Using the example spec from the documentation I have added two tests to demonstrate the issue. The first one fails due to a time out because the last line does not contain the text it is expecting ('d' removed from 'logged'). The second test case fails because of an exception (k not defined).

- When running with Mocha test framework -  the afterTest hook is called correctly.
- When running with the Jasmine test framework - the afterTest hook is called incorrectly. The test object in both cases is the second test case, but the error is different (and correct) in each invocation.

```
import { expect } from '@wdio/globals'
import LoginPage from '../pageobjects/login.page.js'
import SecurePage from '../pageobjects/secure.page.js'

describe('My Login application', () => {
    it('timeout failure', async () => {
        await LoginPage.open()
        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(true).toBe(true);
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logge into a secure area!')
    })
    it('exception fail rather than assert', async () => {
        await LoginPage.open()
        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        k++; // reference error, k not defined
        await expect(true).toBe(true);
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
    })
})

```

If you change the order of the test cases (in this case reverse them) so that the timed out test is last then the afterTest hook is called correctly for both Mocha and Jasmin:

```
import { expect } from '@wdio/globals'
import LoginPage from '../pageobjects/login.page.js'
import SecurePage from '../pageobjects/secure.page.js'

describe('My Login application', () => {
    it('exception fail rather than assert', async () => {
        await LoginPage.open()
        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        k++; // reference error, k not defined
        await expect(true).toBe(true);
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logged into a secure area!')
    })
   it('timeout failure', async () => {
        await LoginPage.open()
        await LoginPage.login('tomsmith', 'SuperSecretPassword!')
        await expect(true).toBe(true);
        await expect(SecurePage.flashAlert).toBeExisting()
        await expect(SecurePage.flashAlert).toHaveTextContaining(
            'You logge into a secure area!')
    })
})

```

### What is your expected behavior?

The afterTest hook should contain the correct test object.

### How to reproduce the bug.

1. Create a new wdio project
2. Use the example spec from the documentation but modified in the way shown above in the 'What happened' section.
3. Set test framework to Jasmine (the issue does not occur with Mocha)
4. Add a console.log of the test object return in the afterTest hook (or use debugger/breakdpoint).
5. You will see the same test object in the afterTest hook but the error will be different (and correct) in the two invocations.

### Relevant log output

```typescript
Follow steps in How to reproduce the bug. This can be reproduced with a new project quickly.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by tamil777selvan**
## Proposed changes

Fixes #11495

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-utils/src/shim.ts [hunk 1]
```diff
@@ -289,8 +289,12 @@ export async function executeAsync(this: any, fn: Function, retries: Frameworks.
     this.wdioRetries = retries.attempts
 
     try {
+        /**
+         * Decrease the overall timeout by 3 milliseconds to ensure that when a test fails due to a timeout exception in Jasmine,
+         * the test objects are returned instead of being overridden by the values of the next test.
+         */
         // @ts-expect-error
-        const _timeout = this?._runnable?._timeout || globalThis.jasmine?.DEFAULT_TIMEOUT_INTERVAL || timeout
+        const _timeout = (this?._runnable?._timeout || globalThis.jasmine?.DEFAULT_TIMEOUT_INTERVAL || timeout) - 3
```
Comment (christian-bromann) [inline packages/wdio-utils/src/shim.ts:297]: Do we know that 3ms are enough for this to not happen? It seems a bit arbitrary.

Comment (tamil777selvan) [reply packages/wdio-utils/src/shim.ts:297]: It does not need to be precisely 3ms. It just needs to be a shorter duration than the overall timeout. So, I've used 3ms, making sure it doesn't disrupt the timeouts set & execution timeline.

Comment (christian-bromann) [reply packages/wdio-utils/src/shim.ts:297]: Can we move the `3` to a const at the top of the file with a descriptive name and a comment as to why the value is chosen? I think it would greatly help anyone stumbling over it in the future.

Comment (tamil777selvan) [reply packages/wdio-utils/src/shim.ts:297]: sure, on it.

**Review by christian-bromann — APPROVED** [review]
Awesome, LGTM 👍
