### PR TITLE
fix multiremote instances spawning

### LINKED ISSUE #2825: Multiremote support for multiple specs
## The problem

Missing feature of being able to run multiremote tests in locally and cloud services like Saucelabs or Browserstack correctly.  When you have more than one spec defined as multiremote test then you want Saucelabs or BrowserStack to spin up new VMs per spec. Currently it uses the same VM for all the multiremote specs, and soon exhausts itself.  This is seen locally also.

## Environment

* WebdriverIO version: 4.13.1 and v5
* Node.js version: 8.6.0
* [Standalone mode or wdio testrunner](http://webdriver.io/guide/getstarted/modes.html): wdio
* if wdio testrunner, running synchronous or asynchronous tests: sync
* Additional wdio packages used (if applicable):  `wdio-sauce-service`

## Details

Run multiremote tests (more than 1 spec) on saucelabs or browserstack and the wdio launcher will use the initial pair (or however many you declare) of VMs across all your tests.  It should dispose of the VMs at the end of the test and create new ones by default.  It is not expected to run the tests in parallel so this is not required (maxInstances support).  Looking at `launcher.js` multiremote tests will only every run one `processNumber` with a single `cid` despite different tests starting.  The process count remains the same.

## Link to Selenium/WebdriverIO logs

N/A

## Code To Reproduce Issue [ Good To Have ]

Run the example multiremote in saucelabs from wdio runner, but duplicate the test to have more than 1 multiremote spec to run.

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Change way how multiremote mode spawns instances.

**Current behaviour**
- all the spec files are running in same worker. This causing issues with reporters and limits spawning of instances (so parallelization works bad)
- instances are not killed in the very end, browsers are hanging opened

**New behaviour**
- another worker spawned for each spec file
- spec files can run in parallel
- browser instances are killed after every spec file (same as in non multiremote mode)

fixes #2825

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: packages/wdio-cli/src/launcher.js [hunk 1]
```diff
@@ -97,20 +97,10 @@ class Launcher {
...
-                this.resolve = resolve
-                this.startInstance(this.configParser.getSpecs(), caps, 0)
-            })
-        }
-
         /**
          * fail if no caps were found
          */
-        if (!caps || !caps.length) {
+        if (!caps || (!this.isMultiremote && !caps.length)) {
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/launcher.js]: can be simplified to:
`if (!caps || !caps.length)`

File: packages/wdio-cli/src/launcher.js [hunk 2]
```diff
@@ -122,15 +112,31 @@ class Launcher {
...
+             * Multiremote mode
+             */
             this.schedule.push({
                 cid: cid++,
-                caps: capabilities,
-                specs: this.configParser.getSpecs(capabilities.specs, capabilities.exclude).map(s => ({ files: [s], retries: config.specFileRetries })),
-                availableInstances: capabilities.maxInstances || config.maxInstancesPerCapability,
-                runningInstances: 0,
-                seleniumServer: { hostname: config.hostname, port: config.port, protocol: config.protocol }
+                caps,
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/launcher.js]: This is now the object containing all configured browsers, is this what we need here?

File: packages/wdio-cli/src/launcher.js [hunk 3]
```diff
@@ -122,15 +112,31 @@ class Launcher {
...
+                specs: this.configParser.getSpecs(caps.specs, caps.exclude).map(s => ({ files: [s], retries: config.specFileRetries })),
+                availableInstances: config.maxInstances || 1,
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/launcher.js]: Why 1 instead of maxInstancesPerCapability?

File: packages/wdio-cli/src/launcher.js [hunk 4]
```diff
@@ -122,15 +112,31 @@ class Launcher {
...
+            /**
+             * Multiremote mode
+             */
             this.schedule.push({
                 cid: cid++,
-                caps: capabilities,
-                specs: this.configParser.getSpecs(capabilities.specs, capabilities.exclude).map(s => ({ files: [s], retries: config.specFileRetries })),
-                availableInstances: capabilities.maxInstances || config.maxInstancesPerCapability,
-                runningInstances: 0,
-                seleniumServer: { hostname: config.hostname, port: config.port, protocol: config.protocol }
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/launcher.js]: This line isn't needed for multi remote?

File: packages/wdio-cli/src/launcher.js [hunk 5]
```diff
@@ -342,16 +348,16 @@ class Launcher {
         }
         this.interface.emit('job:end', { cid, passed, retries })
 
-        // Update schedule now this process has ended
-        if (!this.isMultiremote) {
-            // get cid (capability id) from rid (runner id)
-            cid = parseInt(cid, 10)
+        /**
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/launcher.js]: Seems like the code below will now get executed for both multi remote as well as regular mode, is this correct?

File: packages/wdio-runner/src/index.js [hunk 6]
```diff
@@ -270,26 +270,45 @@ export default class Runner extends EventEmitter {
      * within a hook by the user
      */
     async endSession (shutdown) {
+        /**
+         * For Multiremote - make sure that all the instances have sessionId
+         */
+        const hasSessionId = global.browser && (this.isMultiremote ? !global.browser.instances.some(i => global.browser[i] && !global.browser[i].sessionId) : global.browser.sessionId)
```
Comment (erwinheitzman) [inline packages/wdio-runner/src/index.js]: Pretty long line, perhaps divide over more lines for readability.

File: packages/wdio-cli/src/launcher.js (hunk 1 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: `caps` is an object in Multiremote, while in regular mode it is an array.

Before current PR this block was unreachable in Multiremote, so have to add this condition

File: packages/wdio-cli/src/launcher.js (hunk 3 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: Before it was allowed to have only 1 instance in multiremote, even maxInstances was ignored.
I've noticed that maxInstances value is 100 and was afraid it might brake something in Multiremote, so I decided to use 1 instead of maxInstancesPerCapability

I can change it to something like `maxInstancesPerCapability / (Object.keys(caps).length || 1)` to avoid spawning to much browser instances in Multiremote. Not sure if it makes sense to do that.

File: packages/wdio-cli/src/launcher.js (hunk 4 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: It was not used before, most likely it is not needed because this line might differ per Multiremote instance

File: packages/wdio-cli/src/launcher.js (hunk 5 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: absolutely! There is no more difference here now between regular and multiremote modes

File: packages/wdio-runner/src/index.js (hunk 6 above)
Comment (mgrybyk) [reply packages/wdio-runner/src/index.js]: agree, fixing

File: packages/wdio-cli/src/launcher.js (hunk 2 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: yes, that is how multiremote works

File: packages/wdio-cli/src/launcher.js (hunk 3 above)
Comment (erwinheitzman) [reply packages/wdio-cli/src/launcher.js]: I can only find a few references to maxInstancesPerCapability, this actually seems deprecated: https://webdriver.io/docs/options.html

File: packages/wdio-runner/src/index.js (hunk 6 above)
Comment (mgrybyk) [reply packages/wdio-runner/src/index.js]: @erwinheitzman fixed!

File: packages/wdio-cli/src/launcher.js (hunk 3 above)
Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: ah sorry, one more comment, it makes no sense to use `maxInstancesPerCapability`, we should only use `maxInstances`, so that's fine.
Sorry for confusing, `maxInstancesPerCapability` only makes sense in regular mode

**Comment by mgrybyk** [comment]
@erwinheitzman do you have some more comments?

**Comment by mgrybyk** [comment]
@christian-bromann can we merge this one?
