### PR TITLE
webdriverio: fix isDisplayed

### LINKED ISSUE #3699: blocker: isDisplayed doesn't work in Appium in 5.7.1
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.1

**Config of WebdriverIO**
Using Appium 1.11.1

```
capabilities: [{
...
    "appium:app": __dirname + '/../../apps/MoPlay.apk',
    "appium:appPackage": 'com.addisongloballtd.moplay.adhoc',
    "appium:appActivity": 'com.moplay.MainActivity',
}]
```

**Describe the bug**
isDisplayed doesn't work, works fine in 5.7.0

**To Reproduce**
`$('~BUTTON').waitForDisplayed()`

**Expected behavior**
isDisplayed, waitForDisplayed should work

**Log**
```
Error: waitUntil condition failed with the following reason: Cannot read property 'toLowerCase' of undefined
    at timer.catch.e (/e2e/node_modules/webdriverio/build/commands/browser/waitUntil.js:75:11)
    at Element.waitForDisplayed (/e2e/node_modules/webdriverio/build/commands/element/waitForDisplayed.js:51:15)
```

**Additional context**

> Please use the correct markdown

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

fix #3699 #3700 #3645 #3709 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

code for testing PR
```
browser.url("http://adam.goucher.ca/parkcalc/")
const inputSelector = "input[type='submit']"

// already not existing
$("not-existing").waitForDisplayed(2000, true)
const el = $(inputSelector)
console.log(el.isDisplayed()) // true

// remove element in 3 seconds
browser.execute(function (selector) {
    const window = this
    window.setTimeout(() => {
        window.document.querySelector(selector).remove()
    }, 3000);
}, inputSelector)

// first existing, then not existing
$(inputSelector).waitForDisplayed(8000, true)
console.log(el.isDisplayed()) // false
```

### CODE REVIEW

File: packages/webdriverio/src/commands/element/isDisplayed.js [hunk 1]
```diff
@@ -70,7 +70,7 @@ export default async function isDisplayed() {
      * no longer dictates it. In those instances, we pass the element through a script
      * that was provided by Brian Burg of safaridriver.
      */
-    return browser.isW3C && noW3CEndpoint.includes(browser.capabilities.browserName.toLowerCase()) ?
+    return browser.isW3C && !browser.isMobile && noW3CEndpoint.includes(browser.capabilities.browserName.toLowerCase()) ?
```
Comment (mgrybyk) [inline packages/webdriverio/src/commands/element/isDisplayed.js]: fix #3699

File: packages/webdriverio/src/utils/implicitWait.js [hunk 2]
```diff
@@ -11,7 +11,7 @@ const log = logger('webdriverio')
  */
 export default async function implicitWait (currentElement, commandName) {
 
-    if (!currentElement.elementId && !commandName.match(/(waitUntil|waitFor|isExisting|isDisplayed)/)) {
+    if (!currentElement.elementId && !commandName.match(/(waitUntil|waitFor|isExisting|is?\w+Displayed)/)) {
```
Comment (mgrybyk) [inline packages/webdriverio/src/utils/implicitWait.js]: fix #3700

**Comment by abjerstedt** [comment]
Can iphone 12 safari still work with this? I think they still use safari driver and lose the endpoint.

**Comment by mgrybyk** [comment]
@abjerstedt I'll test this really soon.

Are there any other cases to verify?

**Comment by wswebcreation** [comment]
@mgrybyk 
Yes, iOS Hybrid app. I can verify the mobile parts if needed now. Give me 30 minutes

**Comment by mgrybyk** [comment]
@wswebcreation I'll be verifying all the cases really soon as well.
Doing mobile testing on emulators, but I think it shouldn't be a problem in this case.
Missing IE and Edge.

**Comment by wswebcreation** [comment]
Ok, then I'll proceed working for my boss 😜

**Comment by abjerstedt** [comment]
@mgrybyk IE is unaffected by either the last or this PR. Edge should be fine... i don't think anyone actually tests mobile edge anyways.

**Comment by mgrybyk** [comment]
@abjerstedt @wswebcreation 

- Android app **PASSED**
- Android browser chrome **PASSED**
- iOS app
- iOS browser safari
- Chrome **PASSED**
- Firefox **PASSED**
- Safari _FAILED_ !!!
test is not failing, however instead of `false` I'm receiving
`{ error: 'no such element', message: '', stacktrace: '' }`

**Comment by abjerstedt** [comment]
@mgrybk yeah... theres already an issue with safari and refetch (from before my recent PRs).

I think safari is giving us a different status or response code on stales preventing us from matching and handling them.

**Comment by mgrybyk** [comment]
I'm using following code for testing everything except of native app:
```
        browser.url("http://adam.goucher.ca/parkcalc/")
        const el = $("input[type='submit']")
        console.log(el.isDisplayed()) // should return true
        browser.execute(function () {
            this.document.querySelector("input[type='submit']").remove()
        })
        console.log(el.isDisplayed()) // should return false
```

**Comment by mgrybyk** [comment]
@abjerstedt should I fix it as well within this PR?

**Comment by abjerstedt** [comment]
Do we also want to add execute to this exclusion list for waiting?

**Comment by abjerstedt** [comment]
@mgrybyk might as well. They are all slightly related.

**Comment by mgrybyk** [comment]
@abjerstedt
> Do we also want to add execute to this exclusion list for waiting?

Not sure, from the first point of view it makes sense, but I might be wrong :)

**Comment by mgrybyk** [comment]
@wswebcreation can you help with testing native app?
I'm having some issues with certificate and unable to verify it right now

**Comment by mgrybyk** [comment]
@abjerstedt fixed Safari issue `{ error: 'no such element', message: '', stacktrace: '' }`

File: packages/webdriverio/src/commands/element/isDisplayed.js [hunk 3]
```diff
@@ -70,10 +70,11 @@ export default async function isDisplayed() {
...
      * that was provided by Brian Burg of safaridriver.
      */
-    return browser.isW3C && noW3CEndpoint.includes(browser.capabilities.browserName.toLowerCase()) ?
+    const result = browser.isW3C && !browser.isMobile && noW3CEndpoint.includes(browser.capabilities.browserName.toLowerCase()) ?
         await browser.execute(isElementDisplayedScript, {
             [ELEMENT_KEY]: this.elementId, // w3c compatible
             ELEMENT: this.elementId // jsonwp compatible
         }) :
         await this.isElementDisplayed(this.elementId)
+    return result === true
```
Comment (mgrybyk) [inline packages/webdriverio/src/commands/element/isDisplayed.js]: @abjerstedt fix of Safari's `{ error: 'no such element', message: '', stacktrace: '' }`

**Comment by mgrybyk** [comment]
- Android app **PASSED**
- Android browser chrome **PASSED**
- iOS app  _unable to verify_
- iOS browser safari **PASSED**
- Chrome **PASSED**
- Firefox **PASSED**
- Safari **PASSED**

**Comment by wswebcreation** [comment]
@mgrybyk 

I can do that in about 30-60 minutes, currently busy with some stuff for my boss

File: packages/webdriverio/src/commands/element/isDisplayed.js (hunk 3 above)
Comment (mgrybyk) [reply packages/webdriverio/src/commands/element/isDisplayed.js]: ignore this "fix".

Comment (abjerstedt) [reply packages/webdriverio/src/commands/element/isDisplayed.js]: This won't fix the other commands though. We will want to update the response parser in webdriver.

**Comment by mgrybyk** [comment]
Thanks a lot, @wswebcreation  

P.S. please don't merge this PR, have to do some more minor fixes and add tests

File: packages/webdriverio/src/middlewares.js [hunk 4]
```diff
@@ -15,7 +15,19 @@ export const elementErrorHandler = (fn) => (commandName, commandFn) => {
...
 
             try {
-                return await fn(commandName, commandFn).apply(this, args)
+                const result = await fn(commandName, commandFn).apply(this, args)
+
+                /**
+                 * assume Safari responses like { error: 'no such element', message: '', stacktrace: '' }
+                 * as `stale element reference`
+                 */
+                if (result && result.error === 'no such element') {
```
Comment (mgrybyk) [inline packages/webdriverio/src/middlewares.js]: fix #3645

Comment (abjerstedt) [reply packages/webdriverio/src/middlewares.js]: Can we handle this inside webdriver instead?
packages/webdriver/src/utils.js
isSuccessfulResponse (statusCode, body) {

Comment (abjerstedt) [reply packages/webdriverio/src/middlewares.js]: ultimately, it would be nice if we could consume this inCustomRequestError and treat safari's stale elements the same as the rest

Comment (mgrybyk) [reply packages/webdriverio/src/middlewares.js]: @abjerstedt sorry to say there is no way to do it.
We have to keep this dirty hack.
The problem is that there is no difference between Safari's not found element and Safari's stale element exception.

My proposal would be to leave this code as is.

**Comment by christian-bromann** [comment]
@mgrybyk can you remove the `DEL_ME` file? Feel free to add it to gitignore if you use it for dev purposes

**Comment by mgrybyk** [comment]
@christian-bromann sorry for that. I'll delete it later today

**Comment by mgrybyk** [comment]
@christian-bromann deleted.

**Comment by christian-bromann** [comment]
@abjerstedt can you do another review?

File: packages/webdriverio/src/utils/implicitWait.js (hunk 2 above)
Comment (mgrybyk) [reply packages/webdriverio/src/utils/implicitWait.js]: also fixes #3709

File: packages/webdriverio/src/middlewares.js (hunk 4 above)
Comment (abjerstedt) [reply packages/webdriverio/src/middlewares.js]: @mgrybyk We still need to handle the safari stales upstream in webdriver (but i can put a diff pr up). 

We need to block the triple requests and just return an element not found. This should hypothetically cause the middleware to just work.

Comment (mgrybyk) [reply packages/webdriverio/src/middlewares.js]: Agree, I've noticed that requests are multiplied.
If you can assist it would be really awesome!
