### PR TITLE
fix(webdriverio): properly handle unresolved element on `switchFrame` input in non-BIDI scenario

### LINKED ISSUE #13856: [🐛 Bug]: `switchFrame()` doesn't always accept promise
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.2.8

### Node.js Version

v22.6.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
    browserName: 'electron',
    browserVersion: '33.0.0',
    'wdio:electronServiceOptions': {
        appArgs: []
    }
}
```

### What happened?

The `await browser.switchFrame($('iframe'))` will fail in Electron app test setup with `wdio-electron-service` with the following error:
> WebDriverError: invalid argument: missing 'ELEMENT'

### What is your expected behavior?

Based on [`switchFrame()`](https://webdriver.io/docs/api/browser/switchFrame/) WDIO docs and [existing test](https://github.com/webdriverio/webdriverio/blob/v9.2.10/e2e/wdio/headless/test.e2e.ts#L517-L526) in E2E test suite, the following construct should work with no errors:

```javascript
await browser.switchFrame($('iframe'))
```

### How to reproduce the bug.

Here is the repo to reproduce the problem: https://github.com/gavvvr/wdio-electron-service-818

### Relevant log output

```typescript
[0-0] 2024-11-05T22:00:38.362Z ERROR webdriver: WebDriverError: invalid argument: missing 'ELEMENT'
[0-0]   (Session info: chrome=130.0.6723.59) when running "frame" with method "POST" and args "{"id":{}}"
[0-0] invalid argument in "My Login application.should reset the frame when the page is reloaded"
invalid argument: WebDriverError: invalid argument: missing 'ELEMENT'
  (Session info: chrome=130.0.6723.59) when running "frame" with method "POST" and args "{"id":{}}"
    at async Context.<anonymous> (/Users/user/Documents/sandboxes/wdio-electron-iframe-ts/test/specs/test.e2e.ts:4:5
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by gavvvr**
## Proposed changes

Fixes #13856

Rearrange the code to handle input the same way in non-BIDI and BIDI scenarios

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriverio/src/commands/browser/switchFrame.ts [hunk 1]
```diff
@@ -70,6 +70,29 @@ export async function switchFrame (
...
+     * that was previously queried.
+     */
+    if (typeof context === 'object' && typeof (context as WebdriverIO.Element).getElement === 'function') {
+        const element = await context.getElement()
+        await element.waitForExist({
+            timeoutMsg: `Can't switch to frame with selector ${element.selector} because it doesn't exist`
+        })
+        return switchToFrameUsingElement(this, element)
+    }
+
```
Comment (erwinheitzman) [inline packages/webdriverio/src/commands/browser/switchFrame.ts:95]: You now skip the needed check on line 99

**Review by erwinheitzman — CHANGES_REQUESTED** [review]

**Review by christian-bromann — APPROVED** [review]
Great contribution 👍
