### PR TITLE
Fixes issue 9578 

### LINKED ISSUE #9578: [🐛 Bug]: Configuration wizard: validate relative path for specs/feature files and page objects
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8

### Node.js Version

v19.3.0

### Mode

Standalone Mode

### Which capabilities are you using?

_No response_

### What happened?

I was I am trying to build an automation framework using cucumber. I filled out the following correctly : 

Screenshot 2023-01-12 at 16 10 17

### What is your expected behavior?

I was expecting to wdio file correctly show feature files, step definition files and page object folder correctly.  Instead I keep seeing the following: 

[watch this video](https://www.dropbox.com/s/aweeht1y7vu4gz8/cucumber%20page%20layout%20%20error.mov?dl=0)

### How to reproduce the bug.

Please view the 'what happened' box 

### Relevant log output

```typescript
Please view the 'what happened' box
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by KierenLWoods**
## Proposed changes

This change fixes #9578 . There was an issue where if a user answered the test file generation location questions with a response such as 'y', the wizard would then put all the files in the current directory. With this fix even if 'y' was to be passed the files would then be generated in a folder named y under the project root. This PR also fixes a bug around the step definition file location. 

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

fixes #9578

### CODE REVIEW

File: packages/wdio-cli/src/utils.ts [hunk 1]
```diff
@@ -592,14 +592,14 @@ export async function getAnswers(yes: boolean): Promise<Questionnair> {
 export function getPathForFileGeneration(answers: Questionnair, projectRootDir: string) {
     const destSpecRootPath = path.resolve(
         projectRootDir,
-        path.dirname(answers.specs || '').replace(/\*\*$/, ''))
+        (path.dirname(answers.specs || '') === '.' ? path.resolve(answers.specs || '') : path.dirname(answers.specs || '')).replace(/\*\*$/, ''))
 
-    const destStepRootPath = path.resolve(projectRootDir, path.dirname(answers.stepDefinitions || ''))
+    const destStepRootPath = path.resolve(projectRootDir, (path.dirname(answers.stepDefinitions || '') === '.' ? path.resolve(answers.stepDefinitions || '') : path.dirname(answers.stepDefinitions || '')))
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:597]: same

File: packages/wdio-cli/src/utils.ts [hunk 2]
```diff
@@ -590,16 +590,20 @@ export async function getAnswers(yes: boolean): Promise<Questionnair> {
...
+        (path.dirname(specAnswer) === '.' ? path.resolve(specAnswer) : path.dirname(specAnswer)).replace(/\*\*$/, ''))
 
-    const destStepRootPath = path.resolve(projectRootDir, path.dirname(answers.stepDefinitions || ''))
+    const destStepRootPath = path.resolve(projectRootDir, (path.dirname(stepDefinitionAnswer) === '.' ? path.resolve(stepDefinitionAnswer) : path.dirname(stepDefinitionAnswer)))
 
     const destPageObjectRootPath = answers.usePageObjects
         ? path.resolve(
             projectRootDir,
-            path.dirname(answers.pages || '').replace(/\*\*$/, ''))
+            (path.dirname(pageObjectAnswer) === '.' ? path.resolve(pageObjectAnswer) : path.dirname(pageObjectAnswer)).replace(/\*\*$/, ''))
```
Comment (erwinheitzman) [inline packages/wdio-cli/src/utils.ts:606]: Let's make a function that automatically resolves this by taking the answer, check if . and resolve if needed

**Review by erwinheitzman — CHANGES_REQUESTED** [review]

**Review by christian-bromann — APPROVED** [review]
Awesome, great work! LGTM 👍
