### PR TITLE
allure-reporter: fix mime type

### LINKED ISSUE #6053: [wdio-allure-reporter] Unable to attach buffer content type as a 'image/png'  to allure report
https://github.com/webdriverio/webdriverio/blob/63519058a7fab1bdc424fc95c14f97207d496627/packages/wdio-allure-reporter/src/index.js#L538-L540

All kind of buffer content types (like screenshots created in wdio) are handed as a  'text/plain'  due to changes made in #6022

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

fix #6053

- allows user to override the default types
- assume a Buffer is an image unless the type is explicitly provided
- added tests to cover all the scenarios

works like this: `AllureReporter.addAttachment('scr', Buffer.from(browser.takeScreenshot(), 'base64'))`

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: packages/wdio-allure-reporter/src/index.js [hunk 1]
```diff
@@ -444,7 +444,8 @@ class AllureReporter extends WDIOReporter {
     }
 
     dumpJSON(name, json) {
-        this.allure.addAttachment(name, JSON.stringify(json, null, 2), 'application/json')
+        const content = JSON.stringify(json, null, 2)
+        this.allure.addAttachment(name, typeof content === 'string' ? content : `${content}`, 'application/json')
```
Comment (christian-bromann) [inline packages/wdio-allure-reporter/src/index.js:448]: Why do we need to check if `content` is a string if we use `JSON.stringify` above? That method always returns a string.

Comment (mgrybyk) [reply packages/wdio-allure-reporter/src/index.js:448]: It doesn't, it can return undefined that causes failures

Comment (christian-bromann) [reply packages/wdio-allure-reporter/src/index.js:448]: This would mean we would add `undefined` as content. How about we have a:

```js
if (!json) {
    return
}
```
instead?

Comment (mgrybyk) [reply packages/wdio-allure-reporter/src/index.js:448]: not sure, I'd always add whatever the user wants, even if it's undefined.
I'd like to see undefined in attachments if I passed it

Comment (christian-bromann) [reply packages/wdio-allure-reporter/src/index.js:448]: but undefined is not really saying anything, and it is also not a `'application/json'` mime type. Can we have something like "no content" or something like that?

Comment (mgrybyk) [reply packages/wdio-allure-reporter/src/index.js:448]: yeah, I'll set it to text plain

Comment (mgrybyk) [reply packages/wdio-allure-reporter/src/index.js:448]: but I'd not change undefined to anything, because it can be what user has passed, ex
```
let a
if (b) { a = b }
addAttachment('a', a) // I expect to see either undefined or b
```

**Review by christian-bromann — APPROVED** [review]
LGTM 👍
