### PR TITLE
Fix wrapCommand for async command execution

### LINKED ISSUE #4849: beforeCommand, afterCommand do not work when use async
Hello,

I'm trying to use beforeCommand and afterCommand hooks in order to catch browser.url command. unfortunately, it does not work.

```
    /**
     * Runs before a WebdriverIO command gets executed.
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     */
    beforeCommand: function (commandName, args) {
//something
    },

    /**
     * Runs after a WebdriverIO command gets executed
     * @param {String} commandName hook command name
     * @param {Array} args arguments that command would receive
     * @param {Number} result 0 - command success, 1 - command error
     * @param {Object} error error object if any
     */
     afterCommand: function (commandName, args, result, error) {
//something
     },

```

Did I miss something ?

Thx

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

The PR #4853 caused a regression with async test execution. This patch fixes it and adds smoke tests for async test runner execution.

closes #4849

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-utils/src/shim.js [hunk 1]
```diff
@@ -53,24 +54,36 @@ let runFnInFiberContext = function (fn) {
...
 }
 
-let wrapCommand = async function (commandName, fn, ...args) {
-    await executeHooksWithArgs.call(this, this.options.beforeCommand, [commandName, args])
+let wrapCommand = function wrapCommand (commandName, fn) {
+    return async function wrapCommandFn (...args) {
+        const beforeHookArgs = [commandName, args]
+        if (!inCommandHook) {
+            inCommandHook = true
+            await executeHooksWithArgs.call(this, this.options.beforeCommand, beforeHookArgs).catch((err) => err)
```
Comment (mgrybyk) [inline packages/wdio-utils/src/shim.js]: Are you sure we need to catch error? Shouldn't  executeHooksWithArgs catch all errors for us?

**Comment by mgrybyk** [comment]
LGTM, let's wait for tests to pass
