### PR TITLE
fix(webdriverio): support opening file urls

### LINKED ISSUE #13956: [🐛 Bug]: Timeout when opening url 'file://'
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.4.1

### Node.js Version

v20.11.1

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
}
```

### What happened?

A simple test timed out loading the URL file://
```
describe('example', () => {
    it('load page', async () => {
        await browser.url('file:///Some/valid/path/test.html');
    });
});
```

```
------------------------------------------------------------------
[chrome 131.0.6778.109 mac #0-0] Running: chrome (v131.0.6778.109) on mac
[chrome 131.0.6778.109 mac #0-0] Session ID: 43ae91a4726d6ec62ea3c108d9225aec
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] » /simple.ts
[chrome 131.0.6778.109 mac #0-0] example
[chrome 131.0.6778.109 mac #0-0]    ✖ load page
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] 1 failing (5s)
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] 1) example load page
[chrome 131.0.6778.109 mac #0-0] Error: waitUntil condition timed out after 5000ms
```

### What is your expected behavior?

To succeed and not timeout. 

### How to reproduce the bug.

Uploading a simple example. 
[simple.zip](https://github.com/user-attachments/files/18045334/simple.zip)
```
npm I
npm run test-simple
```

### Relevant log output

```typescript
------------------------------------------------------------------
[chrome 131.0.6778.109 mac #0-0] Running: chrome (v131.0.6778.109) on mac
[chrome 131.0.6778.109 mac #0-0] Session ID: 43ae91a4726d6ec62ea3c108d9225aec
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] » /simple.ts
[chrome 131.0.6778.109 mac #0-0] example
[chrome 131.0.6778.109 mac #0-0]    ✖ load page
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] 1 failing (5s)
[chrome 131.0.6778.109 mac #0-0]
[chrome 131.0.6778.109 mac #0-0] 1) example load page
[chrome 131.0.6778.109 mac #0-0] Error: waitUntil condition timed out after 5000ms

If I change the code to: await browser.url('file:///Some/valid/path/test.html').catch(console.error);
Then I see:

[0-0] Error: waitUntil condition timed out after 5000ms
[0-0]     at <anonymous> (.../simple-file/node_modules/webdriverio/build/index.js:4924:13)
[0-0]     at Browser.wrapCommandFn (.../simple-file/node_modules/@wdio/utils/build/index.js:884:23)
[0-0]     at Browser.url3 (.../simple-file/node_modules/webdriverio/build/index.js:4885:21)
[0-0]     at Browser.wrapCommandFn (.../simple-file/node_modules/@wdio/utils/build/index.js:884:23)
[0-0]     at UserContext.<anonymous> (.../simple-file/simple.ts:4:9)
[0-0]     at UserContext.executeAsync (.../simple-file/node_modules/@wdio/utils/build/index.js:1004:20)
[0-0]     at UserContext.testFrameworkFnWrapper (.../simple-file/node_modules/@wdio/utils/build/index.js:1075:14)
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #13956

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### CODE REVIEW

File: packages/webdriverio/src/networkManager.ts [hunk 1]
```diff
@@ -103,7 +104,7 @@ export class NetworkManager {
             /**
              * ignore urls that do not start with http
```
Comment (Delta456) [inline packages/webdriverio/src/networkManager.ts:105]: The comment needs to be updated too

File: packages/webdriverio/src/networkManager.ts [hunk 2]
```diff
@@ -101,9 +102,9 @@ export class NetworkManager {
              */
             !log.navigation ||
             /**
-             * ignore urls that do not start with http
+             * ignore urls that users wouldn't navigate to
              */
-            !log.url.startsWith('http')
+            !SUPPORTED_NAVIGATION_PROTOCOLS.some((protocol) => log.url.startsWith(protocol))
```
Comment (damencho) [inline packages/webdriverio/src/networkManager.ts:107]: ❤️
