### PR TITLE
Fix browser session close in watch mode

### LINKED ISSUE #3919: Watch command doesn't close the sessions properly
If I run the `--watch` mode and I ctrl+c to end the sessions, it doesn't properly end them.

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Currently sessions are not closed in watch mode on termination. This PR fixes it.
Tested in regular and multiremote modes. 

Fixes #3919

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments

**flow**
1. spec execution started
2. spec execution finished, child process killed, browser object no longer exists 
3. watcher is waiting for changes...
4. SIGINT

_then..._

**previous flow**
5. no attempt to call endSession because worker is marked as not busy. Even if it was, browser object doesn't exist so there is no way to interact with session.

**new flow**
5. endSession triggered, attached to session, deleted session. In multiremote mode things are a bit more complex because it is necessary to attach to every instance.

### CODE REVIEW

File: packages/wdio-cli/src/launcher.js [hunk 1]
```diff
@@ -97,40 +97,51 @@ class Launcher {
...
+        if (!caps || (!this.isMultiremote && !caps.length)) {
             return new Promise((resolve) => {
                 log.error('Missing capabilities, exiting with failure')
                 this.interface.updateView()
                 return resolve(1)
             })
         }
 
+        /**
+         * avoid retries in multiremote mode
```
Comment (CrispusDH) [inline packages/wdio-cli/src/launcher.js]: It might be a typo. Below you check watch mode instead of multiremote

Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: Yeah, typo in comment, thank you

Comment (mgrybyk) [reply packages/wdio-cli/src/launcher.js]: @CrispusDH fixed

**Comment by christian-bromann** [comment]
Can we remove the commits from PR #3958?

**Comment by mgrybyk** [comment]
@christian-bromann do you mean changes? If yes - we can't because this PR relies on Multiremote mode fix.

**Comment by christian-bromann** [comment]
@mgrybyk can you rebase this branch on top of master?

**Comment by mgrybyk** [comment]
let's merge logging first, I'll rebase after

**Comment by mgrybyk** [comment]
playing around with rebase, please ignore for now!

**Comment by mgrybyk** [comment]
Sorry, got some failures with rebase, fixed now.

**Comment by christian-bromann** [comment]
@mgrybyk seems that there are still some conflicts

**Comment by mgrybyk** [comment]
These are new, resolving

**Comment by mgrybyk** [comment]
@christian-bromann resolved conflicts
