### PR TITLE
fix(webdriver): Fix no retrying requests when unexpected token on responses occurs (like on HTML responses)

### LINKED ISSUE #14759: [🐛 Bug]: Unexpected token on failing request with HTML response. Is not retrying the request
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.19.2

### Node.js Version

22.18.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    browserName: 'chrome'
}
```

### What happened?

Running tests using our Selenium server, which is behind a nginx server, sometimes we are getting HTTP 504 Gateway time-out error. And as that kind of errors by default are replied with an HTML page with the error itself, is causing another error on WebdriverIO while parsing the response:

Unexpected token '<', "<html>
<he"... is not valid JSON when running

That errors avoids the retry system, causing the entire test fail.

### What is your expected behavior?

The request should be retried as it happens with other request failures

### How to reproduce the bug.

Is a private server so I can grant anyone access, by it should be easily to reproduce with a simple mock, as the one purposed here: https://github.com/webdriverio/webdriverio/issues/2521#issuecomment-2759749772

### Relevant log output

```typescript
Unexpected token '<', "<html>
<he"... is not valid JSON when running
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by Nyaran**
Fixes #14759

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriver/src/request/request.ts [hunk 1]
```diff
@@ -138,9 +138,17 @@ export abstract class WebDriverRequest {
                 ...(dispatcher ? { dispatcher } : {})
             })
 
+            const rawBody = await response.text()
+            let body
+            try {
+                body = rawBody ? JSON.parse(rawBody) : {}
+            } catch {
+                body = rawBody
```
Comment (christian-bromann) [inline packages/webdriver/src/request/request.ts]: Passing along the response as text here isn't much helpful. We should throw a specific error that contains the raw response.

**Review by christian-bromann — CHANGES_REQUESTED** [review]
I don't think we want these responses to not throw. For example: what if the WebDriver server returns a 200 with HTML content. We should ensure the response we get is a valid WebDriver command response.

**Comment by Nyaran** [comment]
I did some changes to throw an error on parse error, and pass the responseCode and raw body to the WebDriverRequestError instance, so the retry mechanism can run
