### PR TITLE
Fixes #6057

### LINKED ISSUE #6057: browser.mock in a new window not working
**Environment:**
 - **WebdriverIO version:** 6.7.1
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** sync
 - **Node.js version:** 10.23.0
 - **NPM version:** 6.14.8
 - **Browser name and version:** Chrome 86.0.4240.111
 - **Platform name and version:** Mac OS Catalina 10.15.7 (19H2)
 - **Additional wdio packages used (if applicable):** @wdio/spec reporter, @wdio/selenium-standalone service

**Config of WebdriverIO**
```javascript
exports.config = 
{
  runner: 'local',
  specs: [ './specs/**test.js' ],
  exclude: [],
  maxInstances: 5,
  capabilities: [ { maxInstances: 5, browserName: 'chrome' } ],
  logLevel: 'warn',
  bail: 180000,
  baseUrl: '',
  waitforTimeout: 25000,
  connectionRetryTimeout: 90000,
  specFileRetries: 0,
  connectionRetryCount: 2,
  // automationProtocol: 'devtools',
  services: [ 'selenium-standalone' ],
  framework: 'mocha',
  specFileRetries: 0,
  reporters: ['spec'],
  mochaOpts: { ui: 'bdd', timeout: 60000 }
}
```

**Describe the bug**
Mocking seems to not work when opening a new tab in the test flow.

**To Reproduce**

```javascript
describe("Mocking", () => {
  it('Should be able to mock in a new tab', () => {
    const mock1 = browser.mock('https://www.rapidtables.com/web/html/**')
    browser.url('https://www.rapidtables.com/web/html/link/html-link-new-window.html')
    browser.$('//a[contains(text(),"Open page in new window")]').click()
    browser.waitUntil(() => (browser.getWindowHandles()).length > 1);
    browser.switchToWindow(browser.getWindowHandles()[1]);
    const mock2 = browser.mock('https://www.rapidtables.com/web/html/**')
    browser.pause(2000)
    browser.refresh()
    browser.pause(2000)
    console.warn(mock1.calls.length);
    console.warn(mock2.calls.length);
  });
});
```

```
Execution of 1 spec files started at 2020-10-30T20:58:20.692Z

[0-0] RUNNING in chrome - /specs/mock_test.js
[0-0] 1
[0-0] 0
[0-0] PASSED in chrome - /specs/mock_test.js
```

**Expected behavior**
Should be able to mock in the new tab after the page is refreshed.

**Additional context**
It seems like we are always getting the first page [here](https://github.com/webdriverio/webdriverio/blob/d064e3175a915fdc74507cbfaf561c67602c5a0d/packages/webdriverio/src/commands/browser/mock.ts#L116)

### PR DESCRIPTION
**Pull request by vmelikyan**
## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

### CODE REVIEW

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Can we add unit tests for this?

File: packages/webdriverio/src/commands/browser/mock.ts [hunk 1]
```diff
@@ -100,34 +100,36 @@ import DevtoolsNetworkInterception from '../../utils/interception/devtools'
...
+        await pages.forEach(async (page: any) => {
+            const client = await page.target().createCDPSession()
+            client.send('Fetch.enable', {
+                patterns: [{ requestStage: 'Request' }, { requestStage: 'Response' }]
+            })
+            client.on(
+                'Fetch.requestPaused',
+                (NetworkInterception as unknown as typeof DevtoolsNetworkInterception)
+                    .handleRequestInterception(client, SESSION_MOCKS.get(windowHandle)!)
+            )
```
Comment (christian-bromann) [inline packages/webdriverio/src/commands/browser/mock.ts:127]: Should we make sure that we don't register this twice for a page?

File: packages/webdriverio/src/commands/browser/mock.ts [hunk 2]
```diff
@@ -100,34 +100,36 @@ import DevtoolsNetworkInterception from '../../utils/interception/devtools'
...
+    const windowHandle: string = await browser.getWindowHandle()
     /**
      * enable network Mocking if not already
      */
-    if (SESSION_MOCKS.size === 0 && !this.isSauce) {
-        const [page] = await this.puppeteer.pages()
-        const client = await page.target().createCDPSession()
-        await client.send('Fetch.enable', {
-            patterns: [{ requestStage: 'Request' }, { requestStage: 'Response' }]
+    if (!SESSION_MOCKS.has(windowHandle) && !this.isSauce) {
```
Comment (mgrybyk) [inline packages/webdriverio/src/commands/browser/mock.ts:115]: I'd better always define a Set per window and check is it empty like https://github.com/webdriverio/webdriverio/compare/mock-multi-window#diff-03e7544b40f7605d80b9c64844538cd8a50ccfdddf92b3c452f30b5fe43bb78eR114

I think this is what @christian-bromann is asking for

File: packages/webdriverio/src/commands/browser/mock.ts [hunk 3]
```diff
@@ -100,34 +100,36 @@ import DevtoolsNetworkInterception from '../../utils/interception/devtools'
...
+        SESSION_MOCKS.set(windowHandle, new Set())
+        const pages = await this.puppeteer.pages()
+        await pages.forEach(async (page: any) => {
```
Comment (mgrybyk) [inline packages/webdriverio/src/commands/browser/mock.ts:118]: I'd define mocks per page rather than have a mock for all pages.
It's impossible to identify where does request come from

**Review by mgrybyk — CHANGES_REQUESTED** [review]

**Comment by vmelikyan** [comment]
Thanks for the feedback. I'll try to fix it over the weekend.

**Comment by christian-bromann** [comment]
@vmelikyan is there anything I can do to help land this?

**Comment by vmelikyan** [comment]
@christian-bromann I've copied over @mgrybyk's solution and updated the test.

**Comment by vmelikyan** [comment]
_Side note:_ Is it really needed to run the unit tests along with `test:eslint test:typings test:coverage` on all platforms? E.g. `linux 10.x, 12.x, 14.x`, `windows` and `macos`

**Review by christian-bromann — APPROVED** [review]
This looks good to me 👍 

@mgrybyk thoughts?

**Comment by christian-bromann** [comment]
> _Side note:_ Is it really needed to run the unit tests along with `test:eslint test:typings test:coverage` on multiple platforms? E.g. `linux 10.x, 12.x, 14.x`, `windows` and `macos`

Yes. We test on different Node.js versions to ensure that e.g. dependencies are still supported for the range of Node.js versions WebdriverIO is suppose to support. And then we test on different OS platforms to ensure that if someone with a Windows machine wants to contribute to WebdriverIO doesn't see any failing tests which often occur if you assert paths (`/` vs `\\`).

**Review by mgrybyk — APPROVED** [review]
