### PR TITLE
wdio-devtools-service: better browser name and version check

### LINKED ISSUE #4589: Devtools: Unable to run performance test
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.12
 - **Mode:** WDIO Testrunner
 - **If WDIO Testrunner, running sync/async:** Sync
 - **Node.js version:** v10.16.2
 - **NPM version:** v6.11.3
 - **Browser name and version:** Chrome 77 ran through Browserstack
 - **Platform name and version:** Windows 10
 - **Additional wdio packages used (if applicable):** @wdio/devtools-service

**Config of WebdriverIO**
```
exports.config = {
   user: bstack_user,
   key: bstack_password,
   updateJob: false,
    maxInstances: 1,
    specs: [
        './tests/partner_portal/**/policy_secondary_*.spec.js'
    ],
capabilities: [{
        'os': 'Windows',
        'os_version': '10',
        'browserName': 'Chrome',
        'browser_version': '77.0',
        build: 'partner_portal-test',
        'project': 'Partner_Portal',
        acceptInsecureCerts: true,
        'browserstack.local': true,
        resolution: '1920x1080'
    }],
services: [
        'devtools'
    ],
logLevel: 'warn',
    coloredLogs: true,
    screenshotPath: './errorShots/',
    baseUrl: partnerURL,
    waitforTimeout: 20000,
    connectionRetryTimeout: 10000,
    host: 'hub.browserstack.com',
    framework: 'mocha',
    mochaOpts: {
        ui: 'bdd',
        timeout: 100000,
        compilers: ['@babel/register']
    },
    before: function () {
        var chai = require('chai');
        global.expect = chai.expect;
        chai.Should();
    },
    onPrepare: function (config, capabilities) {
        console.log("Connecting local");
        return new Promise(function (resolve, reject) {
            exports.bs_local = new browserstack.Local();
            exports.bs_local.start({
                'key': exports.config.key
            }, function (error) {
                if (error) return reject(error);
                console.log('Connected. Now testing...');

                resolve();
            });
        });
    },
    // Code to stop browserstack local after end of test
    onComplete: function () {
        exports.bs_local.stop(function () {});
    }
}
}
```

**Describe the bug**
`The @wdio/devtools-service currently only supports Chrome version 63 and up`

I receive this error even with browserstack capabilities set to Chrome 77.

**To Reproduce**
Please see below example performance file

```
describe('Testing the partner portal\'s initial paint time', () => {
    before(function() {
        browser.enablePerformanceAudits();
    });

    after(function() {
        browser.disablePerformanceAudits()
    });

    it('Should load within performance constraints that will be set at a later point in time', () => {
        browser.url(url);
        let metrics = browser.getMetrics();
        assert.ok(metrics.speedIndex < 1500);

        let score = browser.getPerformanceScore();
        console.log(score);

        $('#AgencyCode').setValue(partner.PARTNER_PORTAL_AGENCY_CODE);
        $('#frmRouter > div > div > div > div:nth-child(2) > div > input:nth-child(2)').click();

        metrics = browser.getMetrics()
        assert.ok(metrics.speedIndex < 1500)
        score = browser.getPerformanceScore()
        assert.ok(score >= .99)
    });
});
```

**Expected behavior**
According to the docs this should run as long as 'devtools' is added to services array

**Log**
```
Connecting local
Connected. Now testing...
[0-0] RUNNING in Chrome - C:\Users\xxx\Desktop\projects\webdriver-xxx-test\performance\partner_perf.js
[0-0] 2019-10-08T17:36:07.714Z **ERROR @wdio/devtools-service: The @wdio/devtools-service currently only supports Chrome version 63 and up**
[0-0] initialised custom reporter with the following reporter options: { logLevel: 'warn',
  setLogFile: [Function: NOOP],
  someOption: 'foobar',
  logFile: undefined,
  writeStream: { write: [Function: write] } }
Some log line
[0-0] We are beginning the test!
[0-0] TypeError in "Testing the partner portal's initial paint time "before all" hook for "Should load within performance constraints that will be set at a later point in time""
browser.enablePerformanceAudits is not a function
[0-0] We've completed the suite!
[0-0] TypeError in "Testing the partner portal's initial paint time "after all" hook for "Should load within performance constraints that will be set at a later point in time""
browser.disablePerformanceAudits is not a function
```

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Tune supporter version verification to be case insensitive and also support other possible version property names

fixes #4589

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: packages/wdio-devtools-service/src/utils.js [hunk 1]
```diff
@@ -128,3 +128,14 @@ export function quantileAtValue (median, falloff, value) {
...
     return (1 - internalErf_(standardizedX)) / 2
 }
+
+/**
+ * check if browser version is lower than `minVersion`
+ * @param {object} caps capabilities
+ * @param {number} minVersion minimal chrome browser version
+ */
+export function isBrowserVersionLower(caps, minVersion) {
+    const versionProps = ['browserVersion', 'browser_version', 'version']
```
Comment (christian-bromann) [inline packages/wdio-devtools-service/src/utils.js]: We can move this up to the top of the file?

File: packages/wdio-devtools-service/src/utils.js [hunk 2]
```diff
@@ -128,3 +128,14 @@ export function quantileAtValue (median, falloff, value) {
...
+    const browserVersion = caps[versionProps.find(prop => caps[prop])]
+    return typeof browserVersion === 'number' && browserVersion < minVersion
```
Comment (christian-bromann) [inline packages/wdio-devtools-service/src/utils.js]: What if someone has a browser version like `65.1.234.2`?

Comment (mgrybyk) [reply packages/wdio-devtools-service/src/utils.js]: Missed that!

File: packages/wdio-devtools-service/src/utils.js [hunk 3]
```diff
@@ -128,3 +129,27 @@ export function quantileAtValue (median, falloff, value) {
...
     return (1 - internalErf_(standardizedX)) / 2
 }
+
+/**
+ * check if browser version is lower than `minVersion`
+ * @param {object} caps capabilities
+ * @param {number} minVersion minimal chrome browser version
+ */
+export function isBrowserVersionLower (caps, minVersion) {
+    const browserVersion = getChromeMajorVersion(caps[VERSION_PROPS.find(prop => caps[prop])])
```
Comment (christian-bromann) [inline packages/wdio-devtools-service/src/utils.js]:
```suggestion
    const chromeVersion = caps[VERSION_PROPS.find(prop => caps[prop])]
    
    if (!chromeVersion) {
        log.warn('No Chrome version can be detected in the capabilities')
        return true
    }
    
    const browserVersion = getChromeMajorVersion(chromeVersion)
```

**Comment by mgrybyk** [comment]
> Let's add this check in case no browser version is provided.

There is such case already or I'm missing something

File: packages/wdio-devtools-service/src/utils.js (hunk 3 above)
Comment (mgrybyk) [reply packages/wdio-devtools-service/src/utils.js]: I don't think we need to warn that no browser version is provided, it's not mandatory

Comment (christian-bromann) [reply packages/wdio-devtools-service/src/utils.js]: you right

Comment (mgrybyk) [reply packages/wdio-devtools-service/src/utils.js]: the function returns false if there is no version provided OR browser version is above 63.

otherwise it returns `true`.

**Comment by mgrybyk** [comment]
argh, missed to rename `browserVersion` to `chromeVersion`.

Shall I raise a PR for it or let's just keep it as is?

**Comment by christian-bromann** [comment]
I think it is fine. I hope the service can be used by other browsers soon too.
