### PR TITLE
(@wdio/shared-store-service): support multiremote

### LINKED ISSUE #10729: [🐛 Bug]: @wdio/shared-store-service not working in multi-remote
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7

### Node.js Version

16

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
    userA: {
      capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:loggingPrefs': { browser: 'ALL' },
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--window-size=1440,800', '--enable-logging-info']
        }
      },
      baseUrl: process.env.CRM_FRONTEND_E2E_BASEURL
    },
    userB: {
      capabilities: {
        browserName: 'chrome',
        acceptInsecureCerts: true,
        'goog:chromeOptions': {
          args: ['--disable-gpu', '--window-size=1440,800']
        }
      },
      baseUrl: process.env.WEBSHOP_FRONTEND_E2E_BASEURL
    }
  },
```

### What happened?

Running test with multi-remote causes the code in launcher to break on `forEach`, as capabilities is in this case an object with `userA`, `userB` (see above config). 
```typescript
        capabilities.forEach((capability) => {
            capability['wdio:sharedStoreServicePort'] = port
        })
```
I did experiment a bit and got the code working for set and get, but it always returns 'value,value' to me. Which I think is caused by the two browser objects. 

### What is your expected behavior?

Either the capabilities in the onPrepare hook should really be the capabilities (not the two browsers). or there should be some code to handle the two browser objects in get down into their capabilities.

At the end of the day, I want the shared-store-service to work with multiple browsers, because that's what it is there for, right? 

### How to reproduce the bug.

I will try to set something up, if you are not able to reproduce this yourselfes.

### Relevant log output

```typescript
TypeError: capabilities.forEach is not a function
    at SharedStoreLauncher.onPrepare (...\e2e-tests\node_modules\@wdio\shared-store-service\build\launcher.js:16:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ...\e2e-tests\node_modules\@wdio\cli\build\utils.js:38:17
    at async Promise.all (index 1)
    at async Launcher.run (...\e2e-tests\node_modules\@wdio\cli\build\launcher.js:86:13)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #10729

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

n/a

### CODE REVIEW

File: packages/wdio-shared-store-service/src/launcher.ts [hunk 1]
```diff
@@ -1,27 +1,47 @@
...
+            const multiremote = c as Capabilities.MultiRemoteCapabilities
+            if (!multiremote.browserName && multiremote[Object.keys(multiremote)[0]].capabilities) {
+                return Object.values(multiremote).map((options) =>
+                    (options.capabilities as Capabilities.W3CCapabilities)?.alwaysMatch ||
+                    (options.capabilities as Capabilities.Capabilities)
+                )
+            }
+
+            const w3cCaps = c as Capabilities.W3CCapabilities
+            if (w3cCaps.alwaysMatch) {
```
Comment (erwinheitzman) [inline packages/wdio-shared-store-service/src/launcher.ts:38]: I little bit cleaner would be
```suggestion
            return w3cCaps.alwaysMatch || c as Capabilities.Capabilities
```

**Review by erwinheitzman — APPROVED** [review]
LGTM nice one! 👍 

Approved with a small suggestion
