### PR TITLE
[Bug]: Execution steps are missing in allure reports. 

### LINKED ISSUE #10912: [🐛 Bug]: <Execution steps are missing in allure reports>
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.14.0

### Node.js Version

18.17.0

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
browserName: chrome,
browserVersion: "stable",
acceptInsecureCerts: true,

"goog:chromeOptions": {
            "args": ["user-agent=gcp-automation-test (Windows NT)",
                `${process.env.HEADLESS === 'true' ? '--headless' : undefined}`,
                `${process.env.HEADLESS === 'true' ? '--window-size=1920,1080' : undefined}`
            ]
        },
```

### What happened?

Allure report only capturing few steps when disableWebdriverStepsReporting: false

image

### What is your expected behavior?

It should show all the steps like how it used to be with v7
image

### How to reproduce the bug.

npx wdio run ./wdio.conf.ts --spec D:\Project\merx-shopify-automation\src\specs\bvt\orderConfirmationPage.test.ts --mochaOpts.grep "Verify place order through Afterpay"

### Relevant log output

```typescript
Terminal logs showing all the logs as expected.

[0-0] 2023-08-10T17:54:18.348Z INFO webdriver: RESULT []
[0-0] 2023-08-10T17:54:18.816Z INFO webdriver: COMMAND findElements("xpath", "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']")
[0-0] 2023-08-10T17:54:18.816Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:18.816Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']"
[0-0] }
[0-0] 2023-08-10T17:54:18.830Z INFO webdriver: RESULT []
[0-0] 2023-08-10T17:54:19.320Z INFO webdriver: COMMAND findElements("xpath", "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']")
[0-0] 2023-08-10T17:54:19.320Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:19.320Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']"
[0-0] }
[0-0] 2023-08-10T17:54:19.347Z INFO webdriver: RESULT []
[0-0] 2023-08-10T17:54:19.812Z INFO webdriver: COMMAND findElements("xpath", "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']")
[0-0] 2023-08-10T17:54:19.812Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:19.812Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//button[@aria-label='Filter & Sort' or @aria-label='Show Filters']"
[0-0] }
[0-0] 2023-08-10T17:54:19.825Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_58'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:19.830Z INFO webdriver: RESULT WebdriverIO.Element<undefined>
[0-0] 2023-08-10T17:54:19.830Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(text(), 'Loading')]")
[0-0] 2023-08-10T17:54:19.831Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:19.831Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(text(), 'Loading')]" }
[0-0] 2023-08-10T17:54:19.846Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0] }
[0-0] 2023-08-10T17:54:19.848Z INFO webdriver: COMMAND waitForElementNotDisplayed(<object>, 60000)
[0-0] 2023-08-10T17:54:19.848Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:19.848Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:19.848Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:19.865Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:20.363Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:20.363Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:20.363Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:20.392Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:20.854Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:20.855Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:20.855Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:20.886Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:21.348Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:21.348Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:21.348Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:21.360Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:21.852Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:21.852Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:21.852Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:21.870Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:22.358Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:22.359Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:22.359Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:22.379Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:22.850Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:22.851Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:22.851Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:22.867Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:23.361Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:23.361Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:23.361Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_59',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_59'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:23.375Z WARN webdriver: Request encountered a stale element - terminating request
[0-0] 2023-08-10T17:54:23.376Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(text(), 'Loading')]")
[0-0] 2023-08-10T17:54:23.376Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:23.376Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(text(), 'Loading')]" }
[0-0] 2023-08-10T17:54:23.384Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(), 'Loading')]"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:23.388Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(text(), 'Loading')]")
[0-0] 2023-08-10T17:54:23.388Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:23.388Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(text(), 'Loading')]" }
[0-0] 2023-08-10T17:54:23.398Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(text(), 'Loading')]"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:23.400Z INFO webdriver: RESULT WebdriverIO.Element<undefined>
[0-0] 2023-08-10T17:54:23.400Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.400Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.400Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.412Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.431Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.431Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.431Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.432Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.432Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.432Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.469Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.494Z INFO webdriver: COMMAND waitForElementsToBeMinimumArrayOfSize(<object>, 1, 60000)
[0-0] 2023-08-10T17:54:23.495Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.496Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.496Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.502Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.551Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.568Z INFO webdriver: RESULT undefined
[0-0] 2023-08-10T17:54:23.568Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.569Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.569Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.580Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.598Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:23.598Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:23.598Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:23.607Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:23.623Z INFO webdriver: COMMAND getElementRect("4A2C56C09769C1C2AB38421EBECFBBE1_element_73")
[0-0] 2023-08-10T17:54:23.624Z INFO webdriver: [GET] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element/4A2C56C09769C1C2AB38421EBECFBBE1_element_73/rect
[0-0] 2023-08-10T17:54:23.631Z INFO webdriver: RESULT { height: 421, width: 421, x: 72, y: 515.8375244140625 }
[0-0] 2023-08-10T17:54:23.631Z INFO webdriver: COMMAND getWindowRect()
[0-0] 2023-08-10T17:54:23.632Z INFO webdriver: [GET] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/window/rect
[0-0] 2023-08-10T17:54:23.634Z INFO webdriver: RESULT { height: 832, width: 1552, x: -8, y: -8 }
[0-0] 2023-08-10T17:54:23.634Z INFO webdriver: COMMAND executeScript("return (() => [
[0-0]         window.scrollX, window.scrollY
[0-0]     ]).apply(null, arguments)", <object>)
[0-0] 2023-08-10T17:54:23.634Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:23.634Z INFO webdriver: DATA {
[0-0]   script: 'return (() => [\n' +
[0-0]     '        window.scrollX, window.scrollY\n' +
[0-0]     '    ]).apply(null, arguments)',
[0-0]   args: []
[0-0] }
[0-0] 2023-08-10T17:54:23.640Z INFO webdriver: RESULT [ 0, 0 ]
[0-0] 2023-08-10T17:54:23.641Z INFO webdriver: COMMAND performActions(<object>)
[0-0] 2023-08-10T17:54:23.642Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/actions
[0-0] 2023-08-10T17:54:23.642Z INFO webdriver: DATA {
[0-0]   actions: [
[0-0]     { id: 'action2', type: 'wheel', parameters: {}, actions: [Array] }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:24.710Z INFO webdriver: RESULT null
[0-0] 2023-08-10T17:54:24.711Z INFO webdriver: COMMAND releaseActions()
[0-0] 2023-08-10T17:54:24.711Z INFO webdriver: [DELETE] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/actions
[0-0] 2023-08-10T17:54:24.713Z INFO webdriver: RESULT null
[0-0] 2023-08-10T17:54:24.714Z INFO webdriver: COMMAND findElements("xpath", "//div[contains(@class, 'product-tile_container')]/div/a")
[0-0] 2023-08-10T17:54:24.714Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/elements
[0-0] 2023-08-10T17:54:24.714Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class, 'product-tile_container')]/div/a"
[0-0] }
[0-0] 2023-08-10T17:54:24.725Z INFO webdriver: RESULT [
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_73'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_74'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_75'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_76'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_77'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_78'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_79'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_80'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_81'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_82'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_83'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_84'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_85'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_86'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_87'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_88'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_89'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_90'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_91'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_92'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_93'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_94'
[0-0]   },
[0-0]   {
[0-0]     'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_95'
[0-0]   }
[0-0] ]
[0-0] 2023-08-10T17:54:24.741Z INFO webdriver: COMMAND elementClick("4A2C56C09769C1C2AB38421EBECFBBE1_element_73")
[0-0] 2023-08-10T17:54:24.742Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element/4A2C56C09769C1C2AB38421EBECFBBE1_element_73/click
[0-0] 2023-08-10T17:54:24.806Z INFO webdriver: RESULT null
[0-0] 2023-08-10T17:54:24.806Z INFO webdriver: COMMAND waitForPageToLoad(60000)
[0-0] 2023-08-10T17:54:24.808Z INFO webdriver: COMMAND executeScript("return (() => document.readyState === 'complete').apply(null, arguments)", <object>)
[0-0] 2023-08-10T17:54:24.809Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:24.810Z INFO webdriver: DATA {
[0-0]   script: "return (() => document.readyState === 'complete').apply(null, arguments)",
[0-0]   args: []
[0-0] }
[0-0] 2023-08-10T17:54:24.815Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:24.816Z INFO webdriver: COMMAND executeScript("return (() => document.readyState === 'interactive').apply(null, arguments)", <object>)        
[0-0] 2023-08-10T17:54:24.816Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:24.816Z INFO webdriver: DATA {
[0-0]   script: "return (() => document.readyState === 'interactive').apply(null, arguments)",
[0-0]   args: []
[0-0] }
[0-0] 2023-08-10T17:54:24.821Z INFO webdriver: RESULT false
[0-0] 2023-08-10T17:54:24.822Z INFO webdriver: RESULT undefined
[0-0] 2023-08-10T17:54:24.822Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:24.822Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:24.822Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:24.837Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@id,'pdp-cta')]/button"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:24.842Z INFO webdriver: COMMAND waitForElementDisplayed(<object>, 30000)
[0-0] 2023-08-10T17:54:24.843Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:24.843Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:24.843Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:24.849Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@id,'pdp-cta')]/button"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:25.356Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:25.356Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:25.356Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:25.365Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@id,'pdp-cta')]/button"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:25.851Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:25.852Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:25.852Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:25.869Z INFO webdriver: RESULT {
[0-0]   error: 'no such element',
[0-0]   message: `no such element: Unable to locate element: {"method":"xpath","selector":"//div[contains(@id,'pdp-cta')]/button"}\n` +
[0-0]     '  (Session info: chrome=115.0.5790.170)',
[0-0]   stacktrace: 'Backtrace:\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706244A62+57106]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061BCF52]\n' +
[0-0]     '\t(No symbol) [0x00007FF70608E2CB]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C786E]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060C795C]\n' +
[0-0]     '\t(No symbol) [0x00007FF706100477]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E69FF]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060FE522]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060E6793]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BCE81]\n' +
[0-0]     '\t(No symbol) [0x00007FF7060BE064]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7064F4222+2873042]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF706546590+3209792]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF70653F3AF+3180639]\n' +
[0-0]     '\tGetHandleVerifier [0x00007FF7062D5F25+652245]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C8618]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C47C4]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061C48BC]\n' +
[0-0]     '\t(No symbol) [0x00007FF7061B4C33]\n' +
[0-0]     '\tBaseThreadInitThunk [0x00007FFF8CEA26AD+29]\n' +
[0-0]     '\tRtlUserThreadStart [0x00007FFF8DE4AA68+40]\n'
[0-0] }
[0-0] 2023-08-10T17:54:26.347Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:26.348Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:26.348Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:26.377Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_105'
[0-0] }
[0-0] 2023-08-10T17:54:26.380Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:26.381Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:26.381Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_105',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_105'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:26.397Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:26.397Z INFO webdriver: RESULT WebdriverIO.Element<4A2C56C09769C1C2AB38421EBECFBBE1_element_105>
[0-0] 2023-08-10T17:54:26.398Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@class,'product-info_productInfoWrapper')]")
[0-0] 2023-08-10T17:54:26.398Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:26.398Z INFO webdriver: DATA {
[0-0]   using: 'xpath',
[0-0]   value: "//div[contains(@class,'product-info_productInfoWrapper')]"
[0-0] }
[0-0] 2023-08-10T17:54:26.410Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_109'
[0-0] }
[0-0] 2023-08-10T17:54:26.412Z INFO webdriver: COMMAND waitForElementDisplayed(<object>, 30000)
[0-0] 2023-08-10T17:54:26.412Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:26.412Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:26.412Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_109',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_109'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:26.422Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:26.422Z INFO webdriver: RESULT WebdriverIO.Element<4A2C56C09769C1C2AB38421EBECFBBE1_element_109>
[0-0] 2023-08-10T17:54:26.423Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@id,'pdp-cta')]/button")
[0-0] 2023-08-10T17:54:26.424Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:26.424Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@id,'pdp-cta')]/button" }
[0-0] 2023-08-10T17:54:26.433Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_105'
[0-0] }
[0-0] 2023-08-10T17:54:26.437Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:26.438Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:26.438Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_105',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_105'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:26.443Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:26.444Z INFO webdriver: COMMAND findElement("xpath", "//div[contains(@class, 'loader_dots')]")
[0-0] 2023-08-10T17:54:26.444Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/element
[0-0] 2023-08-10T17:54:26.444Z INFO webdriver: DATA { using: 'xpath', value: "//div[contains(@class, 'loader_dots')]" }
[0-0] 2023-08-10T17:54:26.451Z INFO webdriver: RESULT {
[0-0]   'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_110'
[0-0] }
[0-0] 2023-08-10T17:54:26.455Z INFO webdriver: COMMAND waitForElementNotDisplayed(<object>, 60000)
[0-0] 2023-08-10T17:54:26.456Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:26.456Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:26.456Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_110',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_110'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:26.461Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:26.960Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:26.961Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:26.961Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_110',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_110'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:26.970Z INFO webdriver: RESULT true
[0-0] 2023-08-10T17:54:27.469Z INFO webdriver: COMMAND executeScript(<fn>, <object>)
[0-0] 2023-08-10T17:54:27.470Z INFO webdriver: [POST] http://0.0.0.0:58251/session/11f2995ae4f1143f53b45fb4eadb5b65/execute/sync
[0-0] 2023-08-10T17:54:27.470Z INFO webdriver: DATA {
[0-0]   script: 'isElementDisplayed(...) [8007 bytes]',
[0-0]   args: [
[0-0]     {
[0-0]       'element-6066-11e4-a52e-4f735466cecf': '4A2C56C09769C1C2AB38421EBECFBBE1_element_110',
[0-0]       ELEMENT: '4A2C56C09769C1C2AB38421EBECFBBE1_element_110'
[0-0]     }
[0-0]   ]
[0-0] }
[0-0] 2023-08-10T17:54:27.490Z INFO webdriver: RESULT true


No error in terminal logs.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by BorisOsipov**
Sometimes onAfterCommand fires twice in a row causing a broken report. Added a guard to not allow an end step when there are no steps.

fix #10912

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [ ] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
> It is very difficult to understand why tests on CI fail, but this failure seems irrelevant.

I am have been working over the last days to fix the issues but haven't had enough time to get it green  again. I hope to get stuff rolling soon again then I will update this branch.

File: packages/wdio-allure-reporter/src/reporter.ts [hunk 1]
```diff
@@ -503,7 +503,7 @@ export default class AllureReporter extends WDIOReporter {
 
         if (!disableWebdriverStepsReporting) {
             this.attachJSON('Response', commandResult)
-            this._endTest(AllureStatus.PASSED)
+            this.endStep(AllureStatus.PASSED)
```
Comment (christian-bromann) [inline packages/wdio-allure-reporter/src/reporter.ts:506]: I don't see `this.endStep` being defined somewhere 🤔

Comment (BorisOsipov) [reply packages/wdio-allure-reporter/src/reporter.ts:506]: Here https://github.com/webdriverio/webdriverio/blob/3f678588dda3ade709f09bd0631f6b76d32ddaf0/packages/wdio-allure-reporter/src/reporter.ts#L795
