### PR TITLE
Fix/watcher files to watch 14685

### LINKED ISSUE #14685: [🐛 Bug]: <title>
### Have you read the Contributing Guidelines on issues?

- [x] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

9.18.4

### Node.js Version

v24.5.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{ 
 browsername: "google-chrome-stable",
 devcontianer: "ghcr.io/devcontainers/features/node:1:latest"
 platform: "windows11 wsl2"
}
```

### What happened?

When using WebdriverIO's watcher feature (wdio run --watch) with the filesToWatch option configured to monitor changes in application source files, the watcher does not trigger test reruns upon changes in these app files. However, it correctly detects changes in test spec files and reruns tests as expected.

### What is your expected behavior?

I expect the watcher to rerun tests based on app file changes

### How to reproduce the bug.

1. Setup a WDIO configuration (wdio.conf.js) with:
```javascript
specs: ['./**/*.test.js'],
filesToWatch: ['./**/**/*.js'],  // watch for changes in app files
```
2. Ensure a local web server is running to serve your app under test (e.g. via ui5 serve on port 8081).

3. Start the test run with watcher enabled:
```console
wdio run ./path/to/wdio.conf.js --watch
```
4. Modify a test spec file (e.g., unit.test.js). Observe the tests rerun automatically.

5. Modify an app source file matching the filesToWatch glob (e.g., a .js file in the app directory). Observe no test rerun triggered

### Relevant log output

```typescript
Internally, WebdriverIO watcher converts filesToWatch globs to absolute file URIs (e.g., file:///absolute/path/**/*.js), whereas spec files are watched using filesystem paths (e.g., /absolute/path/unit.test.js).

This difference in path format causes chokidar (the file watcher library WDIO uses) to ignore the changes in app files watched through filesToWatch.

The watcher remains active and does not crash or stop responding; it merely does not respond to changes in app files. Still works for spec changes.

Running an external chokidar CLI watcher to manually rerun tests on app file changes is a reliable workaround.

// excerpt from package.json scripts

"serve:ui5": "ui5 serve --port 8081",
"test": "wdio run ./webapp/test/wdio.conf.js",
"test:watch:ready": "wait-on tcp:8081 & npm run test  -- --watch",
"tdd": "run-p serve:ui5 test:watch:ready"
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### PR DESCRIPTION
**Pull request by mccmrunal**
## Proposed changes
Fixes #14685 - The watcher was not triggering test reruns when files configured in filesToWatch were modified.

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
 In 
watcher.ts
, filesToWatch paths were processed using FileSystemPathService.ensureAbsolutePath(), which converts paths to file:// URIs (e.g., file:///path/to/src/**/*.js). However, chokidar (the file watching library) cannot handle file:// URIs correctly for glob patterns.
## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriverio/src/utils/index.ts [hunk 1]
```diff
@@ -317,6 +317,16 @@ export async function findDeepElement(
...
     const { using, value } = findStrategy(selector as string, this.isW3C, this.isMobile)
+
+    /**
+     * if we are using a relative xpath selector and we have a parent element
+     * we need to fall back to the regular WebDriver Classic command as BiDi
+     * does not support relative xpath selectors with a start node
+     */
+    if (using === 'xpath' && (value.startsWith('./') || value.startsWith('..')) && (this as WebdriverIO.Element).elementId) {
+        return this.findElementFromElement((this as WebdriverIO.Element).elementId, using, value)
+    }
```
Comment (christian-bromann) [inline packages/webdriverio/src/utils/index.ts]: I am assuming [`startNodes`](https://www.w3.org/TR/webdriver-bidi/#command-browsingContext-locateNodes) would allow to do that?

Regardless, let's remove this as this patch is unrelated to the original quest of fixing the watcher.

File: packages/webdriverio/src/utils/index.ts [hunk 2]
```diff
@@ -383,6 +393,16 @@ export async function findDeepElements(
...
     )
     const { using, value } = findStrategy(selector as string, this.isW3C, this.isMobile)
+
+    /**
+     * if we are using a relative xpath selector and we have a parent element
+     * we need to fall back to the regular WebDriver Classic command as BiDi
+     * does not support relative xpath selectors with a start node
+     */
+    if (using === 'xpath' && (value.startsWith('./') || value.startsWith('..')) && (this as WebdriverIO.Element).elementId) {
+        return this.findElementsFromElement((this as WebdriverIO.Element).elementId, using, value)
```
Comment (christian-bromann) [inline packages/webdriverio/src/utils/index.ts]: same

Comment (mccmrunal) [reply packages/webdriverio/src/utils/index.ts]: resolved
