### PR TITLE
fix(webdriver): allow BiDiCore to send declared headers

### LINKED ISSUE #13153: [🐛 Bug]: BidiCore does not send headers declared in wdio.conf.js on the upgrade GET request.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.38.2

### Node.js Version

v18.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
{
  browserName: 'chrome',
  webSocketUrl: true,
  acceptInsecureCerts: true,
  'cal:nodeOptions': { debug: true },
  'goog:chromeOptions': {
    extensions: [chromeExtension],
    args: ['--no-sandbox', '--disable-infobars']
  },
}
```

### What happened?

We use CloudFlare to protect internal domains, including the domain for a selenium grid.

We have a header declared in wdio.conf.js to provide `cf-access-token` on all requests made by the driver to the grid.  This has usually worked just fine - it's supported for standard requests, as well as cdp websockets. 

ex: our WDIO config starts with:
```
exports.config = {
  //
  // ====================
  // Runner Configuration
  // ====================
  runner: 'local',
  hostname: 'cf.protected.domain',
  port: 443,
  path: '/wd/hub',
  protocol: 'https',
  headers: {
    'cf-access-token': token,
  }
  ...
```

I have been experimenting with the new Bidi protocol support, and when I run an unprotected selenium grid locally, things work just fine (I am able to connect successfully, calls work as expected).

However when I point at the protected grid, I started encountering 302 errors because the initial upgrade request does not contain the header declared in the conf file, see request captured with BurpSuite:

```
GET /session/eaf58f4c46c0085af16d64833dffd782/se/bidi HTTP/2
Host: cf.protected.domain
Sec-Websocket-Version: 13
Sec-Websocket-Key: VXb45CB2mKTB0Q9Itu73Yw==
Connection: Upgrade
Upgrade: websocket
```

I can manually patch BidiCore and pass the header into the WebSocket constructor here: https://github.com/webdriverio/webdriverio/blob/43868ec82075db90009f00bb737f6df0f1744ca6/packages/webdriver/src/bidi/core.ts#L18 and things work.

```
GET /session/c052b894e06f0d2e24215cba6b1ba7a2/se/bidi HTTP/2
Host: cf.protected.domain
Cf-Access-Token: ABCD...
Sec-Websocket-Version: 13
Sec-Websocket-Key: OJeok1BuGE69MPkIYsEipQ==
Connection: Upgrade
Upgrade: websocket
```

I am not entirely sure if this will cause issues with the folks who are using the `runner: 'browser'` configuration (I don't believe WebSocket accepts a header param in that instance) and I believe Bidi was intended to also support that case?

But as it stands - this was unexpected behavior when I have declared a "header" setting in the config.

### What is your expected behavior?

Headers declared in wdio.conf.js are included in the GET request for Bidi socket upgrades.

### How to reproduce the bug.

Create a wdio.conf.js file that declares a header option:

```
exports.config = {
  //
  // ====================
  // Runner Configuration
  // ====================
  runner: 'local',
  hostname: 'cf.protected.domain',
  port: 443,
  path: '/wd/hub',
  protocol: 'https',
  headers: {
    'cf-access-token': token,
  }
  ...
```

Make a request to a Bidi method 
```
    const sessStatus = await browser.sessionStatus({});
    console.log(sessStatus);
```

Observe that the socket upgrade request does not include the header. 

### Relevant log output

```typescript
[0-0] ----Debug session for chrome----
[0-0] 
[0-0] https://cf.protected.domain
[0-0] 
[0-0] 
[0-0] 2024-07-12T16:36:25.056Z DEBUG @wdio/runner: init remote session
[0-0] 2024-07-12T16:36:25.150Z DEBUG @wdio/runner: init remote session
[0-0] 2024-07-12T16:36:25.151Z INFO webdriver: Initiate new session using the WebDriver protocol
[0-0] 2024-07-12T16:36:25.151Z INFO @wdio/utils: Connecting to existing driver at https://cf.protected.domain:443/wd/hub
[0-0] 2024-07-12T16:36:25.294Z INFO webdriver: [POST] https://cf.protected.domain/wd/hub/session
[0-0] 2024-07-12T16:36:25.294Z INFO webdriver: DATA {
[0-0]   capabilities: {
[0-0]     alwaysMatch: {
[0-0]       browserName: 'chrome',
[0-0]       webSocketUrl: true,
[0-0]       acceptInsecureCerts: true,
[0-0]       'cal:nodeOptions': [Object],
[0-0]       'goog:chromeOptions': [Object]
[0-0]     },
[0-0]     firstMatch: [ {} ]
[0-0]   },
[0-0]   desiredCapabilities: {
[0-0]     browserName: 'chrome',
[0-0]     webSocketUrl: true,
[0-0]     acceptInsecureCerts: true,
[0-0]     'cal:nodeOptions': { debug: true },
[0-0]     'goog:chromeOptions': { extensions: [Array], args: [Array] }
[0-0]   }
[0-0] }
[0-0] RUNNING in chrome - file:///apps/wdio-e2e/src/specs/login.spec.ts
[0-0] 2024-07-12T16:36:30.119Z INFO webdriver: Register BiDi handler for session with id 6bc8d1a963f2eb8f225395327ff8cd68
[0-0] 2024-07-12T16:36:30.119Z INFO webdriver: Connect to webSocketUrl wss://cf.protected.domain/session/6bc8d1a963f2eb8f225395327ff8cd68/se/bidi
[0-0] /Users/n.tinkler/projects/calendly/client-core/node_modules/ws/lib/websocket.js:912
[0-0]       abortHandshake(
[0-0]       ^
[0-0] Error: Unexpected server response: 302
[0-0]     at ClientRequest.<anonymous> (/Users/n.tinkler/projects/calendly/client-core/node_modules/ws/lib/websocket.js:912:7)
[0-0]     at ClientRequest.emit (node:events:513:28)
[0-0]     at ClientRequest.emit (node:domain:489:12)
[0-0]     at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
[0-0]     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
[0-0]     at TLSSocket.socketOnData (node:_http_client:542:22)
[0-0]     at TLSSocket.emit (node:events:513:28)
[0-0]     at TLSSocket.emit (node:domain:489:12)
[0-0]     at addChunk (node:internal/streams/readable:324:12)
[0-0]     at readableAddChunk (node:internal/streams/readable:297:9)
2024-07-12T16:36:30.244Z DEBUG @wdio/local-runner: Runner 0-0 finished with exit code 1
[0-0] FAILED in chrome - file:///apps/wdio-e2e/src/specs/login.spec.ts
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by navin772**
## Proposed changes

Fixes #13153 

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/webdriver/src/bidi/core.ts [hunk 1]
```diff
@@ -27,7 +27,7 @@ export class BidiCore {
     constructor (webSocketUrl: string, opts?: ClientOptions) {
         this.#webSocketUrl = webSocketUrl
         log.info(`Connect to webSocketUrl ${this.#webSocketUrl}`)
-        this.#ws = new environment.value.Socket(this.#webSocketUrl, opts) as unknown as WebSocket
+        this.#ws = new environment.value.Socket(this.#webSocketUrl, { ...opts }) as unknown as WebSocket
```
Comment (erwinheitzman) [inline packages/webdriver/src/bidi/core.ts:30]: Why do we spread this when nothing new is added (spreading it like this only costs extra memory)?

Comment (navin772) [reply packages/webdriver/src/bidi/core.ts:30]: Thanks for pointing that out, didn't knew that! Kind of new to TS.

I will remove it and the other occurrence as well.

**Review by christian-bromann — APPROVED** [review]
LGTM 👍
