### PR TITLE
webdriverio: return promise-wrapped async elements from $/$$ in async mode

### LINKED ISSUE #3760: WebdriverIOAsync findElement(s) signatures have WebdriverIO return types
**Environment (please complete the following information):**
 - **WebdriverIO version:** 5.7.5
 - **Mode:** Standalone

**Describe the bug**

The use of `WrapWithPromise` to generate `WebdriverIOAsync` types from `WebdriverIO` types means that the return types of most methods are correctly typed as Promises rather than the resolved types of those Promises.

However, in the case of `WebdriverIOAsync.Browser.findElement(s)` (or `$` or `$$`), the resolved type is itself an element, but since these method signatures have been generated from `WebdriverIO.Browser`, that element is of type `WebdriverIO.Element`, *not* `WebdriverIOAsync.Element` as it should be.

**To Reproduce**
```
type T = ReturnType<WebdriverIOAsync.Browser["$"]>; // Promise<WebdriverIO.Element>
```

**Expected behavior**
```
type T = ReturnType<WebdriverIOAsync.Browser["$"]>; // Promise<WebdriverIOAsync.Element>
```

So that we can do the following without a type error: 

```
const element = await browser.$("selector");
await element.$("sub-selector").then((subElement) => subElement.click());
```

### PR DESCRIPTION
**Pull request by richsilv**
## Proposed changes

`WebdriverIO.Async` types are updated so that the `$` and `$$` methods on `Element` and `Browser` return one or an array of `WebdriverIOAsync.Element` objects wrapped in a promise, rather than one of an array of `WebdriverIO.Element` objects wrapped in a promise (which is inconsistent with the API).

Resolves #3760 

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

## Further comments

N/A

### CODE REVIEW

**Comment by christian-bromann** [comment]
@richsilv can you please sign the CLA?

File: packages/webdriverio/webdriverio.d.ts [hunk 1]
```diff
@@ -3,21 +3,36 @@
 type BrowserObject = WebDriver.ClientOptions & WebDriver.ClientAsync & WebdriverIOAsync.Browser;
 
 // Element commands that should be wrapper with Promise
-type ElementPromise = Omit<WebdriverIO.Element, 'addCommand'>;
+type ElementPromise = Omit<WebdriverIO.Element, 'addCommand' | '$' | '$$'>;
 
 // Element commands wrapper with Promise
 type ElementAsync = {
     [K in keyof ElementPromise]: WrapWithPromise<ElementPromise[K], ReturnType<ElementPromise[K]>>
+} & {
```
Comment (CrispusDH) [inline packages/webdriverio/webdriverio.d.ts]: could we somehow reduce duplication of this code?

Comment (richsilv) [reply packages/webdriverio/webdriverio.d.ts]: :thumbsup: makes sense. Should I amend the commit, or add another?

Comment (CrispusDH) [reply packages/webdriverio/webdriverio.d.ts]: I think it is up to you. I prefer additional commit :)

Comment (richsilv) [reply packages/webdriverio/webdriverio.d.ts]: as requested

**Comment by christian-bromann** [comment]
@CrispusDH I am not a typescript expert so if you are cool with the change, I will merge it

**Comment by CrispusDH** [comment]
Looks good for me

**Comment by mgrybyk** [comment]
moment, taking a look

File: packages/webdriverio/webdriverio.d.ts [hunk 2]
```diff
@@ -3,22 +3,33 @@
 type BrowserObject = WebDriver.ClientOptions & WebDriver.ClientAsync & WebdriverIOAsync.Browser;
 
 // Element commands that should be wrapper with Promise
-type ElementPromise = Omit<WebdriverIO.Element, 'addCommand'>;
+type ElementPromise = Omit<WebdriverIO.Element, 'addCommand' | '$' | '$$'>;
+
+// Methods which return async element(s) so non-async equivalents cannot just be promise-wrapped
+interface AsyncSelectors {
+    $(
```
Comment (mgrybyk) [inline packages/webdriverio/webdriverio.d.ts]: small suggestion, can we move $ and $$ to types and reuse types in global variables declarations, something like this:
```
type $ = (selector: string | Function) => Promise<WebdriverIOAsync.Element>;
type $$ = (selector: string | Function) => Promise<WebdriverIOAsync.Element[]>;
interface AsyncSelectors {
    $: $;
    $$: $$;
}
```
...
```
declare var browser: BrowserObject;
declare var $: $;
declare var $$: $$;
```

What do you think?

Comment (richsilv) [reply packages/webdriverio/webdriverio.d.ts]: I can see the point of the types, but for my benefit could you explain why these should be declared globally? Are they supposed to be accessible that way?

Comment (christian-bromann) [reply packages/webdriverio/webdriverio.d.ts]: @richsilv if you use the wdio testrunner yes

Comment (richsilv) [reply packages/webdriverio/webdriverio.d.ts]: Makes sense, thanks! I'll make the requested change.

Comment (richsilv) [reply packages/webdriverio/webdriverio.d.ts]: okay, done

**Comment by mgrybyk** [comment]
I think it is required to rebase in order to resolve codecov failure, @richsilv
