### PR TITLE
Speedup Firefox Nightly startup on MacOS with devtools protocol

### LINKED ISSUE #5916: Starting firefox on MacOS takes much time in binary is not specified
**Environment (please complete the following information):**
 - **WebdriverIO version:** 6.5.0
 - **Platform name and version:** MacOS
 - **Additional wdio packages used (if applicable):** devtools

**Config of WebdriverIO**
```js
automationProtocol: 'devtools',
    capabilities: [
        {
            browserName: 'firefox',
        },
    ],
```

**Describe the bug**
it takes more than 5 seconds for finder to find Firefox binary every time 

**To Reproduce**
1. run tests in firefox
2. wait for tests to start

**Expected behavior**
less than a second for sure, ideally less than 100 ms

### PR DESCRIPTION
**Pull request by mgrybyk**
## Proposed changes

Speedup firefox/edge startup on MacOS
fixes #5916

results on my machine:
- before 5.5s
- after 1.5s

If the browser installed to the default location no waiting is required!

## Types of changes

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/master/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

Decided to use JSON format intentionally, ti takes ~300ms less than text and ~100ms less than XML output types.
Sorry to say there are no other reliable ways to get an app installation path on MacOS.

### CODE REVIEW

**Comment by joventuraz** [comment]
This also fixes an issue I encountered after installing firefox through brew cask, where it was not added to Launch Services yet, so the lsregister command returned nothing.

File: packages/devtools/src/launcher.js [hunk 1]
```diff
@@ -134,7 +134,7 @@ function launchBrowser (capabilities, product) {
 
     if (!executablePath) {
         throw new Error('Couldn\'t find executable for browser')
-    } else if (product === BROWSER_TYPE.firefox && !executablePath.toLowerCase().includes(CHANNEL_FIREFOX_NIGHTLY)) {
+    } else if (product === BROWSER_TYPE.firefox && executablePath !== 'firefox' && !executablePath.toLowerCase().includes(CHANNEL_FIREFOX_NIGHTLY)) {
```
Comment (mgrybyk) [inline packages/devtools/src/launcher.js:137]: Some CI platforms disallow accessing binaries by a full path, like `/tmp/34rgew/firefox-nightly/firefox`.
The firefox is added to `PATH` and can be called with `firefox`.

To be able to run tests in CI I'd like to be able to set `binary` to just `firefox`, ex: `binary: process.env.CI ? 'firefox' : undefined,`

**Review by christian-bromann — APPROVED** [review]
👍
