### PR TITLE
fix spec name comparison - fixes #11060

### LINKED ISSUE #11060: [🐛 Bug]: Junit XML report is empty
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.15.9

### Node.js Version

16.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

_No response_

### What happened?

After running the tests, the junit xml report files are empty:
<?xml version="1.0" encoding="UTF-8"?>
<testsuites/>

### What is your expected behavior?

XML files should contain test results

### How to reproduce the bug.

Reading the previous bug report #9352, I can see the same result, still empty.
The resolution of #9352 was to use url.fileURLToPath on the following line;
```
const sameSpecFileName = url.fileURLToPath(specFileName) === suite.file;
```
What I can see on my side (on Windows, using jamsine framework and typescript), is it compares the 2 following strings:
```
"D:\Code\***.ts" === "file:///D:/Code/***.ts"
```
In fact, in my case specFileName and suite.file are both URLs, so doing
```
const sameSpecFileName = specFileName === suite.file;
```
or
```
const sameSpecFileName = url.fileURLToPath(specFileName) === url.fileURLToPath(suite.file);
```
both work on my case.

So #9352 didn't solve the issue in my environment, but introduced a regression.

May be we should check which type of file name is on both side of the comparison (file path or URL). If both have the same type, we can compare them directly, else we should convert the one being an URL into a path using fileURLToPath ?

### Relevant log output

```typescript
no relevant log output
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by lecousin**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)
Fix #11060: compare file names between spec filename and suite filename

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-junit-reporter/src/index.ts [hunk 1]
```diff
@@ -304,6 +304,13 @@ class JunitReporter extends WDIOReporter {
     private _format (val: any) {
         return JSON.stringify(limit(val))
     }
+
+    private _sameFileName(file1: string, file2: string) {
+        // ensure both files are not a file URL
+        file1 = file1 && file1.startsWith('file://') ? url.fileURLToPath(file1) : file1
+        file2 = file2 && file2.startsWith('file://') ? url.fileURLToPath(file2) : file2
```
Comment (christian-bromann) [inline packages/wdio-junit-reporter/src/index.ts:311]: Your type definition for the function suggest that `file1` and `file2` are always a string so none need to check for their existence
```suggestion
        file1 = file1.startsWith('file://') ? url.fileURLToPath(file1) : file1
        file2 = file2.startsWith('file://') ? url.fileURLToPath(file2) : file2
```

**Review by christian-bromann — COMMENTED** [review]
Can we have a test for this?

File: packages/wdio-junit-reporter/src/index.ts (hunk 1 above)
Comment (lecousin) [reply packages/wdio-junit-reporter/src/index.ts:311]: that was my initial code, but the tests failed because in the tests it may be null, so I add the condition to be sure as I conclued that it may introduce a regression where sometimes the filename can be null.

Comment (erwinheitzman) [reply packages/wdio-junit-reporter/src/index.ts:311]: We can use the example?.myProperty  notation here instead

Comment (christian-bromann) [reply packages/wdio-junit-reporter/src/index.ts:311]: I think we should update the test then to confirm with the typing.

Comment (lecousin) [reply packages/wdio-junit-reporter/src/index.ts]: I added the ? in both parameter declaration and usage, and a unit test on the function _sameFileName

**Review by christian-bromann — APPROVED** [review]
LGTM 👍

**Comment by christian-bromann** [comment]
Congratulations @lecousin on your first WebdriverIO contribution 🎉
