### PR TITLE
Fix 'wdio config' in empty directory

### LINKED ISSUE #13771: [🐛 Bug]: 'wdio config' fails in the middle of questionnaire if there was no package.json at CWD
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

v9.2.0

### Node.js Version

v22.6.0

### Mode

Standalone Mode

### Which capabilities are you using?

_No response_

### What happened?

If I run `npx @wdio/cli config` in an empty directory (without `package.json`), the 1st question is if I want the CLI to create one for me. The default answer is Yes and I agree, but then in the middle of questionnaire (after choosing JS testing framework) it fail with exception (see "Relevant log output")

### What is your expected behavior?

_No response_

### How to reproduce the bug.

See "What happened?"

### Relevant log output

```typescript
Error: Could not find project root directory with a package.json
    at getProjectRoot (file:///Users/user/.npm/_npx/c99d4c13e0dee746/node_modules/@wdio/cli/build/index.js:1808:11)
    at async detectCompiler (file:///Users/user/.npm/_npx/c99d4c13e0dee746/node_modules/@wdio/cli/build/index.js:1416:16)
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by gavvvr**
## Proposed changes

Fixes #13771

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-cli/src/utils.ts [hunk 1]
```diff
@@ -531,42 +533,39 @@ export async function getAnswers(yes: boolean): Promise<Questionnair> {
 
     const projectProps = await getProjectProps(process.cwd())
     const isProjectExisting = Boolean(projectProps)
+    const nameInPackageJsonIsNotCreateWdioDefault = projectProps?.packageJson?.name !== 'my-new-project'
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:536]: Where does `my-new-project` come from?

File: packages/wdio-cli/src/utils.ts [hunk 2]
```diff
@@ -358,6 +358,8 @@ export function hasBabelConfig(rootDir: string) {
  * detect if project has a compiler file
  */
 export async function detectCompiler(answers: Questionnair) {
+    if (answers.createPackageJSON) { return false }
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:361]: Are we sure we want to return `false` here? What if ther user wants to use TS in a new project?

File: packages/wdio-cli/src/utils.ts [hunk 3]
```diff
@@ -531,42 +533,39 @@ export async function getAnswers(yes: boolean): Promise<Questionnair> {
...
+            default: true,
+            message: `Couldn't find a package.json in "${process.cwd()}" or any of the parent directories, do you want to create one?`,
+            when: !isProjectExisting
+        },
+        {
+            type: 'confirm',
+            name: 'projectRootCorrect',
+            default: true,
+            message: `A project${projectName} was detected at "${projectProps?.path}", correct?`,
+            when: isProjectExisting && nameInPackageJsonIsNotCreateWdioDefault
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:552]: Can we move `isProjectExisting && nameInPackageJsonIsNotCreateWdioDefault` into a const somewhere above and use it for both of the `when` callbacks?

**Review by christian-bromann — CHANGES_REQUESTED** [review]

File: packages/wdio-cli/src/utils.ts (hunk 1 above)
Comment (gavvvr) [reply packages/wdio-cli/src/utils.ts:536]: @christian-bromann I didn't introduce this behavior, just refactored. Looking through git logs shows that this name [was used by `create-wdio` generator](https://github.com/webdriverio/create-wdio/blob/76a54560b1b71d3b8ebb46270605deb5b28d06c2/src/index.ts#L66-L70) and it got removed in [create-wdio@c3e5fd29b72](https://github.com/webdriverio/create-wdio/commit/c3e5fd29b72675a33701895a95736235295c35b3#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80L69)

File: packages/wdio-cli/src/utils.ts (hunk 2 above)
Comment (gavvvr) [reply packages/wdio-cli/src/utils.ts:361]: @christian-bromann this function is only used for __computing default answer__ to the question: "Do you want to use Typescript to write tests?"

https://github.com/webdriverio/webdriverio/blob/2f9d09151cfb3666c8fe9178326f9f943107ec33/packages/wdio-cli/src/constants.ts#L472-L483

So, by the time `detectCompiler()` is called, there is no answer for `isUsingTypeScript` yet, because `detectCompiler()` gets called right before asking user for `isUsingTypeScript`.

File: packages/wdio-cli/src/utils.ts (hunk 3 above)
Comment (gavvvr) [reply packages/wdio-cli/src/utils.ts:552]: @christian-bromann yes, I can do it. Seems like it won't affect any behavior for now (while `package.json` doesn't get modified somewhere in the middle of running `wdio config`)

Comment (gavvvr) [reply packages/wdio-cli/src/utils.ts:552]: The CI has failed after the change. Unit tests are saying the following about `getProjectProps` in `constants.ts`:

> TypeError: getProjectProps is not a function"

`console.log(getProjectProps)` shows `undefined`. I find it difficult to understand why is that 🤔

Comment (christian-bromann) [reply packages/wdio-cli/src/utils.ts:552]: Note that unit tests may mock out entire packages or even native functions like `fetch`.

File: packages/wdio-cli/src/utils.ts (hunk 2 above)
Comment (christian-bromann) [reply packages/wdio-cli/src/utils.ts:364]: Can we add a comment above the if statement to document this reasoning?

**Comment by christian-bromann** [comment]
@gavvvr anything I can do to help move this forward?

**Comment by gavvvr** [comment]
> @gavvvr anything I can do to help move this forward?

Hi @christian-bromann. Sorry for abandoning this.
I'm out of the context already, but I as I remember I felt some resistance regarding moving `isProjectExisting` && `nameInPackageJsonIsNotCreateWdioDefault` to consts, because it seemed to add to complexity of mocking. Do you still think it's a good idea to move them to consts? If you confirm, I can adjust mocks and finish the PR.

**Comment by christian-bromann** [comment]
> because probably `npm init wdio@latest` should be used on empty directories.

No, it should be possible to use it anywhere, empty directories and existing projects.

I am seeing a lot of `TypeError: getProjectProps is not a function` which tells me that a test probably mocks the file and does't export a mock for this function.

Feel free to schedule a [office hour session](https://webdriver.io/community/openofficehours) if you would like to sync in person.

**Comment by christian-bromann** [comment]
@gavvvr is there anything I can do to help land this fix?

**Comment by gavvvr** [comment]
@christian-bromann I've scheduled one more open office hour right now. The previous one from December was cancelled.

File: packages/wdio-cli/src/utils.ts [hunk 4]
```diff
@@ -358,6 +358,9 @@ export function hasBabelConfig(rootDir: string) {
  * detect if project has a compiler file
  */
 export async function detectCompiler(answers: Questionnair) {
+    // obviously there is no compiler, if there is no package.json
+    if (answers.createPackageJSON) { return false }
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:362]:
```suggestion
    if (answers.createPackageJSON) {
        return false
    }
```

File: packages/wdio-cli/src/utils.ts [hunk 5]
```diff
@@ -533,42 +536,39 @@ export async function getAnswers(yes: boolean): Promise<Questionnair> {
...
+            default: projectProps?.path,
+            // only ask if there are more than 1 runner to pick from
+            when: /* istanbul ignore next */ (answers: Questionnair) => isProjectExisting && nameInPackageJsonIsNotCreateWdioDefault && !answers.projectRootCorrect
+        }
     ]
+
     // @ts-expect-error
-    return inquirer.prompt(questions)
+    const answers = await inquirer.prompt(projectRootQuestions)
+    if (answers.createPackageJSON) { answers.projectRoot = process.cwd() }
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:568]:
```suggestion
    if (answers.createPackageJSON) {
        answers.projectRoot = process.cwd()
    }
```

File: packages/wdio-cli/src/utils.ts [hunk 6]
```diff
@@ -995,6 +995,8 @@ export async function createWDIOConfig(parsedAnswers: ParsedAnswers) {
  * @returns project root path
  */
 export async function getProjectRoot (parsedAnswers?: Questionnair) {
+    if (parsedAnswers?.createPackageJSON && parsedAnswers.projectRoot) { return parsedAnswers.projectRoot }
```
Comment (christian-bromann) [inline packages/wdio-cli/src/utils.ts:998]:
```suggestion
    if (parsedAnswers?.createPackageJSON && parsedAnswers.projectRoot) {
        return parsedAnswers.projectRoot
    }
```

**Review by christian-bromann — APPROVED** [review]
LGTM 👍  thanks so much!

Just flagged some code style thingies that I will resolve myself
