### PR TITLE
bugfix: #6569 only install tagged version if requested spec doesnt match semver

### LINKED ISSUE #6569: wdio config: No matching version found for @wdio/spec-reporter@^7.0.8.
**Environment:**
 - **WebdriverIO version:** 7.1.0
 - **Mode:** N/A
 - **If WDIO Testrunner, running sync/async:** N/A
 - **Node.js version:** 14.15.4
 - **NPM version:** 6.14.10
 - **Browser name and version:** N/A
 - **Platform name and version:** Mac OS 10.15.7
 - **Additional wdio packages used (if applicable):** @wdio/wdio-config, @wdio/spec-reporter

**Config of WebdriverIO**
N/A

**Describe the bug**
When installing packages while running `npx wdio config`, the build fails when it tries to install @wdio/spec-reporter@^7.0.8 which doesn't exist

**To Reproduce**
1. run `npx wdio config`
2. Answer the questions (You can also pass the --yes flag)
3. Build fails

**Expected behavior**
Packages install.

**Log**
```
Installing wdio packages:
- @wdio/local-runner@^7.0.8
- @wdio/mocha-framework@^7.0.8
- @wdio/spec-reporter@^7.0.8
- wdio-chromedriver-service
- @wdio/sync@^7.0.8
- chromedriver
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @wdio/spec-reporter@^7.0.8.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

The latest available version of spec-reporter is 7.0.7.  Maybe just a timing issue?  Is 7.0.8 about to be released?

### PR DESCRIPTION
**Pull request by iamkenos**
## Proposed changes

- fixes #6569
- ~~to add a condition for dist tags `beta` and `next` when installing packages via the config command~~
- to add a condition to check if fetchSpec mathces semver

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

- ~~do we need to add it for uncommon tags too? looking at previous release tags, wdio has had `alpha` and `blm` tags before~~

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-cli/src/commands/config.ts [hunk 1]
```diff
@@ -105,9 +105,12 @@ const runConfig = async function (useYarn: boolean, yes: boolean, exit = false)
      * ensure wdio packages have the same dist tag as cli
      */
     if (pkg._requested && pkg._requested.fetchSpec) {
-        packagesToInstall = packagesToInstall.map((p) => p.startsWith('@wdio') || ['devtools', 'webdriver', 'webdriverio'].includes(p)
-            ? `${p}@${pkg._requested.fetchSpec}`
-            : p
+        const { fetchSpec } = pkg._requested
+        packagesToInstall = packagesToInstall.map((p) =>
+            (p.startsWith('@wdio') || ['devtools', 'webdriver', 'webdriverio'].includes(p)) &&
+            (fetchSpec.includes('beta') || fetchSpec.includes('next'))
```
Comment (christian-bromann) [inline packages/wdio-cli/src/commands/config.ts:111]: This would limit us in only using `beta` or `next` tags. It would be great if every tag can work. Therefor I suggest to try to match against versions, e.g. `/(v)?\d+\.\d+\.\d+/` something like that?

**Review by christian-bromann — CHANGES_REQUESTED** [review]

**Review by christian-bromann — APPROVED** [review]
Awesome, thank you so much 👍
