### PR TITLE
fix(webdriverio): handle `closeWindow` for WDIO classic when no window is open

### LINKED ISSUE #14047: [🐛 Bug]: closeWindow() leads to "Malformed type for "handle" parameter of command switchToWindow" error when only one window is opened
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

22.12.0

### Mode

Standalone Mode

### Which capabilities are you using?

_No response_

### What happened?

After the changes https://github.com/webdriverio/webdriverio/pull/14025, command closeWindow() leads to the error(when only one window has been opened): 

```
[chrome 131.0.6778.205 windows #0-0] Error: Malformed type for "handle" parameter of command switchToWindow
[chrome 131.0.6778.205 windows #0-0] Error: Malformed type for "handle" parameter of command switchToWindow
[chrome 131.0.6778.205 windows #0-0] Expected: string
[chrome 131.0.6778.205 windows #0-0] Actual: undefined
[chrome 131.0.6778.205 windows #0-0]
[chrome 131.0.6778.205 windows #0-0] For more info see https://w3c.github.io/webdriver/#dfn-switch-to-window
```

It happens for both: Bidi and classic protocols ("wdio:enforceWebDriverClassic": true)

### What is your expected behavior?

According to the documentation:
`The Close Window command closes the current top-level browsing context. Once done, if there are no more top-level browsing contexts open, the WebDriver session itself is closed.`

So the expected result is to close the window even if it was only one window, without the error (as before the fix)

### How to reproduce the bug.

await browser.url(url)
await browser.closeWindow()

### Relevant log output

```typescript
[chrome 131.0.6778.205 windows #0-0] Error: Malformed type for "handle" parameter of command switchToWindow
[chrome 131.0.6778.205 windows #0-0] Error: Malformed type for "handle" parameter of command switchToWindow
[chrome 131.0.6778.205 windows #0-0] Expected: string
[chrome 131.0.6778.205 windows #0-0] Actual: undefined
[chrome 131.0.6778.205 windows #0-0]
[chrome 131.0.6778.205 windows #0-0] For more info see https://w3c.github.io/webdriver/#dfn-switch-to-window
[chrome 131.0.6778.205 windows #0-0]
[chrome 131.0.6778.205 windows #0-0]     at Browser.protocolCommand (file:///C:/123123/node_modules/webdriver/build/node.js:86:15)
[chrome 131.0.6778.205 windows #0-0]     at Browser.wrapCommandFn (C:\123123\node_modules\@wdio\utils\build\index.js:893:32)
[chrome 131.0.6778.205 windows #0-0]     at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
[chrome 131.0.6778.205 windows #0-0]
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by navin772**
## Proposed changes

Fixes #14047

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [ ] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by navin772** [comment]
@christian-bromann I have made the changes as per your [suggestions](https://github.com/webdriverio/webdriverio/pull/14025#issuecomment-2581465748), PTAL.

**Comment by navin772** [comment]
@HannaTarasevich this fix should work to resolve the `Malformed type for "handle" parameter of command switchToWindow` error, but do note that the [reproducible example](https://github.com/HannaTarasevich/wdio-closeWindow) you provided will still fail due to another error:
```
invalid session id: WebDriverError: invalid session id when running "url" with method "POST" and args "{"url":"https://the-internet.herokuapp.com/login"}"
```
since the window is being closed as soon as it is opened. You can try using above `pkg.pr` packages to test.

**Comment by HannaTarasevich** [comment]
@navin772
Thank you for the prepared solution! Right, this error is totally expected

**Comment by christian-bromann** [comment]
I am getting the following error with this:

```
2025-01-10T05:48:19.820Z INFO webdriver: COMMAND closeWindow()
2025-01-10T05:48:19.820Z INFO webdriver: [DELETE] http://localhost:58259/session/c6936cec45deca85bccc34e4f94c6222/window
2025-01-10T05:48:19.931Z INFO webdriver: RESULT []
2025-01-10T05:48:19.931Z INFO webdriver: COMMAND createWindow("tab")
2025-01-10T05:48:19.931Z INFO webdriver: [POST] http://localhost:58259/session/c6936cec45deca85bccc34e4f94c6222/window/new
2025-01-10T05:48:19.931Z INFO webdriver: DATA { type: 'tab' }
2025-01-10T05:48:19.946Z ERROR webdriver: WebDriverError: invalid session id when running "window/new" with method "POST" and args "{"type":"tab"}"
/Users/christian.bromann/Sites/WebdriverIO/projects/webdriverio/packages/webdriver../src/request/request.ts:228
        const error = new WebDriverResponseError(response, url, fullRequestOptions)
                      ^


invalid session id: WebDriverError: invalid session id when running "window/new" with method "POST" and args "{"type":"tab"}"
```

Basically the command to open the window fails - as expected since the driver closes the session as no windows are around anymore. I am not sure if this is a "solution" to the problem. I rather return a more conrete error message to the user notifying that they closed all windows.

What do you all think should be the right behavior?

**Comment by HannaTarasevich** [comment]
This bug was only about a new issue with "malformed," which has been fixed. The "invalid session id" error was expected and has always worked this way. Therefore, I wouldn’t address it within the scope of this bug.

In general, I agree that the message could be improved, but I believe it is quite descriptive as it is now.

File: packages/webdriverio/src/session/context.ts [hunk 1]
```diff
@@ -65,13 +65,19 @@ export class ContextManager extends SessionManager {
...
          * the `closeWindow` command returns:
          *   > the result of running the remote end steps for the Get Window Handles command, with session, URL variables and parameters.
          */
         if (event.command === 'closeWindow') {
-            this.#currentContext = (event.result as { value: string[] }).value[0]
+            const windowHandles = (event.result as { value: string[] }).value
+            if (windowHandles.length === 0) {
+                const newWindowHandle = await this.#browser.createWindow('tab')
+                this.#currentContext = newWindowHandle.handle
+                return this.#browser.switchToWindow(this.#currentContext)
```
Comment (christian-bromann) [inline packages/webdriverio/src/session/context.ts:78]: How about instead of calling a command that will fail anyway to just throw a meaningful message here, saying that all handles were removed which has caused WebdriverIO to close the session.

**Review by christian-bromann — CHANGES_REQUESTED** [review]

File: packages/webdriverio/src/session/context.ts (hunk 1 above)
Comment (navin772) [reply packages/webdriverio/src/session/context.ts:78]: You mean instead of creating a new window, we just return an error message? That would not resolve this issue, although that's what the [spec](https://www.w3.org/TR/webdriver2/#dfn-close-window:~:text=If%20there%20are%20no%20more%20open%20top%2Dlevel%20browsing%20contexts%2C%20then%20try%20to%20close%20the%20session.) tells to do.

> calling a command that will fail anyway

Which command are we referring to here?

File: packages/webdriverio/src/session/context.ts [hunk 2]
```diff
@@ -65,13 +65,17 @@ export class ContextManager extends SessionManager {
         }
     }
 
-    #onCommandResultBidiAndClassic(event: { command: string, result: unknown }) {
+    async #onCommandResultBidiAndClassic(event: { command: string, result: unknown }) {
```
Comment (christian-bromann) [inline packages/webdriverio/src/session/context.ts:68]:
```suggestion
    #onCommandResultBidiAndClassic(event: { command: string, result: unknown }) {
```

**Review by christian-bromann — APPROVED** [review]
LGTM 👍
