### PR TITLE
@wdio/browserstack-service: Add session naming options

### LINKED ISSUE #7876: [🐛 Bug]: For mocha tests, BrowserStack session name is set as '<the last test title's describe> - <test title>'
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

7.5.7

### Node.js Version

12

### Mode

Standalone Mode

### Which capabilities are you using?

```typescript
{
  os: 'OS X',
  osVersion: 'Catalina',
  browserName: 'Chrome',
  browserVersion: 'latest',
}

Wdio and other packages in use:
@wdio/browserstack-service
@wdio/cli
@wdio/local-runner
@wdio/mocha-framework
@wdio/selenium-standalone-service
@wdio/spec-reporter
webdriverio
selenium-standalone (^6.15)
```

### What happened?

homepage.spec.ts
```
describe('Homepage', () => {
  describe('header', () => {
    it('is rendered', () => {});
  }
  describe('navigation', () => {
    it('is present on the page', () => {});
  }
  describe('footer', () => {
    it('is present on the page', () => {});
  }
})
```
category.spec.ts
```
describe('Category Page', () => {
  describe('header', () => {
    it('is rendered', () => {});
  }
  describe('navigation', () => {
    it('is present on the page', () => {});
  }
  describe('footer', () => {
    it('is present on the page', () => {});
  }
})
```
**Current Behavior:**
With Mocha tests, the session name for the above spec files is same which is "footer - is present on the page".  (last test's parent describe - last test's title) as per https://github.com/webdriverio/webdriverio/blob/main/packages/wdio-browserstack-service/src/service.ts#L95

I have tried to rename the session name using BrowserStack REST API but it is overriding the session name by BrowserStack-service after the hook code.

**Additional Info:**
Fix done for Jasmine tests #6777 
https://github.com/webdriverio/webdriverio/pull/7198 

### What is your expected behavior?

In the above case, the expected session name for homepage.spec.ts should be - `'Homepage'`
and for category.spec.ts, should be - `'Category Page'`. 
Expect the main/global describe title of the spec file as a session name so we can differentiate between different spec files. 

### How to reproduce the bug.

To reproduce the issue, run the mocha tests shown above(nested describe) in BrowserStack and observe the BrowserStack session names.

### Relevant log output

```typescript
The session name for both the spec files is the same - "footer - is present on the page"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by SCG82**
## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

- Set the session name in `beforeSuite` and/or `beforeTest` instead of `afterTest`
  - allow the user the option to update the name at any given point in time.
  - account for cases where there is a long running `before` function, or one that can fail.
- Add options `setSessionName` and `setSessionStatus` (both default to `true`)
- Add option `sessionNamePrependTopLevelSuiteTitle `
  - For nested suites, set session name to: `<outer suite title> - <inner suite title>`
- Add option `sessionNameOmitTestTitle `
  - Set session name to: `<suite title>`
- Add option `sessionNameFormat` to allow customizing the session name using configuration, capabilities, suite title, test title (Mocha only)

Setting `sessionNamePrependTopLevelSuiteTitle =true` and `sessionNameOmitTestTitle=true` will resolve #7876 using the consensus from the discussion in #6777.

Examples, `sessionNamePrependTopLevelSuiteTitle` and `sessionNameOmitTestTitle` set to `true`:
```javascript
describe('webdriver.io', () => {
    describe('header bar', () => {
        it('should have logo', () => {})
    })
    describe('body', () => {
        xit('font should be...', () => {})
    })
})

// Session name before the fix: "header bar - should have logo"
// Session name after the fix: "webdriver.io - header bar"
```

Deeply nested suites:
```javascript
describe('webdriver.io', () => {
    describe('v6', () => {
        describe('header bar', () => {
            it('should have inline search', () => {})
        })
    })
})

// Session name before the fix: "header bar - should have inline search"
// Session name after the fix: "webdriver.io - header bar"
```

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

**Comment by christian-bromann** [comment]
@SCG82 it seems like unit tests are failing 🤔

**Comment by SCG82** [comment]
> @SCG82 it seems like unit tests are failing 🤔

Ready for review

File: packages/wdio-browserstack-service/src/service.ts [hunk 1]
```diff
@@ -95,7 +97,12 @@ export default class BrowserstackService implements Services.ServiceInstance {
             }
         } else {
             // Mocha
-            this._fullTitle = `${test.parent} - ${test.title}`
+            // eslint-disable-next-line no-lonely-if
```
Comment (erwinheitzman) [inline packages/wdio-browserstack-service/src/service.ts:100]: This rule is quite valid and I don't agree disabling it: https://eslint.org/docs/latest/rules/no-lonely-if

File: packages/wdio-browserstack-service/src/service.ts [hunk 2]
```diff
@@ -95,7 +97,12 @@ export default class BrowserstackService implements Services.ServiceInstance {
...
+            if (test.parent && test.parent !== this._suiteTitle) {
+                this._fullTitle = `${this._suiteTitle} - ${test.parent}`
```
Comment (erwinheitzman) [inline packages/wdio-browserstack-service/src/service.ts:102]: Feels like this needs to happen recursively when there is more than one parent suite, in other words, I do not think this handles cases like this:
```js
describe('my component', () => {
  describe('scenario A', () => {
    describe('and some other condition is truthy', () => {
      it('example', () => {
        // this now has three parents, does this work?
      });
    });
  });
});
```

**Review by erwinheitzman — CHANGES_REQUESTED** [review]
Thank you for this PR, I have left a question and a request for change

File: packages/wdio-browserstack-service/src/service.ts (hunk 2 above)
Comment (SCG82) [reply packages/wdio-browserstack-service/src/service.ts]: For this example, it will set the session name to: `my component - and some other condition is truthy`. For comparison, the sauce labs service will set the job name to `my component` and add context of `and some other condition is truthy - example`. 

I can't figure out how to obtain `scenario A` from any of the hooks. Any ideas?

**Comment by SCG82** [comment]
Made a few changes, and added some tests (based on the sauce service tests). Also fixed the type errors in the service test.

File: packages/wdio-browserstack-service/src/service.ts (hunk 2 above)
Comment (SCG82) [reply packages/wdio-browserstack-service/src/service.ts]: Another option is to use one of the following as the session name:
- `this._suiteTitle` (which would be "my component" in the above example)
- `test.parent` ("and some other condition is truthy")

or keep the current title (test.parent - test.title) except set it before the test (so users may change it without being overridden).

**Comment by christian-bromann** [comment]
@Ankit098 what do you think?

**Comment by christian-bromann** [comment]
@SCG82 mind updating this branch, it should resolve the build issues.

**Comment by christian-bromann** [comment]
@Ankit098 what do you think?

**Review by Ankit098 — COMMENTED** [review]
1. in the following scenario:
```
describe("describe title", () => {
  it("it title", () => {
  })
})
```
the session name after new changes will be `describe title` (from `describe title - it title` earlier).. and by extension the `it block`'s name gets dropped even in nested describe.. I think we should include the it block's title.
2. for nested desribes, like either:
```
describe("describe1", () => {
  describe("describe2", () => {
    describe("describe3", () => {
      it("it1", () => {
      })
      it("it2", () => {
      })
    })
  })
})
```
or
```
describe("describe1", () => {
  describe("describe2", () => {
    it("it1", () => {
    })
  })
  describe("describe3", () => {
    it("it2", () => {
    })
  })
})
```
the session name picked will be `describe1 - describe3` here we can introduce some [annotations](https://www.browserstack.com/docs/automate/selenium/annotations) to differentiate the different blocks' execution in the logs on browserstack dashboard. +@alliv8

**Comment by SCG82** [comment]
I can make this change, although it would be preferable if BrowserStack introduced a "subtitle" / "context" in which to display the current `it` step (similar to SauceLabs' 'context') so that the job title can be set by the user (in `before`) and not overridden.

**Comment by SCG82** [comment]
@christian-bromann @Ankit098 ready for review

**Comment by SCG82** [comment]
@christian-bromann @Ankit098 ready for another review

**Comment by alliv8** [comment]
I think adding more verbosity would be a personal choice and whatever changes we make, we should not modify existing behaviour for users (leads to users saying why did you change this; I didn't ask for it), and rather extend functionality in cases where the outcome is undesired or add options for more advanced use-cases.

In terms of BrowserStack adding further classification, we've attempted to solve this using console annotators, which can be seen and filtered within the session log context to highlight different `describe` and `it` blocks. The service could automatically use the beforeHook for each `describe` and  `it` context to be passed to the BrowserStack session.

I'm wondering if we could create options to support the different preferences that have been brought up, and keep current behaviour as default?

```
sessionNamingOpts: {
  includeLastStep: true / false (default true) -- 
  maxDescribeLevels: 1  
}
```

or we instead allow for users to decide, and disable the service naming and test marking logic

```
setSessionName: true / false
```

**Comment by SCG82** [comment]
> we should not modify existing behaviour for users

Existing behavior is unchanged by this PR, except that the job name is set before the suite/test instead of only after the test has completed.

**Comment by SCG82** [comment]
@alliv8 @Ankit098 @christian-bromann Added `setSessionName`, `setSessionStatus` options + tests and updated README.

**Comment by SCG82** [comment]
@erwinheitzman can I get another review?

File: packages/wdio-browserstack-service/README.md [hunk 3]
```diff
@@ -141,8 +135,53 @@ services: [
...
+Default: `false`
+
+### setSessionName
+
+Automatically set the BrowserStack Automate session name.
+
+Type: `Boolean`<br />
+Default: `true`
+
+### setSessionStatus
```
Comment (christian-bromann) [inline packages/wdio-browserstack-service/README.md:175]: Just curious, I would love to understand when people are interested to turn this off. Is it because these additional request slow down the test run?

**Review by christian-bromann — APPROVED** [review]
Overall fantastic change set, great work 👍 

Please see my last question, which I would like to see answered before merging. Having this options seems great but if not really needed we could avoid adding it as it means also more stuff to maintain 😉

File: packages/wdio-browserstack-service/README.md (hunk 3 above)
Comment (SCG82) [reply packages/wdio-browserstack-service/README.md:175]: For my use case I'd like to set the session status/reason in an `after` hook without it being overridden.

**Comment by SCG82** [comment]
changes since last review:
* apply `sessionNameFormat` in all locations where the session name is set.

File: packages/wdio-browserstack-service/README.md (hunk 3 above)
Comment (christian-bromann) [reply packages/wdio-browserstack-service/README.md:175]: Why are you setting the name in the after hook? Just curious.

**Comment by christian-bromann** [comment]
@Ankit098 this change looks good to me. Can you do a second review and give me your 👍 ?

File: packages/wdio-browserstack-service/README.md (hunk 3 above)
Comment (ablok) [reply packages/wdio-browserstack-service/README.md:175]: It's what I would do as well. I would like to write the path of the module there as session name.
Unless browserstack starts supporting it's within a session.

Comment (alliv8) [reply packages/wdio-browserstack-service/README.md:175]: For session name:

We've seen instances of incompatibility of the cucumber wdio parallel plugin and the service's naming logic at a scenario level.

In this case, users have opted to not use the service entirely.

Another one was where describe blocks were written in Korean, and Browserstack currently doesn't support those characters in the name.

While the above are either bugs or fixable limitations, at least the flexibility helps users to fix things themselves, and not have to troubleshoot a behaviour where they set context manually and then it gets overridden on BrowserStack via the service.

For session status:

I've seen patterns where the session reason is set to a grouped message based on all the assertions that have failed in a session.

Something like
"1 of 3 tests failed"

Currently we set the reason based on a single failure

Comment (christian-bromann) [reply packages/wdio-browserstack-service/README.md:175]: Makes sense to me, thanks for clarifying @alliv8

Comment (SCG82) [reply packages/wdio-browserstack-service/README.md:175]: > Why are you setting the name in the after hook? Just curious.

Not the name but the status (passed/failed) and a descriptive `reason` that conveys additional information if `passed`.

**Review by bhanuagarwal73 — APPROVED** [review]

**Review by bhanuagarwal73 — APPROVED** [review]

**Review by Ankit098 — APPROVED** [review]
LGTM! @SCG82 @christian-bromann

**Comment by Ankit098** [comment]
A minor improvement that can be done in a future PR is to add a js executor in the block where the session name is now being updated to add annotations in the logs to better distinguish the different describes/its being executed in the same session - as right now the session name gets updated with each it block and the final name is the last it block - having the annotations will put the different describes/its as visually different blocks in the logs, making logs more meaningful and debugging easier.

**Comment by SCG82** [comment]
> A minor improvement that can be done in a future PR is to add a js executor in the block where the session name is now being updated to add annotations in the logs to better distinguish the different describes/its being executed in the same session - as right now the session name gets updated with each it block and the final name is the last it block - having the annotations will put the different describes/its as visually different blocks in the logs, making logs more meaningful and debugging easier.

Does https://github.com/webdriverio/webdriverio/pull/9124 handle this?

**Comment by bhanuagarwal73** [comment]
Hey @Ankit098 @christian-bromann  I am not seeing sessionNameOmitTestTitle in bstack:options.
Generally using as below rather than at service level

"bstack:options": runtimeArgs.service === 'browserstack' ? {
            "projectName": "xxxxxxx",
            "buildName": `${runtimeArgs.env} - ${runtimeArgs.brand} - ${runtimeArgs.suite} - ${runtimeArgs.browserName}`,
            "os": runtimeArgs.os,
            "osVersion": runtimeArgs.osVersion,
            "deviceName": runtimeArgs.device,
            "networkLogs": true,
            "consoleLogs": "errors",
            "browserVersion": "latest",
            "local": true
        } : {}

I don't want to define at service level:
services: [runtimeArgs.service == 'browserstack' ? [runtimeArgs.service, {
        "sessionNameOmitTestTitle": true
    }] : runtimeArgs.service],

**Comment by christian-bromann** [comment]
@bhanuagarwal73 you have to add `@wdio/browserstack-service` to your `"types"` property in `tsconfig.json`.

**Comment by bhanuagarwal73** [comment]
@christian-bromann  added but still not seeing it.
image

{
    "compilerOptions": {
        "esModuleInterop": true,
        "types": [
            "node",
            "webdriverio/async",
            "@wdio/mocha-framework",
            "@wdio/browserstack-service"
        ],
        "target": "ES5",
        "downlevelIteration": true
    }
}

**Comment by christian-bromann** [comment]
It works on my machine™️
Screenshot 2022-11-25 at 10 21 40

**Comment by christian-bromann** [comment]
This option has to be applied to the service not to your capabilities.

**Comment by bhanuagarwal73** [comment]
That's what asked in initial comments. Thanks for the response as there is no way over bstack:Options, will go with  service level :)

**Comment by christian-bromann** [comment]
I am not sure what you mean by that.

**Comment by bhanuagarwal73** [comment]
Nothing buddy. I am saying ok, will add in service

**Comment by ssomise5** [comment]
Can some one assist , how to use the above fix . Do we need to have specific wdio version

**Comment by ssomise5** [comment]
can someone help me with this bug fix
