### PR TITLE
Fix #11684: Improve AfterTest() for Jasmine

### LINKED ISSUE #11684: Unable to capture failed WebdriverIO - Jasmine spec screenshot in Allure Report due to afterTest() hook returning incorrect value for failed spec as passed=true
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

8.20.2

### Node.js Version

8.15.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
browserName: chrome,
browserVersion: 'latest',
platformName: 'Windows 10'
operatingSystem: Windows 10

dependencies in package.json

"@babel/core": "^7.23.2",
"@babel/preset-env": "^7.23.2",
"@babel/register": "^7.22.15",
"@wdio/allure-reporter": "^8.20.0",
"@wdio/cli": "^8.20.2",
"@wdio/jasmine-framework": "^8.23.0",
"@wdio/local-runner": "^8.20.0",
"@wdio/spec-reporter": "^8.20.0",
"allure-commandline": "^2.24.1"
```

### What happened?

Hi Team, We are using the WebdriverIO with the Jasmine framework for our test automation project. We observed the afterTest() hook in the WebdriverIO shows the passed value as true for the spec that failed with an expectation. Due to this issue, we cannot take a screenshot of the failed spec and attach it to the allure report. Please find the below framework details.

WebdriverIO version: 8.20.2
Framework: Jasmine
Language: Javascript
Mode: [WDIO Testrunner]
If WDIO Testrunner, running sync/async: [async]
Node.js version: [18.15.0]
NPM version: [9.5.0]
Browser name and version: [Chrome 119]
Platform name and version: [Windows 10

We even tried to use the below check in afterTest() hook, but still, the screenshot is not captured in the allure report failed spec.

afterTest: async function (test, context, { error, result, duration, passed, retries }) {
        if (!passed || error) {
            await browser.takeScreenshot()
        }
    }
Attached is the allure report screenshot
image

### What is your expected behavior?

The afterTest() hook should return the correct passed value as true/false for the spec passed/failed due to expectation/assertion

### How to reproduce the bug.

Attached is the sample project created to reproduce this issue. The project contains two specs, one will pass and the other will fail due to expectations.

[JasmineProject.zip](https://github.com/webdriverio/webdriverio/files/13403550/JasmineProject.zip)

### Relevant log output

```typescript
Execution of 1 workers started at 2023-11-19T14:42:21.622Z

[0-0] RUNNING in chrome - file:///C:/Users/User1/Desktop/JasmineProject/test/specs/test.e2e.js

DevTools listening on ws://127.0.0.1:56785/devtools/browser/8fcda011-3409-4c9b-afb6-7b7d4dff81c6
[26656:30380:1119/201242.995:ERROR:policy_logger.cc(157)] :components\policy\core\browser\policy_conversions_client.cc(317) DeveloperToolsDisabled has an error of type: Ignored because it was overridden by DeveloperToolsAvailability.
[0-0] Error in "My Login application should login with valid credentials and expectation failure"
    at <Jasmine>
    at UserContext.<anonymous> (C:\Users\User1\Desktop\JasmineProject\test\specs\/test.e2e.js:24:50)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[0-0] FAILED in chrome - file:///C:/Users/User1/Desktop/JasmineProject/test/specs/test.e2e.js

 "spec" Reporter:
------------------------------------------------------------------
[chrome 119.0.6045.160 windows #0-0] Running: chrome (v119.0.6045.160) on windows
[chrome 119.0.6045.160 windows #0-0] Session ID: 6dc13b4a034ab8e2c836fc5a6d043a9f
[chrome 119.0.6045.160 windows #0-0] » \test\specs\/test.e2e.js
[chrome 119.0.6045.160 windows #0-0] My Login application
[chrome 119.0.6045.160 windows #0-0]    ✓ should login with valid credentials
[chrome 119.0.6045.160 windows #0-0]    ✖ should login with valid credentials and expectation failure
[chrome 119.0.6045.160 windows #0-0]
[chrome 119.0.6045.160 windows #0-0] 1 passing (37.8s)
[chrome 119.0.6045.160 windows #0-0] 1 failing
[chrome 119.0.6045.160 windows #0-0]
[chrome 119.0.6045.160 windows #0-0] 1) My Login application should login with valid credentials and expectation failure
[chrome 119.0.6045.160 windows #0-0] Expect $(`//a/i[text()=' Logout']`) to be disabled

Expected: "disabled"
Received: "not disabled"
[chrome 119.0.6045.160 windows #0-0]     at <Jasmine>
[chrome 119.0.6045.160 windows #0-0]     at UserContext.<anonymous> (C:\Users\User1\Desktop\JasmineProject\test\specs\/test.e2e.js:24:50)
[chrome 119.0.6045.160 windows #0-0]     at processTicksAndRejections (node:internal/process/task_queues:95:5)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:55
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by tech-dm-klymenko**
Fix for https://github.com/webdriverio/webdriverio/issues/11684

## Proposed changes

[//]: # (Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.)

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have added proper type definitions for new commands (if appropriate)

## Further comments

[//]: # (If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...)

### CODE REVIEW

File: packages/wdio-jasmine-framework/src/index.ts [hunk 1]
```diff
@@ -536,4 +537,13 @@ declare global {
...
+
+    // Firstly variable '_wdioDynamicJasmineResult' gets value in packages/wdio-jasmine-framework/src/index.ts and then used here in wdio-utils as workaround for Jasmine
+    // eslint-disable-next-line no-var
+    var _wdioDynamicJasmineResult: WdioDynamicJasmineResult
+}
+
+interface WdioDynamicJasmineResult {
+    passedExpectations: [any, ...any[]]
+    failedExpectations: [any, ...any[]]
 }
```
Comment (christian-bromann) [inline packages/wdio-jasmine-framework/src/index.ts:549]: This should be sufficient
```suggestion
    var _wdioDynamicJasmineResult: any
}
```

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts [hunk 2]
```diff
@@ -7,6 +7,18 @@ import type {
...
+declare global {
+    // Firstly variable '_wdioDynamicJasmineResult' gets value in packages/wdio-jasmine-framework/src/index.ts and then used here in wdio-utils/ as workaround for Jasmine
+    // eslint-disable-next-line no-var
+    var _wdioDynamicJasmineResult: WdioDynamicJasmineResult
+}
+
+interface WdioDynamicJasmineResult {
+    passedExpectations: [any, ...any[]]
+    failedExpectations: [any, ...any[]]
+}
```
Comment (christian-bromann) [inline packages/wdio-utils/src/test-framework/testFnWrapper.ts:21]:
```suggestion
declare global {
    // Firstly variable '_wdioDynamicJasmineResult' gets value in packages/wdio-jasmine-framework/src/index.ts and then used here in wdio-utils/ as workaround for Jasmine
    // eslint-disable-next-line no-var
    var _wdioDynamicJasmineResult: Error
}
```

Comment (christian-bromann) [reply packages/wdio-utils/src/test-framework/testFnWrapper.ts:21]: Let's store only the error in the global variable since it is the only think we are interested in.

File: packages/wdio-jasmine-framework/src/index.ts [hunk 3]
```diff
@@ -201,6 +201,7 @@ class JasmineAdapter {
             self._lastTest = this.result
             // @ts-ignore overwrite existing type
             self._lastTest.start = new Date().getTime()
+            globalThis._wdioDynamicJasmineResult = this.result
```
Comment (christian-bromann) [inline packages/wdio-jasmine-framework/src/index.ts:204]: Then maybe do this her:
```suggestion
            if (this.result.passedExpectations.length === 0 && this.result.failedExpectations.length > 0) {
                globalThis._wdioDynamicJasmineResult = this.result.failedExpectations[0]
            }
```

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts [hunk 4]
```diff
@@ -83,6 +95,17 @@ export const testFrameworkFnWrapper = async function (
...
+            globalThis._wdioDynamicJasmineResult &&
+            global._wdioDynamicJasmineResult.passedExpectations.length === 0 &&
+            global._wdioDynamicJasmineResult.failedExpectations.length > 0
+        ) {
+            const jasmineErr = new Error(globalThis._wdioDynamicJasmineResult.failedExpectations[0]?.message)
+            jasmineErr.stack = globalThis._wdioDynamicJasmineResult.failedExpectations[0].stack
+            throw jasmineErr
+        } else {
+            console.error(afterHookErrMessage)
+        }
```
Comment (christian-bromann) [inline packages/wdio-utils/src/test-framework/testFnWrapper.ts:108]: So we can simplify this:
```suggestion
        if (globalThis._wdioDynamicJasmineResultError) {
            error = globalThis._wdioDynamicJasmineResultError
            globalThis._wdioDynamicJasmineResultError = undefined
        }
```

Comment (christian-bromann) [reply packages/wdio-utils/src/test-framework/testFnWrapper.ts:108]: I think it makes sense then to name the variable `_wdioDynamicJasmineResultError`

**Review by christian-bromann — CHANGES_REQUESTED** [review]
Some comments, great progress!

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts (hunk 4 above)
Comment (tech-dm-klymenko) [reply packages/wdio-utils/src/test-framework/testFnWrapper.ts:108]: Done

File: packages/wdio-jasmine-framework/src/index.ts (hunk 3 above)
Comment (tech-dm-klymenko) [reply packages/wdio-jasmine-framework/src/index.ts:204]: Here in `init()` we simply get a reference to a variable with the test results. But here `result.failedExpectations/passedExpectations` are empty arrays, so the condition will never be satisfied and the assignment will not take place.

As far as I can see, the results end up in the variable `result` dynamically only after this step: 
```typescript
// testFnWrapper.ts

 result = await executeAsync.call(this, specFn, retries, specFnArgs, timeout)
``` 

Therefore, it seems to me that it would be more appropriate to leave only the variable assignment here, as it was before. And then already do the conditions and checks in `testFnWrapper.ts`

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts (hunk 2 above)
Comment (tech-dm-klymenko) [reply packages/wdio-utils/src/test-framework/testFnWrapper.ts:21]: Done

**Comment by tech-dm-klymenko** [comment]
And yet another unexpected moment came to light. Even if the tests are passed, the variable `result` remains `undefined` and does not contain any information for afterHook()
```typescript
result = await executeAsync.call(this, specFn, retries, specFnArgs, timeout)
```

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts (hunk 2 above)
Comment (tech-dm-klymenko) [reply packages/wdio-utils/src/test-framework/testFnWrapper.ts:21]: Here I left type `any` instead of `Error `due to type-checking errors during transpilation

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts [hunk 5]
```diff
@@ -8,11 +8,18 @@ import type {
     AfterHookParam
 } from './types.js'
 
+declare global {
+    // Firstly variable '_wdioDynamicJasmineResultErrorList' gets reference to test result in packages/wdio-jasmine-framework/src/index.ts and then used here in wdio-utils/ as workaround for Jasmine
+    // eslint-disable-next-line no-var
+    var _wdioDynamicJasmineResultErrorList: any
```
Comment (christian-bromann) [inline packages/wdio-utils/src/test-framework/testFnWrapper.ts:14]: The global is only defined in Jasmine
```suggestion
    var _wdioDynamicJasmineResultErrorList?: any
```

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts [hunk 6]
```diff
@@ -83,6 +90,13 @@ export const testFrameworkFnWrapper = async function (
     const testStart = Date.now()
     try {
         result = await executeAsync.call(this, specFn, retries, specFnArgs, timeout)
+        if (result === undefined &&
+            globalThis._wdioDynamicJasmineResultErrorList.length > 0
```
Comment (christian-bromann) [inline packages/wdio-utils/src/test-framework/testFnWrapper.ts:94]:
```suggestion
            globalThis._wdioDynamicJasmineResultErrorList?.length > 0
```

File: packages/wdio-utils/src/test-framework/testFnWrapper.ts [hunk 7]
```diff
@@ -8,11 +8,18 @@ import type {
     AfterHookParam
 } from './types.js'
 
+declare global {
+    // Firstly variable '_wdioDynamicJasmineResultErrorList' gets reference to test result in packages/wdio-jasmine-framework/src/index.ts and then used here in wdio-utils/ as workaround for Jasmine
+    // eslint-disable-next-line no-var
+    var _wdioDynamicJasmineResultErrorList?: any
```
Comment (christian-bromann) [inline packages/wdio-utils/src/test-framework/testFnWrapper.ts:14]:
```suggestion
    var _wdioDynamicJasmineResultErrorList: any | undefined
```

**Review by christian-bromann — CHANGES_REQUESTED** [review]
@tech-dm-klymenko last request: can we add a smoke test for this to ensure we don't regress in the future. I would recommend to create a new smoke test suite that runs a single (failing) jasmine test and writes the result of the `afterTest` hook into a file to then verify the result again in the smoke test. Let me know if you have any questions.

**Comment by tech-dm-klymenko** [comment]
@christian-bromann 
The smoke test turned out to be quite complex; however, it not only checks the existence of values but also ensures that we receive the expected structure and that it has not changed (even under the influence of future updates).

What do you think?
