### PR TITLE
fix(webdriverio): improve switchFrame behavior

### LINKED ISSUE #13776: [🐛 Bug]: switchFrame only works for bidi
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md#reporting-new-issues).

### WebdriverIO Version

latest

### Node.js Version

20.14.0

### Mode

WDIO Testrunner

### Which capabilities are you using?

```typescript
capabilities: [{
        'wdio:enforceWebDriverClassic': true,
        browserName: 'chrome'
    }],
```

### What happened?

Getting an error when trying to use switchFrame passing in something that has to be queried like a selector or url: Failed to execute WebDriver Bidi command "browsingContextGetTree" as no Bidi session was established. Make sure you enable it by setting "webSocketUrl: true" in your capabilities and verify that your environment and browser supports it.

### What is your expected behavior?

switchFrame should work without bidi enabled

### How to reproduce the bug.

To reproduce:

1. Create a wdio project
2. In wdio.conf.ts, update the capabilities to use 'wdio:enforceWebDriverClassic': true
3. Add a page object for something with iframe
4. Add a method that switches to the iframe using a url or frame element parameter
5. Use the new method in a wdio test

I have a sample repo at https://github.com/ShannonH/wdio-test-repo where I've done the above already using the same 'the-internet' app and sample code from the docs to switch to the iframe on the page using the iframe's url (it might be the wrong url, but the error happens on the query)

### Relevant log output

```typescript
[chrome 130.0.6723.59 mac #0-0] Running: chrome (v130.0.6723.59) on mac
[chrome 130.0.6723.59 mac #0-0] Session ID: 734f51e68eaaab8549222b10790d4726
[chrome 130.0.6723.59 mac #0-0]
[chrome 130.0.6723.59 mac #0-0] » /test/specs/test.e2e.ts
[chrome 130.0.6723.59 mac #0-0] My Login application
[chrome 130.0.6723.59 mac #0-0]    ✓ should login with valid credentials
[chrome 130.0.6723.59 mac #0-0]    ✖ should switch to iframes
[chrome 130.0.6723.59 mac #0-0]
[chrome 130.0.6723.59 mac #0-0] 1 passing (2.1s)
[chrome 130.0.6723.59 mac #0-0] 1 failing
[chrome 130.0.6723.59 mac #0-0]
[chrome 130.0.6723.59 mac #0-0] 1) My Login application should switch to iframes
[chrome 130.0.6723.59 mac #0-0] Failed to execute WebDriver Bidi command "browsingContextGetTree" as no Bidi session was established. Make sure you enable it by setting "webSocketUrl: true" in your capabilities and verify that your environment and browser supports it.
[chrome 130.0.6723.59 mac #0-0] Error: Failed to execute WebDriver Bidi command "browsingContextGetTree" as no Bidi session was established. Make sure you enable it by setting "webSocketUrl: true" in your capabilities and verify that your environment and browser supports it.
[chrome 130.0.6723.59 mac #0-0]     at iFramePage.switchToFrame (/Users/shannon.harris/work/wdio-test-repo/test/pageobjects/iframe.page.ts:21:9)
[chrome 130.0.6723.59 mac #0-0]     at iFramePage.assertEditorContent (/Users/shannon.harris/work/wdio-test-repo/test/pageobjects/iframe.page.ts:16:9)
[chrome 130.0.6723.59 mac #0-0]     at Context.<anonymous> (/Users/shannon.harris/work/wdio-test-repo/test/specs/test.e2e.ts:18:9)


Spec Files:      0 passed, 1 failed, 1 total (100% completed) in 00:00:04
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### PR DESCRIPTION
**Pull request by christian-bromann**
## Proposed changes

fixes #13776

## Types of changes

[//]: # (What types of changes does your code introduce to WebdriverIO?)
[//]: # (_Put an `x` in the boxes that apply_)

- [ ] Polish (an improvement for an existing feature)
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (improvements to the project's docs)
- [ ] Specification changes (updates to WebDriver command specifications)
- [ ] Internal updates (everything related to internal scripts, governance documentation and CI files)

## Checklist

[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._)

- [x] I have read the [CONTRIBUTING](https://github.com/webdriverio/webdriverio/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added the necessary documentation (if appropriate)
- [x] I have added proper type definitions for new commands (if appropriate)

## Backport Request

[//]: # (The current `main` branch is the development branch for WebdriverIO v9. If your change should be released to the current major version of WebdriverIO (v8), please raise another PR with the same changes against the `v8` branch.)

- [x] This change is solely for `v9` and doesn't need to be back-ported
- [ ] Back-ported PR at `#XXXXX`

## Further comments

n/a

### CODE REVIEW

File: packages/webdriverio/src/commands/browser/switchFrame.ts [hunk 1]
```diff
@@ -49,73 +68,211 @@ export async function switchFrame (
...
+
+        /**
+         * Fetch all iframes located in any available frame
+         */
+        const allFrames = (await Promise.all(Object.keys(allContexts).map(async (id) => {
+            /**
+             * first, fetch all iframes in given browsing context
+             */
+            const { nodes } = await this.browsingContextLocateNodes({
+                locator: { type: 'css', value: 'iframe' },
```
Comment (danielhjacobs) [inline packages/webdriverio/src/commands/browser/switchFrame.ts:141]: Does this also work for classic frames: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame?

**Comment by torokati44** [comment]
Does this also fix https://github.com/webdriverio/webdriverio/issues/13763 perhaps? :thinking:
